### ISSUE TITLE
Migrate to XCFrameworks

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#1036]
Currently, since a framework can only contain one copy of its binary per CPU architecture, we have to remove the slice for simulators on Apple Silicon Macs. XCFrameworks don’t have this issue, but SDWebImageSwiftUI does not support them (https://github.com/SDWebImage/SDWebImageSwiftUI/issues/156). Ideally, we would fix whatever problem is on their end so we can enable XCFrameworks before we get anyone using Apple Silicon Macs for dev.

**Comment by evancrow** [comment]
Fixed by #2923
