### ISSUE TITLE
We should try to provide a more user friendly description of the external app a link will open in

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1040]
We should try to provide a more user friendly description of the external app a link will open in

See example here of the app store:

<img src="https://user-images.githubusercontent.com/79867437/126381708-1e5162bd-501b-4004-99db-4311d1bbe2f8.png" width="300">

Not a very user friendly description of what will happen. We should ideally translate that to "Open this on the App Store?"

Perhaps there is some way to get app meta data (name, etc.) based on the URL scheme.

@evancrow FYI

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfegk
