### ISSUE TITLE
Investigate cross device login with iCloud keychain

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#1063]
Currently, we store cookie in keychain May be we can look into extending it to store some credentials or enable password autofill with the iCloud keychain to streamline the sign in process for user using the browser on another device.

https://developer.apple.com/documentation/security/shared_web_credentials
https://developer.apple.com/documentation/security/password_autofill

However, I'm not 100% sure if this works for our case since we are extracting the cookie from cookie storage. May be we need to rework the flow a bit to enable password autofill somewhere in order to make this work.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfen3
