### ISSUE TITLE
Autofill issues when using Gboard

### ISSUE THREAD

**Issue by builderthebob** [neevaco/neeva-ios#1133]
**User**: Kevin Mullins
**AuthType**: Okta
**SignupType**: survey
**Feedback**: Weirdly, the mobile app continues to auto-fill my email address in the search box each time I start a search using the first two letters. I.e. if I want to search “modern homes”, the search box automatically fill “motoliving@gmail.comdern homes”

Current URL: https://www.iheart.com/live/am-1300-the-zone-2181/
**Query**: -NA-
**Source**: `App`
**InviteToken**: `-NA-`
**RequestID**: `-NA-`
**Client**: co.neeva.app.ios.browser(1.0.5)
**FuzzedUserAgent**: NeevaBrowserIOS
**Browser**: BrowserNeeva(OSUnknown)
**Device**: ios-browser
**Geolocation Status**: 
**Github Issue**: -NA-

[Mode Report](https://app.mode.com/neeva/reports/960f6705e371?param_event_id=-NA-)

**Comment by jedireza** [comment]
I know this issue is really old. I just played a bit with the Gboard app and didn't notice any glaring bugs.
