### ISSUE TITLE
Consider migrating "profile.foo" preferences to something without the dot

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1209]
Consider migrating "profile.foo" preferences to something without the dot

Because of this bug in the Defaults package:
https://github.com/sindresorhus/Defaults/issues/59

It seems we cannot use Defaults.publisher / .observe because of this bug since all of our prefs are of the form "profile.foo". We can switch to "profile-foo" instead, but we will need to do a migration to avoid loss of user data.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfev1
