### ISSUE TITLE
Enable TestBrowserDB/testMovesDB

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#1236]
These 2 assertions fail:

https://github.com/neevaco/neeva-ios-phoenix/blob/4b1e3d0f81b3ee475dd6a1e7c7a7e783bfb9413d/StorageTests/TestBrowserDB.swift#L123-L124

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxff2d
