### ISSUE TITLE
Enable settings-related tests

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#1239]
For some reason, XCUI Testing is unable to toggle SwiftUI `Toggle` components in a `List`. Affected tests:

- [ ] `CopiedLinksTests/testCopiedLinks`
- [ ] `NavigationTests/testWriteToChildPopupTab`
- [ ] `SettingsTest/testDefaultBrowser`

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxff4z
