### ISSUE TITLE
Fix XCUITests.NavigationTest

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#1241]
- [ ] `testScrollsToTopWithMultipleTabs`
- [ ] `testDownloadLink`
- [ ] `testPopUpBlocker`
- [ ] `testURLBar`
- [ ] `testDownloadLink`

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxffr0
