### ISSUE TITLE
Fix how VoiceOver pronounces Neeva

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#1295]
It says something along the lines of “nay-eeva” at the moment. We can fix the issue for the app’s name by specifying `CFBundleSpokenName` in relevant `Info.plist` files, but I’m not sure there’s a way to consistently fix it across all strings.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxffw7
