### ISSUE TITLE
Re-enable testSuggestionsListNoNeevaSuggestionsForIncognito

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#1383]
It worked by passing `isIncognito` to the `SuggestionModel` initializer, which promptly threw that value away. The fact that it continued to pass despite not functioning as intended is concerning. I’ve disabled it for now.

**Comment by jedireza** [comment]
Moved to ClickUp https://app.clickup.com/t/3vxfg4x
