### ISSUE TITLE
Add wrapper script for running tests that will automatically re-run tests to determine if they are flaky

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1399]
Add wrapper script for running tests that will automatically re-run tests to determine if they are flaky

When a test fails, we can re-run the test again to see if it will still fail. Doing this automatically will help save us time, not having to re-run the tests manually ourselves.

The downside is that if the tests do succeed when re-run that we might become a bit blind to flakiness, and our tests will just run more slowly.

**Comment by evancrow** [comment]
Fixed by #3644
