### ISSUE TITLE
Consider alternative approaches to how we handle auth

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#145]
Consider alternative approaches to how we handle auth

This is a placeholder issue. We need to investigate alternatives to our current way of authenticating to Neeva search. Just using the cookie approach has downsides.

It could make sense to have the use sign-in at the browser level (via native app APIs), and then use that to generate the Neeva cookie. This way we can generate that again when needed and avoid the web-based auth flows.

**Comment by evancrow** [comment]
Outdated issue, #3614 is more relevant
