### ISSUE TITLE
Multiple overlapping calls to UserFlagStore.setFlag get silently ignored

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1452]
Multiple overlapping calls to UserFlagStore.setFlag get silently ignored

This code checks `state` to avoid sending a mutation if we are already sending a mutation:

```
    public func setFlag(_ flag: UserFlag, action: (() -> Void)?) {
        if case .sending = state { return }

        self.state = .sending

        UpdateUserFlagMutation(
        ...
```

Good. But what happens if the second call to `setFlag` is trying to set a different flag than the first? The second would just get ignored, and that flag would not get set.

Since we only use this to set a single flag at the moment (See PR #1451), there's no actual bug, but if we start trying to set other user flags then we might hit this bug. Flags might not get set when we call `setFlag` and the failure may appear quite flaky--sometimes working, sometimes not.

@macy-n FYI

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfgj3
