### ISSUE TITLE
Understand what happens when users skip the first run flow

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1627]
Understand what happens when users skip the first run flow

Do they eventually find their way to sign up / sign in? We could instrument more of the sign up / sign in paths to find out. We could also do things like measure number of page loads after skipping the first run flow. Hmm...

From @ramaswamy11703, one question that this will help answer is should we consider something radical like providing N free searches to users before requiring them to sign up.

@macy-n FYI

**Comment by jedireza** [comment]
I think we can close this. Preview mode is a thing now and we're logging engagement which can help us determine if we're converting. Please reopen if I misunderstood.
