### ISSUE TITLE
Share to Neeva > Save to Spaces > Login not working

### ISSUE THREAD

**Issue by macy-n** [neevaco/neeva-ios#1706]
I don't think many people use this path, so should be a low priority bug.

0) Make sure you are signed out of Neeva
1) Visit a url, i.e. amazon.com
2) Click the share icon the bottom bar
3) Select Share
4) Select Neeva (if you don't see Neeva, scroll right and click More)
5) Select Save to Spaces
6) Because you are signed out, you will see the page "Oops, this page is a little shy"
7) Click "Sign in with Neeva"

Expected behavior: You will be redirect to the Neeva sign in page"

Actual behavior: Panel closed and not redirected

Video
https://user-images.githubusercontent.com/61707598/133532576-2fe07aa9-6b2f-4b92-b715-3a5dcfb26a19.MP4

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfgt3
