### ISSUE TITLE
Spaces Detail UI is not fully accessible 

### ISSUE THREAD

**Issue by yozuysal** [neevaco/neeva-ios#1717]
#1716 addresses the lowest hanging fruit here, but I think the toolbar at the top needs a bit more work.

Right now, the individual space items, share button, more button and the items inside and the title for the header is accessible.

1. It is not possible to access the "Back" button inside the header. One of the reasons for this is the GridPicker below this UI is still accessible and captures touches. The other is, this back button doesnt have a label.
2. It is not possible to scroll down. We might want to audit ScrollViews we have in general and see if there are others we have missed.
3. The  tab switcher toolbar below this UI is still accessible. So can pick up touches, we should set it hidden while detail view is showing.

**Comment by jonathangarelick** [comment]
I'll add -- the "Expand Description" button inside the header is not accessible either.
