### ISSUE TITLE
ClipBoardTests.testClipboard() is flaky

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1749]
ClipBoardTests.testClipboard() is flaky

See for example:
https://app.circleci.com/pipelines/github/neevaco/neeva-ios-phoenix/4462/workflows/aab626b5-f382-4953-8091-d627fd9ad603/jobs/13287

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfgx7
