### ISSUE TITLE
DomainAutocompleteTest.testMixedCaseAutocompletion() is flaky

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1757]
DomainAutocompleteTest.testMixedCaseAutocompletion() is flaky

For example:
https://app.circleci.com/pipelines/github/neevaco/neeva-ios-phoenix/4478/workflows/6c71f333-d11c-4e2f-bbcb-44ceab406285/jobs/13351

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfh0p
