### ISSUE TITLE
The app looks pretty bad when Accessibility > Display & Text Size > Button Shapes is enabled

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1818]
The app looks pretty bad when Accessibility > Display & Text Size > Button Shapes is enabled

https://twitter.com/magic_of_thanos/status/1442607772881854464?s=20

<img src="https://user-images.githubusercontent.com/79867437/134998455-e7b6e649-ea3f-42e9-bb3f-7c8c55b6114d.png" width="300">
<img src="https://user-images.githubusercontent.com/79867437/134998468-d9a8ebf0-18b6-401c-a3a2-f7b156fd6dab.png" width="300">

This is iOS 15 specific.

**Comment by darinwf** [comment]
Another instance of a user seeing this issue:
https://github.com/neevaco/neeva/issues/70528

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfh31
