### ISSUE TITLE
ToolbarTests.testLandscapeNavigationWithTabSwitch() is flaky

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#1823]
ToolbarTests.testLandscapeNavigationWithTabSwitch() is failing on the bots

I'm seeing this test fail commonly on the bots, but not when run locally. Unsure if it is flaky. Not sure if I have seen it pass on CI.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfh59
