### ISSUE TITLE
[bug] Uploading a file on iOS opens the tab view

### ISSUE THREAD

**Issue by byjoshuadavis** [neevaco/neeva-ios#1841]
Hey folks, I’ve noticed a mild annoyance in the app. Uploading photos on iOS causes the screen to jump to the tab switcher view. To reproduce: 1) Go to Twitter.com and sign in / create an account. 2) Create a new Tweet and attach a photo. Observe: the new switcher opens: Expect: to always remain on the page until I click to switch tabs.

Assigning to @darinwf to triage as needed.

**Comment by jedireza** [comment]
I just tried this and didn't get the tab switching bug.
