### ISSUE TITLE
Top-sites ranking algorithm should take into account tabs that are refocused

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#188]
Top-sites ranking algorithm should take into account tabs that are refocused

I believe the current algorithm just counts navigations. We should also consider re-focusing a tab as a navigation. That way tabs that are frequently used aren't considered non-favorites by the user.

**Comment by darinwf** [comment]
This may actually already be the case, but we should confirm that it is and write tests to ensure that it remains the case.

**Comment by jedireza** [comment]
Moved to ClickUp: 🔒 https://app.clickup.com/t/3vxf3h1
