### ISSUE TITLE
Incorrect state for Spaces button fill: Removing a page that is in multiple spaces

### ISSUE THREAD

**Issue by yozuysal** [neevaco/neeva-ios#1959]
Steps to reproduce:

1) Add a page to more than one Space
2) Go to the tab for the page. The bookmark icon is filled.
3) Open addToSpace sheet to remove it from one of the spaces
4) The bookmark icon is not filled
5) Refresh page
6) The bookmark icon is filled back again

At step 4, after the deletion, we just set the icon state to false after a deletion. (This wrongly assumes there was only one space with the deleted item)

**Comment by jonathangarelick** [comment]
@yozuysal So I'm trying the following in `showToastForAddToSpaceUI`:
```
self.requestListener = SpaceStore.shared.$state.sink { [request] state in
  bvc.chromeModel.urlInSpace = SpaceStore.shared.urlInASpace(request.url)
  self.requestListener?.cancel()
}
```
but for some reason, `SpaceStore.shared.urlInASpace(request.url)` is always evaluating to `true`. Any suggestions?

**Comment by yozuysal** [comment]
from a first look: Check the value of state? If it is not .ready, then you shouldn't rely on urlInASpace. My guess is you are reading it while state = .syncing which means that things have not updated yet..
