### ISSUE TITLE
Option to lock browsing session when app is backgrounded

### ISSUE THREAD

**Issue by seth737** [neevaco/neeva-ios#1974]
Requested feature: introduce the option to lock the browsing session when the app is switched away from ("alt tabbed"). When the user comes back to the app, they would need to re-auth with face id or passcode to restore access to the app.

Other browsers on iOS implement some variant of this:

- Chrome has an option to lock access to incognito tabs when app is switched away from (this is off by default)
- Brave can lock access to entire app when app is switched away from (this is off by default)
- Firefox focus locks access to entire app when app is switched away from (this is on by default)
- Duck duck go can lock access to entire app when app is switched away from (this is off by default)

More discussion in this thread: https://neevaco.slack.com/archives/CMDAJCPCP/p1634252091316300

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfj0x
