### ISSUE TITLE
TabGroup cards disappear and flicker on scroll sometimes

### ISSUE THREAD

**Issue by yozuysal** [neevaco/neeva-ios#2086]
I think this especially happens when we have too many cards in the grid. Not seeing this on the spaces grid, so probably not a MultiThumbnail View issue. Had not seen this before, so it is probably regression from TabGroupCardDetails or CardContainer Tab List changes.

https://user-images.githubusercontent.com/83613310/139190304-b5835719-6a4a-445f-a48a-40d449f85e6f.mp4

**Comment by darinwf** [comment]
I think this issue no longer applies with the latest implementation
