### ISSUE TITLE
User report of needing to sign in repeatedly to use the app

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2208]
User report of needing to sign in repeatedly to use the app

This comment came in through the App Store:
<img width="602" alt="Screen Shot 2021-11-09 at 12 15 16 PM" src="https://user-images.githubusercontent.com/79867437/140997934-db47632a-e8e6-4e0b-b16e-f2dd3dc9be57.png">

**Comment by evancrow** [comment]
This was fixed a while ago, was an issue with Sign-in with Apple.
