### ISSUE TITLE
Space intro screen doesn't show up properly in landscape mode; then has trouble when device is rotated to portrait mode

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2293]
Space intro screen doesn't show up properly in landscape mode; then has trouble when device is rotated to portrait mode

Unfortunately couldn't get a screen capture.

In landscape mode, it looks like we open this dialog as an OverlaySheet. The bottom is cut off so you can't read all of the content. It isn't scrollable either.

Then when rotating the device to portrait, the dialog appears to be shown as a modal popover centered on the screen but squished because on a phone there is not a lot of horizontal space in portrait mode.

Switching back to landscape, and it appears to go back to being a bottom sheet. Same as before.

**Comment by jonathangarelick** [comment]
@darinwf Could you clarify what the Space intro sheet is? I am definitely seeing some problems in landscape mode, but I'm not sure exactly what you are referring to.

This part is looking good on the iPhone 13 Simulator:
<img src="https://user-images.githubusercontent.com/41495718/161451085-484fa988-fc13-4676-adc8-d27337c0d94e.png" width="550">

I'm also seeing the following issues on the Space Detail page in landscape view:
-Space header not visible in an empty Space
-Space items not properly padded, so they are being hidden by "the notch"
