### ISSUE TITLE
Stop passing BrowserViewController around everywhere

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2365]
Stop passing BrowserViewController around everywhere

The path to less spaghetti code starts with having fewer god objects. BrowserViewController is such a god object. We should be striving for more modular code. This is good for many reasons: makes the code easier to reason about, makes the code more malleable and makes the code more testable.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfjk9
