### ISSUE TITLE
SAYT results vary from request to request

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2425]
SAYT results vary from request to request

I'd expect that since this is served out of a cache that it should be consistent and stable.

See video:

https://user-images.githubusercontent.com/79867437/145662488-d9a6a8d7-ae35-4db0-8ea0-50c27cf14bb0.MP4

@chung-lai @kevchn @kelvinso FYI

**Comment by darinwf** [comment]
@chung-lai @yifanj0 - We believe our SAYT results should be stable now, right?

**Comment by yifanj0** [comment]
> @chung-lai @yifanj0 - We believe our SAYT results should be stable now, right?

Yes

**Comment by darinwf** [comment]
Thanks for confirming. Marking as closed.
