### ISSUE TITLE
RTL Fixes

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#2517]
- [x] Flip horizontal swipes in tab switcher in RTL
- [ ] consider un-flipping share/tracking protection in the URL bar (since RTL countries still have right-handed people and we want share to be more convenient, right?)
- [ ] flip link icons in settings
- [ ] consider un-flipping View Spaces and create space  in add-to-space dialog for ergonomic reasons

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfjp0
