### ISSUE TITLE
The cheatsheet should use the resolved query rather than the typed query

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2535]
The cheatsheet should use the resolved query rather than the typed query

If a user types "chocol" and then selects a fast-tap result under "chocolate", then we should note that so that when the Cheatsheet is opened we can show more query results for "chocolate" instead of using "chocol".

It might be nice if the Cheatsheet actually said what query it was showing results for (unless it was using the current URL as the query). We might also expand on this idea and also show an option the user could tap on to instead see results for "chocol" (what they exactly typed).

@macy-n FYI

**Comment by EdwardJTL** [comment]
done in #2830
