### ISSUE TITLE
one password extension may be deprecated?

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2556]
It looks like mozilla-mobile/onepassword-app-extension is just a branch of https://github.com/agilebits/onepassword-app-extension/, and according to https://github.com/agilebits/onepassword-app-extension/pull/465, it looks like this extension is being deprecated. I'm not sure what that means exactly, but we should probably investigate to find out if action is required. I noticed that Brave recently landed a change to drop this code.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfjtd
