### ISSUE TITLE
Investigate AnyView use in Overlay Views

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#2612]
As discussed on Slack:

Our overlay views, such as `OverlayRootView` and `PopoverRootView`, type-erase the presented content to `AnyView`. This discards the view hierarchy, and creates a new view identity every time any child view changes, which causes SwiftUI to redraw the entire hierarchy. Last year's [WWDC talk](https://developer.apple.com/videos/play/wwdc2021/10022/) has an explanation of how SwiftUI behaves this way.

I profiled the SwiftUI commands when opening the cheat sheet on a recipe page. 
![Screen Shot 2022-01-18 at 12 03 42 PM](https://user-images.githubusercontent.com/44557675/149989108-f8ce992c-9683-4e18-bde1-94c921d9e04c.png)
There seems to be an excessive amount of drawing commands. i suspect that this may also be due to a loop that calls `renderRichResult->AnyView` to populate things like related results.
Profiling expanding/collapsing the full recipe list seems:
![Screen Shot 2022-01-18 at 12 05 12 PM](https://user-images.githubusercontent.com/44557675/149989118-12c73f1a-b632-4412-a9f8-fa9ba7f5bc09.png)

Here is the trace file. It is not very organized sorry :( 
[cheatsheet_profile.trace.zip](https://github.com/neevaco/neeva-ios-phoenix/files/7891230/cheatsheet_profile.trace.zip)

as noted by @jed-fox-neeva, this will not be trivial to change since these views are currently used as a stored property in an Enum case `OverlayType`.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfyjd
