### ISSUE TITLE
Janky animation switching between incognito and normal tabs

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2705]
Janky animation switching between incognito and normal tabs

I'm seeing this on the latest TestFlight (1.25.4) w/ and w/o the new inline tab groups UX.

Video (or it didn't happen):

https://user-images.githubusercontent.com/79867437/151203418-7541707d-d206-4289-a6dd-db240038a739.MP4

**Comment by evancrow** [comment]
No longer able to repro
