### ISSUE TITLE
Default browser prompt dismisses itself and pops up again in the first run

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#2728]
This only happens when the app is first installed and after I signed in. I didn't touch anything on the screen.

https://user-images.githubusercontent.com/87332917/151479657-d1027db0-d4c9-4a25-8aeb-089f15812087.MP4

**Comment by evancrow** [comment]
Jeez, feel like we keep finding a fix and then it keeps coming back. I don't want to make the delay longer but that appears to be the only solution we have. I wonder if the apple system views are interfering with our views?

**Comment by chung-lai** [comment]
Fixed in https://github.com/neevaco/neeva-ios/pull/2890
