### ISSUE TITLE
Client logging privacy improvements

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#276]
Client logging privacy improvements

Invest in:
- Disabling for incognito sessions
- Aggregating data over time instead of reporting real time
- Anonymizing the data by sending to a different endpoint that doesn't pass the user login cookie?
- Providing users with a way to disable or consider if it should be opt-in
- Providing transparency on what is logged (see e.g., how Brave does this: https://brave.com/privacy-preserving-product-analytics-p3a/)

**Comment by jedireza** [comment]
We've made improvements in a lot of these areas. Also the new structured logging work is in flight. Closing.
