### ISSUE TITLE
WithPopover Timing Issue

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#2763]
It appears that sometimes `WithPopover` cannot present the popover due to this error

```
Client[52350:3883250] [Presentation] Attempt to present <_TtGC7SwiftUI19UIHostingControllerV6Client28CheatsheetTooltipPopoverView_: 0x7fd60515ee20> on <_TtGCV6Client11WithPopover21WrapperViewControllerVOS_17TabToolbarButtons9NeevaMenuVS_28CheatsheetTooltipPopoverView_S4__: 0x7fd605167d90> (from <_TtGCV6Client11WithPopover21WrapperViewControllerVOS_17TabToolbarButtons9NeevaMenuVS_28CheatsheetTooltipPopoverView_S4__: 0x7fd605167d90>) whose view is not in the window hierarchy.
```

To repro this, turn on cheatsheet_query flag, and `showTryCheatsheetPopover` in internal settings. Switch to a tab with a non neeva page. Switch to another tab with a non neeva page. Both of these should show the popover. then switch back to the first tab. the popover does not show, and the error message should appear in the console.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg2nm
