### ISSUE TITLE
Add Scrolling Offset to Cheatsheet

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#2813]
Cheatsheet should remember a scrolling offset.

Perhaps this can be tied to each `Tab` object where the cheatsheet query results are stored.

Laying the groundwork for #2611

**Comment by evancrow** [comment]
For this, could probably remember what query/link was tapped, and then use a ScrollViewReader to scroll to that object when the sheet reappears.

**Comment by darinwf** [comment]
> For this, could probably remember what query/link was tapped, and then use a ScrollViewReader to scroll to that object when the sheet reappears.

We might want to couple this with a caching solution so we can be sure that the content will be the same. There's a fun edge case if we are fetching the content again and it happens to be different than it was when previously fetched.

**Comment by EdwardJTL** [comment]
> For this, could probably remember what query/link was tapped, and then use a ScrollViewReader to scroll to that object when the sheet reappears.

cheatsheet does not use unique id's for each of its child views atm. we will also need to make sure that those id's are unique and unchanged in the scenario Darin mentioned
