### ISSUE TITLE
Sometimes selecting a tab doesn't show the web view and card transition animation

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#2835]
It happens once in 40~50 clicks... the new card gets selected and its border gets highlighted. But the card transition animation didn't happen and the webview is not shown.

**Comment by darinwf** [comment]
Are you seeing this correlate to having a lot of tabs in the tab switcher? (I'm guessing it would.)

**Comment by chassu** [comment]
Not really. The tab switcher only had < 10 tabs when I saw this.

**Comment by darinwf** [comment]
OK, I see. I didn't read the description carefully. You are seeing a card transition not happen. Does it work with a second tap?

**Comment by darinwf** [comment]
I believe I've been able to repro this by tapping on the tab before it finishes its transition animation.
