### ISSUE TITLE
Missing thumbnails

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2838]
From Ario:

<img src="https://user-images.githubusercontent.com/79867437/153308521-579cbab5-3c8b-4f5e-8e1c-41bd894135c8.png" width="300">

I've seen this too.

**Comment by darinwf** [comment]
I added some logging and observed the bug. Here's what I learned:

1. It looks like a newly added set of tabs did not have their screenshots saved.
2. It looks like the background thread where the screenshots are written out to disk did not run (see DiskImageStore.swift).
3. I did not see those background tasks getting interrupted. They just didn't seem to run.

Now, my logging was not as complete as it could have been. I don't see confirmation that we even attempted to start saving the screenshots, but I suspect we probably did.

It seems quite plausible that the app could get backgrounded when these screenshots have not yet been written out.

For other tabs state we take care to ensure background IO happens before we signal to the OS that we are ready to be killed. We should probably do that for DiskImageStore as well.

**Comment by darinwf** [comment]
Unfortunately, I don't think https://github.com/neevaco/neeva-ios/pull/3029 was sufficient to resolve this issue. I believe I observed the bug using 1.32.0, which included (see https://github.com/neevaco/neeva-ios/commits/Build-187) that change.

There must be more to this puzzle. Will need to add more logging and try to again catch it in the act.

**Comment by EdwardJTL** [comment]
> The times I've seen missing thumbnails recently may just be explained by this: #3089
> 
> Might just be that we are not taking a screenshot when we should.

in #3078 we don't have screenshots when opening link from cheatsheet because `createOrSwitchToTab` don't take screenshot. `BrowserViewController.finishEditingAndSubmit` may also call that function. Maybe we should look at when we should be taking screenshots in the code in general?

**Comment by darinwf** [comment]
@EdwardJTL - yeah, it's likely that one patch would fix both issues. I see that `TabManager.createOrSwitchToTabForSpace` calls `takeScreenshot`, so one approach would be to just mimic that code inside `createOrSwitchToTab`. I think that might be a reasonable place to start.

**Comment by darinwf** [comment]
Going to call this fixed now.

**Comment by darinwf** [comment]
Actually, nevermind... just re-read the last few comments.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg36y
