### ISSUE TITLE
Unable to dismiss UIAlert asking if I really want to delete a space

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2870]
https://user-images.githubusercontent.com/79867437/153903127-273464ec-fef5-434a-b037-4be72f59e611.MP4

If I go to delete a space, I'm just left seeing a modal alert dialog that gives me only one choice: delete

Tapping outside the dialog does nothing. Only way to dismiss is to quit the app.

FYI @yozuysal

**Comment by yozuysal** [comment]
I think this is true for a few other actionSheets in our hierarchy right now. Not sure of the reason. @evancrow FYI as well

**Comment by evancrow** [comment]
Likely need a dedicated cancel option
