### ISSUE TITLE
Disable swipe-to-close for now

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2877]
From UX review:

- Concerned that the current swipe-to-close treatment is too fiddly and that it is easy for people to accidentally close tabs; also easy for users to mistake the feature as drag-n-drop to group or reorder and then be surprised that it closes the tab.
- Swipe-to-close not working with collapsed groups is a concern as well.
- Pinch to close is overloading a zoom gesture, which might also surprise users or not be very discoverable
- Drag to trash area makes sense, but what we might do is have an “editing mode” for tabs that users activate through a new action in the overflow menu. In editing mode, users can drag tabs to a trash area, or drag to reorder / group / ungroup tabs.
- Would like to experiment with disabling swipe-to-close (i.e., put it behind a feature flag), and see if users complain about the absence of swipe-to-close. This will help us understand what matters to our user base and help us prioritize this feature.

**Comment by evancrow** [comment]
Another idea discussed in #2888 is a two-finger swipe for swipe to close, I will take a look into this

**Comment by darinwf** [comment]
This was done.
