### ISSUE TITLE
Cheatsheet Promo Popover May Flash During Startup

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#2884]
Opening a link to the app (e.g. spaces) may lead to the promo popover flashing if the condition to show the popover is met (from education flow or on recipe page).

https://user-images.githubusercontent.com/44557675/154003054-2d724e8d-e343-462c-ab5d-95fc7b7742ea.MP4

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg39k
