### ISSUE TITLE
No restore option after closing all tabs

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#2896]
We are exploring option not to show confirmation alert when user clicks "Close All Tabs" option; however, there is no restore option after closing all tabs. Is this an intended behavior?

cc @evancrow, @darinwf, @EdwardJTL

**Comment by evancrow** [comment]
Yes, we intentionally suppress the Toast because users have to confirm

**Comment by darinwf** [comment]
I notice that when using the "Close All Tabs" feature in the Tab Group context menu, I get both a confirmation prompt and a toast. However, when using the "Close All Tabs" feature from the switcher overflow menu, I only get a confirmation prompt. Perhaps these should behave consistently?

I think it is reasonable to not show the toast following a confirmation prompt.
