### ISSUE TITLE
Local/In memory Favicon Storage

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#2903]
For Spotlight search (see #2902), we need either an in memory copy of the image data or a URL to the local file system. We lack infrastructure for that.

I did a round of looking into how we get favicon's to show up in our app. It appears that we keep a url to the `.ico` file and load it each time with `WebImage()`. Maybe this is an opportunity for us to write a class that does more local operations than loading from webURLs?

**Comment by darinwf** [comment]
I think we rely on WebSDImage's cache. Perhaps we should explore if that cache can be visible to our spotlight card (perhaps by being in the same appgroup). Of course since that's a cache, it won't be perfect. The other option is to have some persistent store of icons corresponding to the full set of icons that we might need to support the spotlight card.

**Comment by darinwf** [comment]
Studying https://github.com/neevaco/neeva-ios/pull/2902, I see that it doesn't work as I had imagined. I was imagining an app extension that ran in a more tightly controlled sandbox or something. Instead, this is just about us publishing data to spotlight. Have you considered passing the favicon image data directly? We do have it for each tab, so we could just pass it along as part of the `NSUserActivity`.

**Comment by EdwardJTL** [comment]
> Studying #2902, I see that it doesn't work as I had imagined. I was imagining an app extension that ran in a more tightly controlled sandbox or something. Instead, this is just about us publishing data to spotlight. Have you considered passing the favicon image data directly? We do have it for each tab, so we could just pass it along as part of the `NSUserActivity`.

i wasn't able to find a non-nil instance of the favicon data. The `Favicon` struct in `Tab` contains a web url but not image data

**Comment by darinwf** [comment]
What data type does `NSUserActivity` want?

**Comment by EdwardJTL** [comment]
> What data type does `NSUserActivity` want?

`NSUserActivity` wants a `CSSearchableItemAttributeSet`, which wants either
1. a `Data` type instance: Image data that represents the thumbnail of the item.
2. a `URL` type instance: The local file URL of the thumbnail image for the item.
