### ISSUE TITLE
Unable to Slide NeevaScope Back to Middle Position

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#2910]
When I open the NeevaScope menu and then slide it up, I cannot reset it back to the middle (I can only dismiss it). See video for more:

https://user-images.githubusercontent.com/37356984/154739461-e44f3039-ee33-4fee-b3c9-6c8639d55095.MP4

FYI @EdwardJTL

**Comment by EdwardJTL** [comment]
hmm i just tried and i can slide it to the middle position. it looks like you might have dragged it too far...?

**Comment by evancrow** [comment]
I tried it from a bunch of spots. In the video, you can see I let go above the original position so it should have slid to the middle. Are you testing from the IntroPage?

**Comment by EdwardJTL** [comment]
would you be able to set breakpoints on on drag ended to see why it's calculating it to be in the dismissed state? i can't reproduce this :(

**Comment by evancrow** [comment]
Can't repro anymore, will reopen if I see it again!
