### ISSUE TITLE
Regression: Create space overlay is sized incorrectly

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2911]
https://user-images.githubusercontent.com/79867437/154739867-34e80992-4acc-4631-ba91-47601af0c4fb.MP4

FYI @EdwardJTL @evancrow

**Comment by evancrow** [comment]
This is an issue with the keyboard ignoreSafeArea... ugh. One issue is that fixing this usually breaks the keyboard somewhere else. Maybe the solution is to actively use negative padding to bring the view down to the height of the keyboard.
