### ISSUE TITLE
Overlaysheet can keep creeping up when accessing app switcher

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#2913]
https://user-images.githubusercontent.com/44557675/154749553-f85969af-bc32-4c11-8131-580d09b51774.MP4

**Comment by darinwf** [comment]
Awesome bug!

**Comment by evancrow** [comment]
Hmm, I remember we had a bug a while ago that had to do with swiping up to go home. The issue is that apple really protects that gesture, but maybe we can listen for when it's activated and disable Overlay view movement if it's active? Seems like a minor bug though so not too urgent.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg3e7
