### ISSUE TITLE
NeevaScope Intro Cutoff on Compact Devices

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#2918]
On iPhone SE:
![image](https://user-images.githubusercontent.com/37356984/154884353-1639685d-0574-41b5-80e2-7c7537a87b66.jpeg)

FYI @EdwardJTL

**Comment by EdwardJTL** [comment]
I'll see if I can add the middle preferred height to this; not sure if the animation will look good. 

Otherwise I'll try to wrap things in zstacks and manually calculate image size.

**Comment by EdwardJTL** [comment]
fixed in #2933
