### ISSUE TITLE
Sharing a pdf link via share sheet doesnt work

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#2926]
but copying it with the button that shows up when you edit url works

**Comment by evancrow** [comment]
So it actually is copying, but it's copying the _file_ not the URL. I can add an option to copy the url, and then change copy to copy file.

**Comment by EdwardJTL** [comment]
Oh interesting... yea I think "copy url" and "save to files" make sense

**Comment by evancrow** [comment]
Gonna wait on this one, we can't change the Apple Share Sheet elements like Copy...

**Comment by darinwf** [comment]
How do other browsers handle PDFs?

**Comment by jedireza** [comment]
I was able to share a PDF that I was viewing in a tab with another app and it worked as I expected. If this is still an issue please open a ClickUp ticket with some repro steps.
