### ISSUE TITLE
release script failing

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#2930]
I'm getting this error when running build-release.sh

```
*** Error: Error uploading '/tmp/Neeva.ipa'.
*** Error: CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.dailymotion.SDWebImage' under the iOS application 'Client.app'. With error code STATE_ERROR.VALIDATION_ERROR.90685 for id b4c4caf2-08de-485b-8d40-f4ebe8b6a0c6 Asset validation failed (-19208)
```

I'm guessing it's related to rebuilding Carthage after https://github.com/neevaco/neeva-ios/pull/2923. @j-f1 Do you have any idea?

**Comment by j-f1** [comment]
This is probably because multiple things are using the `SDWebImage` package. Making sure it’s only embedded by one target (perhaps `Shared`?) should fix it
