### ISSUE TITLE
Weird bottom bar position after installing app and signing in

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#2937]
https://user-images.githubusercontent.com/87332917/155650974-f29c8167-b3af-443b-b345-9b08c3fdeb64.MP4

**Comment by yozuysal** [comment]
thanks for catching Charles!

**Comment by chassu** [comment]
Saw you marked it as release blocker. Should I not submit to app store review today then?

**Comment by yozuysal** [comment]
It is fine to submit for review, but if this is a consistent repro, unless we have something critical going out, it would be good to hold off releasing even when approved. Ideally we should fix and then resubmit.

So maybe submit for now and let's assess a fix tomorrow morning?

**Comment by evancrow** [comment]
@chassu I think I have a fix for this, wasn't able to recreate it but if I upload can you try it out?

**Comment by chassu** [comment]
yup!

**Comment by evancrow** [comment]
https://github.com/neevaco/neeva-ios/pull/2940

**Comment by chassu** [comment]
Cherry-pick'ed your change onto the release branch and still see the same bug :'(

**Comment by evancrow** [comment]
Hm okay, I'll look into another approach then

**Comment by evancrow** [comment]
@chassu and I have been debugging and the issue seems very rare, and difficult to reproduce (isolated to one device, iPhone 12, iOS 14.8). Will keep looking into it, but does not seem to have a large impact to block the release.

**Comment by darinwf** [comment]
@evancrow @chassu - Is this bug still valid? Are you still able to repro?

**Comment by evancrow** [comment]
Don't think so, can probably close
