### ISSUE TITLE
Not sure if shield icon is showing correct stats 

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#2938]
<img src="https://user-images.githubusercontent.com/87332917/155651092-76a9854c-f5c0-4e2b-9836-dd1a5539abff.png" width="200"/>

<img src="https://user-images.githubusercontent.com/87332917/155651104-90ec3515-0447-4280-baae-796652c22e2c.png" width="200"/>

**Comment by evancrow** [comment]
What's the issue here? Do you think there are trackers being blocked that aren't being counted in the menu?

**Comment by chassu** [comment]
yeah, that was what I was thinking
