### ISSUE TITLE
Unable to Run Simulator on M1 Mac

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#2941]
@j-f1 I tried building on M1 Mac, but I keep getting a build error with `SwiftyJSON`: 
> Could not find module 'SwiftyJSON' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64, at: /Users/evan/Library/Developer/Xcode/DerivedData/Neeva-bttvrogdodowqjfxqyeqaqfgtbxh/Build/Products/Debug-iphonesimulator/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule

Reset all the excluded architectures, cleared `Carthage/Build`, re-ran `sh ./bootstrap.sh` but no success :(

**Comment by j-f1** [comment]
It works fine for me (iPhone 13 simulator, on 5c23bcad6) — try doing a clean (Product → Clean Build Folder) then rebuild?

The fact that it’s looking for a `.framework` suggests something isn’t properly updated.

**Comment by evancrow** [comment]
Same issue unfortunately

**Comment by evancrow** [comment]
Does it work from `main` for you?

**Comment by j-f1** [comment]
https://github.com/neevaco/neeva-ios/commit/5c23bcad66ba1712b3167c0a18e04ba48c811853 is `main` at the moment.

**Comment by j-f1** [comment]
I’m building the normal Client target — is that what you’re trying to build too?

**Comment by evancrow** [comment]
Yup, `Client`, iPhone 13 Pro, Xcode 13.2.1, Macbook Pro 13" (M1)

**Comment by evancrow** [comment]
Maybe related but I'm seeing this error in the console:

> ld: warning: directory not found for option '-F/Users/evan/Desktop/Work/Neeva/Neeva-iOS/Carthage/Build/iOS'

**Comment by j-f1** [comment]
I’ve seen that too but it seems to work fine — maybe update the `FRAMEWORK_SEARCH_PATHS` settings in the xcodeproj?

**Comment by evancrow** [comment]
Hm, didn't seem to resolve the warnings or the compile error. I did run Xcode via Rossetta and that seems to fix the build errors actually, not preferred but it works.
