### ISSUE TITLE
Laggy autocomplete (shows result for previous query)

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2973]
@nathanwiegand demo'd this bug for me today. Perhaps because he has a large local history database, the queries made to autocomplete the typed prefix come back slow enough that by the time there is an autocomplete result, the next character has already been typed. If we then append the autocomplete result, it can momentarily result in a bad autocompletion.

E.g., if typing "fo" completes to "foobar", but the user is quick to type another "o", the URL bar will momentarily show "foo[obar]"

It seems to indicate that we are not handling a slow history lookup properly. @chung-lai FYI

**Comment by chung-lai** [comment]
Sounds like the problem is still happening even after the fix (#2794). just to confirm, @nathanwiegand, are you running the latest version of the app? The fix was to reset the autocomplete lookup when you type so it should not show in the address bar even with a long look up.

**Comment by nathanwiegand** [comment]
1.29.3 (177.2)

**Comment by darinwf** [comment]
@chung-lai - Looking at the code, it looks like we only check if `currentDeferredHistoryQuery` is non-nil, but when the user types another character that is going to set `currentDeferredHistoryQuery` to non-nil. So the previous request when it completes, it would see that `currentDeferredHistoryQuery` is non-nil so it would still proceed. I think we need some way to distinguish old queries from new queries. A sequence number could work, or something like that.

**Comment by darinwf** [comment]
Actually, I take that back. The following check should be sufficient to guard against this scenario:

```
                guard !deferredHistory.cancelled else {
                    return
                }
```

I'm looking at the `subscribe()` function in `SuggestionModel`

**Comment by chung-lai** [comment]
Right, saw that `cancel` property and thought that will take care the case. Feels like there is a race condition somewhere else. I tried to reproduce the issue before by adding a delay in that code path. There is another option in settings to slow down the db operation but doesn't seem to work :) I guess I should try writing a script to inject many sites into the sqlite table to reproduce the issue.

**Comment by darinwf** [comment]
Could also add some Logger calls and ask Nathan to collect a log file for us. That would be pretty easy.

**Comment by chung-lai** [comment]
@nathanwiegand, could you please try out v1.31.5 see if the patch helps. Thanks!

**Comment by nathanwiegand** [comment]
It's fixed!  Though now it's pretty laggy. But i'll take laggy over buggy anyday

**Comment by chung-lai** [comment]
Great! It's a quick patching for fixing the issue. Have a couple ideas about addressing the performance part like the idea you suggested about maintaining a separate table for domain look up or do some caching.

Will keep this issue open as we haven't fixed the laggy part.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg50h
