### ISSUE TITLE
PDF thumbnails are not saved

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3001]
As part of investigating why thumbnails are sometimes blank (see https://github.com/neevaco/neeva-ios/issues/2838), I've noticed that PDF thumbnails are never saved.

**Comment by darinwf** [comment]
It looks like the `jpegData` calls made when storing the thumbnails to the `DiskImageStore` fail in this case.

**Comment by darinwf** [comment]
Chrome and Firefox also have this bug.

I see that `UIImage.jpegData` is failing and yet there is a non-nil and non-empty underlying `CGImage`. Hmm...

**Comment by EdwardJTL** [comment]
This function may return nil if the image has no data or if the underlying CGImageRef contains data in an unsupported bitmap format. perhaps the bitmap format is not supported by UIImage? we could redraw the CGImage or ask the CGImage to write to a png/jpg file and then ask UIImage to read from it?

**Comment by darinwf** [comment]
Perhaps we can just log details about the CGImage to see how it differs in the PDF case from the normal case. Maybe that will give some clues. I like the suggestion about redrawing the CGImage or what not. Seems like there should be a solution here.
