### ISSUE TITLE
Back Button does not work after opening a page from SRP 

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3010]
The back button is broken on a page opened from SRP. Nothing happens and the button gets grayed out. Going to tab switcher and then the back button is working again.

https://user-images.githubusercontent.com/44557675/156986774-a1f6aba4-b3f8-4195-b595-b148c79f2286.MP4

**Comment by darinwf** [comment]
I think this bug might be unique to this site. Other links work fine. There is something odd about that particular page and how it interacts with our simulated back support.

**Comment by evancrow** [comment]
Yeah seems to work fine pretty much anywhere, safe to remove `release blocker` @darinwf?

**Comment by darinwf** [comment]
Yes, not a release blocker. Interesting bug though. Maybe there is some pattern and this is not the only link click that will exhibit this issue. Definitely a good one to understand and fix.

**Comment by evancrow** [comment]
Did some investigating:
- On the site you showed, it's filling up the back stack with the same URL over and over
- The BackForwardView only shows one URL though which means we're handling something right there
- Tapping the tabs button seems to fix the issue

So even though the website is doing some shady things, we're still handling something wrong. More investigating!

**Comment by jedireza** [comment]
Going to close this since it's not a wide spread bug. If we can identify something we should be doing differently let's file a new issue with details and/or bug repro steps.
