### ISSUE TITLE
It is possible for a modal alert dialog to appear on top of our tab switcher

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3034]
It is possible for a modal alert dialog to appear on top of our tab switcher

See this issue for a screenshot from a user about what this looks like:
https://github.com/neevaco/neeva/issues/65978

I'm not quite sure how this is possible. I wonder if a tab in the background is capable of running script and generating an alert() after the tab has been hidden. I think the user is experiencing that it is hard to close this dialog, so maybe the web page is generating these prompts over and over again.

The report from the user indicates that they are locked out of being able to use the browser when this happens.

**Comment by evancrow** [comment]
This must be a tab using `alert()`... I wonder if #3026 could prevent this?

**Comment by darinwf** [comment]
Yes, that might help. We should construct some evil test cases and see if we can repro what the user was seeing.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg5u6
