### ISSUE TITLE
Couple of Tab Group Bugs

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3039]
@chassu found a few issues with tab groups:

1. Missing corner radius on upper trailing when in compact mode:
<img src=https://user-images.githubusercontent.com/37356984/157581291-88e3f81e-23fc-42c6-ba98-67538b32beb8.png width=300>

2. Order of tab group changes when I relaunched the app:
(see previous image for before relaunching), after relaunching:
<img src=https://user-images.githubusercontent.com/37356984/157581331-9514d525-4b6a-45c3-922a-77aa07fe0dff.png width=300>

The Neeva tab (parent) moved from first to last.

**Comment by chassu** [comment]
For 1, do you mean leading or trailing? I thought the upper leading corner should be rounded...?

**Comment by evancrow** [comment]
Trailing, my mistake!

**Comment by chassu** [comment]
I can understand the issue when it's scrolled to the end of the horizontal scroll view. But do you think it makes sense to round the corners given the compact mode can go to anywhere in the horizontal scroll view?

**Comment by chassu** [comment]
I can't find an example of a tab group's corner when it's scrolled to the end in compact mode.

https://www.figma.com/file/t1jW7cahkClVHAIlnHJuv8/Tab-Manager-(Spaces-%26-Tab-Groups)?node-id=156%3A549

**Comment by evancrow** [comment]
I think it's safe to assume that it should be rounded when it's at the end, but you can add it to Design Open Hours to get an opinion from @Ria-yu. I think the second issue is a bit more pressing and may take some more investigation. Would focus your time there till you can ask design about the first issue.

**Comment by chassu** [comment]
If we round the corners when it's at the end, then we'll also un-round the leading corners when it's not at the front according to the logic...? What do you think?

**Comment by evancrow** [comment]
Makes sense to me!

**Comment by chassu** [comment]
I can't repro the second point. Can you share how you repro the bug?
