### ISSUE TITLE
Regression: Back button is tappable but does nothing after taking a suggested search from the preview experience

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3071]
The back button is not disabled but tapping on it does nothing.

[Observed using 1.32.1]

https://user-images.githubusercontent.com/79867437/158026957-edec8627-277b-43fb-bb83-31c4f329a865.MP4

**Comment by darinwf** [comment]
Probably the back button should just be disabled in this case since the user did not type in a query.

**Comment by evancrow** [comment]
Just tried it and I cannot recreate it :(

https://user-images.githubusercontent.com/37356984/158029000-640df6f4-b187-472c-84de-519f475d547c.mp4

**Comment by darinwf** [comment]
Hmm... okay, let me see if I can figure out why I am seeing this...

**Comment by evancrow** [comment]
@darinwf Can we remove the release blocker label from this?

**Comment by darinwf** [comment]
Can't repro this anymore on `main`. Going to just close it.
