### ISSUE TITLE
Tab group created through new navigation to hub site breaks existing tab group

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3088]
Steps to repro:

1. Start with no tabs
2. Open a tab to news.ycombinator.com
3. Click on a link
4. Open a new tab to news.ycombinator.com
5. Click on a link
6. Open a new tab to news.ycombinator.com

Expected outcome:
Should see one tab group with 3 tabs in it

What happens instead:
See one tab group with 2 tabs in it and another tab on its own

What's going on:
When looking for a tab with matching originalURL, we assign the first tab we find to a new tab group with the newly opened tab. That has the effect of removing the existing tab out of its existing tab group.

Instead we should:
If a matching tab is already in a tab group, then just add the newly opened tab to that tab group.

One of the challenges here is that at the TabManager + Tab level, the only indication of a Tab being in a group is its rootID property. I think the only way to tell if it is not a solo tab is to check if other tabs share the same rootID property.

@evancrow FYI

**Comment by yozuysal** [comment]
TabGroupManager keeps a running map of rootID to children. Maybe we need to move the ownership of TabGroupManager to TabManager so that this query is easily accessible?

**Comment by darinwf** [comment]
@yozuysal - That sounds like a great idea!

**Comment by darinwf** [comment]
I see... TabGroup and TabGroupManager are defined in BrowserPrimitive.swift, so perhaps we'd extract the core bits of each and leave behind a set of extensions that implement AccessingManager, ClosingManager, etc. Makes sense.

**Comment by evancrow** [comment]
Or we could pass TabGroupManager to TabManager and leave it as a separate class? It's defined in BVC so it would be easy to pass on `init`.

**Comment by evancrow** [comment]
Another option would be to declare `TabGroupManager` inside `TabManager` (and pass `TabManager` as a `weak` reference to avoid circular dependencies). I kind of like that one since we can cut `BVC` out of the picture.

**Comment by darinwf** [comment]
I still see this bug in TestFlight build 1.32.6 (192.1). @chung-lai FYI
