### ISSUE TITLE
Crash @ [ TabGroupCardDetails.init ] Pinned tab may be causing a crash

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3091]
<img width="1185" alt="Screen Shot 2022-03-14 at 12 55 36 PM" src="https://user-images.githubusercontent.com/44557675/158222007-e95c3996-19a9-455e-a96f-b190a3a44285.png">

crash on `TabGroupCardModel.onDataUpdated()`->`map`->`init`->`init`. 
This seems to come from `TabGroupCardDetails.init`
checking this init routine,  we have force unwrapping `lhs.pinnedTime! < rhs.pinnedTime!`

we have a variable `isPinned: Bool` and `pinnedTime: TimeInterval?`. 

the simple fix for the crash itself is to use `if let pinnedTime` instead of `isPinned`. But really these should be more tightly coupled together to avoid them being out of sync. So perhaps we should use an enum with an associated value, or just use `@Published pinnedTime: TimeInterval?` and maybe a computed variable to check isPinned; I anticipate this will call for changes on the SwiftUI side as well.

**Comment by darinwf** [comment]
I think this bug might be caused by a user (namely @Ria-yu) having used pinned tabs from an earlier implementation that only defined `isPinned` but not `pinnedTime`. This code assumes that both must be set but that would only be true of new users.

@chassu FYI

**Comment by darinwf** [comment]
Another potential issue I'm seeing is that using `TimeInterval` is not a good idea for persisting a timestamp. We should be using `Date` instead.

**Comment by darinwf** [comment]
> Another potential issue I'm seeing is that using `TimeInterval` is not a good idea for persisting a timestamp. We should be using `Date` instead.

Actually, I think it is okay because we are using `Date().timeIntervalSinceReferenceDate`, and I stand corrected, I do see `pinnedTime` being set now. Not sure how I missed it before.
