### ISSUE TITLE
Screenshot of newly opened tab not taken when long press is used to open a new tab

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3094]
@EdwardJTL @chassu FYI

**Comment by EdwardJTL** [comment]
To clarify, do you mean the current tab or the new tab does not have a screenshot taken? and is this with or without pressing "switch" on the toast?

**Comment by darinwf** [comment]
> To clarify, do you mean the current tab or the new tab does not have a screenshot taken? and is this with or without pressing "switch" on the toast?

I updated the description sorry. I meant the tab that is opened via long pressing. If you go to the tab switcher, the screenshot is not shown.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg66b
