### ISSUE TITLE
[iOS - FR] Clear browsing data - UI & Text update

### ISSUE THREAD

**Issue by hwiatneeva** [neevaco/neeva-ios#3125]
FR is the following, and in the iOS convention....

Thread with Android design and text updates:

> [Darin Fisher](https://app.slack.com/team/U01PJ0VGR70)  [22 minutes ago](https://neevaco.slack.com/archives/C01QW9Z7P3P/p1647375125969099?thread_ts=1647035369.474999&cid=C01QW9Z7P3P)
Would love when time permits to have a version of this design for iOS too :wink:

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg6kz
