### ISSUE TITLE
Suggested sites not showing up on compact state

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3135]
Suggested sites on ZeroQuery not showing up in compact state but shows up when it's fully expanded:

![IMG_5651](https://user-images.githubusercontent.com/87332578/158641361-b9b23bc0-0cb3-4c2b-9abf-98000d57bcfc.PNG)
![IMG_5652](https://user-images.githubusercontent.com/87332578/158641371-ef98bd3c-b07c-4a46-8b90-bd6ec23070c0.PNG)

Starts happening in 1.32.5. fyi @evancrow.

**Comment by chung-lai** [comment]
Looking back at the set of changes, could it be related to #3067?

**Comment by evancrow** [comment]
It seems to be related but I don't know how... suggested sites is inside a SwiftUI view which appears to be rendered just fine.

**Comment by darinwf** [comment]
SnapKit was used by the horizontal scroller, so it could be a good one to explore.
