### ISSUE TITLE
Clicking a link to open Neeva from Mail crashes if selected tab has JavaScript alert

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3139]
Found this while browsing old Firefox iOS issues.

Link to FF issue: https://github.com/mozilla-mobile/firefox-ios/issues/9541
Url for convenience: https://mypay.dfas.mil/#/

Demonstration:

https://user-images.githubusercontent.com/41495718/158723950-8b43062e-04e9-47b8-8ca4-d3c286c731f5.mov

**Comment by darinwf** [comment]
Thanks for finding this!

**Comment by darinwf** [comment]
@jonathangarelick - you fixed this bug right?

**Comment by jonathangarelick** [comment]
I don't believe so.

**Comment by darinwf** [comment]
> I don't believe so.

OK, I guess I was thinking about a different issue then.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg6z4
