### ISSUE TITLE
Large memory usage when we index space items for spotlight

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3155]
Noticed a few memory crash when I used the testflight app 1.32.10 and saw one in my log with `cannot allocate memory`. Looking at simulator with memory usage pattern, notice that after using the app for a while, the memory keeps going up from 150mb to 1.9gb in my case. 

Putting a breakpoint in some spotlight indexing code, every time the memory spikes, that piece of code got triggered (https://github.com/neevaco/neeva-ios/blob/main/Shared/API/SpaceStore%2BCoreSpotlight.swift#L94-L97)

@darinwf, this may explain some crashes you experience earlier in the week without crash stack. fyi @EdwardJTL

**Comment by EdwardJTL** [comment]
@darinwf when you looked for on device logs for the mysterious crashes, did you check if there's any jetsam events logged during the time period of interest?
App killed by memory might be the reason why there was no testflight crash report.

**Comment by chung-lai** [comment]
Didn't know about jetsam before, that's cool! Somehow I don't see any got generated from today, may be I got a crash report instead.

**Comment by chung-lai** [comment]
Remove the release_blocker label as that should be addressed by the PR. Will leave this open until we find a fix for the thumbnail or feel free to open another issue if you like, @EdwardJTL . Thanks for fixing it so quickly!
