### ISSUE TITLE
Tabs not generated in tab group properly

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#3157]
Starting to see this bug after #3146 

It also leads to tab that has no title and screenshot that is not closeable

https://user-images.githubusercontent.com/87332917/158907914-b408a0f6-66f9-48dd-8902-4753045072b3.MP4

@evancrow @darinwf fyi

**Comment by chung-lai** [comment]
You were not seeing this if you download previous build? (like 1.32.9?)

**Comment by chassu** [comment]
I don't see this on 1.32.9. (Just downloaded and tested it)

**Comment by evancrow** [comment]
@chassu I reverted #3146, can you make sure the bug is gone

**Comment by chassu** [comment]
yep, don't see it on main after the revert

**Comment by evancrow** [comment]
Closing then!
