### ISSUE TITLE
Clicking a link in a Space animates in the wrong direction

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3173]
Noticed this morning. Not sure if this is intentional, but when I click a link in a Space, I expect that the transition will animate from right to left, not the other way around.

Demo:

https://user-images.githubusercontent.com/41495718/159290063-a0443150-6e8d-42d6-9154-fe7b5e3bdc6c.mov

**Comment by jedireza** [comment]
In #3610 I also mention how if we transition to the right, swiping back should also work as expected.

**Comment by yozuysal** [comment]
yeah, this currently is the animation we get for free and is the system default for clicking on a Navigation link. We are overdue to redo this and the animation coming back to the space from the link clicked as well.
