### ISSUE TITLE
Unable to handle external URLs that have an uppercase scheme (e.g., HTTPS://cnn.com)

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3190]
If you have a URL like [HTTPS://cnn.com](HTTPS://cnn.com) with an uppercase or mixedcase scheme, which is allowed for URLs, then when we receive these URLs via our SceneDelegate, we'll fail to handle them.

The issue lies in the case-sensitive checks inside `NavigationPath.init`

**Comment by jonathangarelick** [comment]
Successfully replicated. I'll have a go at this.
