### ISSUE TITLE
Update the Safari extension to remember the httpd~login cookie so users can still clear cookies without being signed out of Neeva

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3197]
We do something similar with the app, by storing the httpd~login cookie in the keychain. Perhaps we can even share this token between the app and the extension. Hmm...

**Comment by martha-neeva** [comment]
hey @darinwf and @evancrow - the member who reported this in the community has asked me for an update a couple times (including just now), so wanted to check in here. any update I can share with him?

**Comment by martha-neeva** [comment]
ok thanks @darinwf! I will let the member know

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxg7au
