### ISSUE TITLE
Tab Shows Up Twice Inside Tab Group

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3231]
Observed on latest testflight - 1.34.2(198)

(not shown in video: when you expand the group, the tab shows up twice)

https://user-images.githubusercontent.com/44557675/160327874-09b7839f-9bc5-4598-aeed-31738a4b3a31.MP4

will investigate how to repro

**Comment by darinwf** [comment]
@chassu FYI, any ideas here?

**Comment by chassu** [comment]
I saw it. I don't have any clues yet. :/

**Comment by darinwf** [comment]
So maybe this should not be a release blocker since we have no repro and we aren't seeing it anymore?
