### ISSUE TITLE
Tab re-opened from History > Recently Closed Tabs do not have sessionData associated with them

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3240]
Maybe this is intentional since it would imply needing to save this data to persistent storage. However, it may still be a good idea.

**Comment by darinwf** [comment]
@evancrow - I think you fixed this right?

**Comment by evancrow** [comment]
It works if you reopen a recently closed tab. The issue is that history is stored in `Sites`, a glorified URL basically which means we don't have the session data. I don't know if we would even want to store the session data in history since it would be really space-consuming.

**Comment by darinwf** [comment]
> It works if you reopen a recently closed tab. The issue is that history is stored in `Sites`, a glorified URL basically which means we don't have the session data. I don't know if we would even want to store the session data in history since it would be really space-consuming.

Yes, I did not describe this issue properly. I was only intending to refer to the "recently closed" section. I think your latest change fixed that to use the SavedTab system, right?

**Comment by evancrow** [comment]
@darinwf Think this can be closed now right?

**Comment by darinwf** [comment]
Yes, works now!
