### ISSUE TITLE
Sometimes tab thumbnail is broken

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#3251]
I found it not as easy to repro but I can catch it sometimes by quickly going into the switcher after a tab is created via long press. (create two tabs from long-pressing links from hub site, close one of the child tab, and don't scroll)

<img src="https://user-images.githubusercontent.com/87332917/160544105-f28fe217-90fd-443d-969b-c520daa9c1d9.PNG" width="400"/>

**Comment by darinwf** [comment]
I think you are right to blame the screenshot code you touched recently. That code is very hokey. There are so many opportunities for race conditions in that code. The timeouts, etc. Icky :-P
