### ISSUE TITLE
ZeroQuery No Longer Shows, Weird Animation When Searching

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3260]
Seeing this from main, but not TestFlight whenever I try to open ZeroQuery:

https://user-images.githubusercontent.com/37356984/160691085-0c3351a9-b7e9-41a7-a3e9-52e0e4068751.mp4

**Comment by buracules** [comment]
I will check now

**Comment by evancrow** [comment]
What I'm most confused about is why the ZeroQuery tests aren't failing

**Comment by buracules** [comment]
Ok i found the issue `backgroundColorOrGradient` without args causes this error.
