### ISSUE TITLE
When neeva.com redirects to /signin, we should display the native sign-in UI

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3267]
Currently, we just have the user see the web sign-in screen. We currently only intercept when starting a navigation to /signin, but the web client can issue a pushState (or equivalent) to /signin which WebKit would not see as starting a new navigation. We probably just need to extend our code in WKNavigationDelegate.didFinish.

**Comment by darinwf** [comment]
neeva.com may decide to redirect a user to `/signin` if it determines that the user hasn't used Neeva recently enough. Requiring re-auth like this is a security measure. Therefore, the app needs to be able to handle this case properly and show the native sign-in flow.

**Comment by darinwf** [comment]
This is pretty relevant for users who have been using the product for ~6 months or if they have been inactive for a period of time. Would be nice to make it lower friction to re-auth.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w33cmx
