### ISSUE TITLE
Bottom bar stuck in tab switcher mode while web page and URL bar is showing

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3272]
I saw this happen while using the browser on an iPhone 6s.

Video here:

https://user-images.githubusercontent.com/79867437/160880561-b966ccea-538e-48a6-b17e-bb7815b1d328.MOV

**Comment by darinwf** [comment]
It seems like somehow the bottom bar did not respond properly to `showContent` being set to true. Unfortunately, I didn't test if I was able to tap on any links or interact with the URL bar. I suspect I would have been able to do so since the page scrolled properly and the URL bar was hiding on scroll. The bottom bar was just in some broken state, so we should probably focus the investigation on how that could be the case.

**Comment by darinwf** [comment]
This is with latest TestFlight: 1.34.5.

And I'm able to repro by just switching tabs a bunch on the device...

**Comment by darinwf** [comment]
Tapping on a link in the page fixes it. Could be the navigation events help refresh the UI somehow. Tapping on the overflow button shows the menu, but dismissing that menu, then the bottom bar is shown properly.

**Comment by evancrow** [comment]
I've also been able to repro by rotating my device and then opening the tab switcher... might have something to do with the `ChromeModel`?

**Comment by darinwf** [comment]
Unfortunately the fix caused a bigger regression, so had to revert. Re-opening this bug.

**Comment by evancrow** [comment]
@darinwf Should we try using the original fix I had?

**Comment by darinwf** [comment]
I'm seeing this bug show up in the simulator now:

https://user-images.githubusercontent.com/79867437/162484515-9a19d20d-b4d2-49e5-953a-db179a9d931e.mp4

The repro is just tapping on the tab card. @evancrow - I think it is worth understanding this bug better. I can't explain why the extra `objectWillChange.send()` call would help so it is making me nervous about just shipping that fix. We should try to understand what is really going on so we can be confident about the fix.

**Comment by darinwf** [comment]
And now I cannot repro ... :-(

**Comment by evancrow** [comment]
Yeah this bug is quite elusive, have not seen it in a bit

**Comment by darinwf** [comment]
I went back to my iPhone 6s, and I can repro (sometimes).

**Comment by evancrow** [comment]
So maybe this is a performance-related bug?
