### ISSUE TITLE
Web page is clipped on the left hand side when in landscape mode

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3278]
This is with 1.34.8:

https://user-images.githubusercontent.com/79867437/160940591-a40dac6b-6cd7-48b4-bb20-78331a7cbb50.MP4

**Comment by darinwf** [comment]
@chassu was also seeing this. I wasn't able to repro until I tapped on a link on techmeme.com while it was in landscape mode and hit the back button.

**Comment by evancrow** [comment]
Might be an issue with the SimulatedBackSwipeController... investigating
