### ISSUE TITLE
Opening a space link while a space is open breaks spaces

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3311]
if a space is already open, and the app is told to open a spaces url, it doesn't do anything. Exit the spaces and try opening the link again makes the tab switcher spin indefinitely. See video.

This seems to only happen to spaces you are not already in.

https://user-images.githubusercontent.com/44557675/161861027-bec06d25-86c6-45c4-8fb1-7f1dec4c37c7.MP4

**Comment by jedireza** [comment]
I'm not able to reproduce this.

https://user-images.githubusercontent.com/979929/203160710-f44a9c98-7bdb-4739-98d1-eb49610a9f0f.MP4
