### ISSUE TITLE
Spaces experience bugs when signed out

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3319]
@darinwf and I chatted verbally about a couple of these. I found a new case (creating a space from results) and thought it best to open an issue with some visuals.

### Creating a new space from results:
https://user-images.githubusercontent.com/979929/162119026-4c723426-ea9f-4c4d-a2dc-31c559bbeec4.MP4

### Creating a new space from iOS spaces view:
https://user-images.githubusercontent.com/979929/162119054-cc74e283-798b-4a9b-91a5-39b99da111bc.MP4

### Save to spaces button when on a page:
![IMG_9BE77F2BE923-1](https://user-images.githubusercontent.com/979929/162119070-64fc625c-6a03-4013-8163-4957f0054bf0.jpeg)

**Comment by yozuysal** [comment]
:( . Are all of these when signed out?

**Comment by jedireza** [comment]
yep

**Comment by darinwf** [comment]
I did a quick test to try to repro but was unsuccessful. However, I think I have seen this kind of behavior before. Just am not seeing the repro steps yet.

**Comment by jedireza** [comment]
This is `1.34.12 (200.8)` from the app store. Maybe it's not just being signed out, but having _never_ been signed in. I'm not sure if that would make a difference or not yet.
