### ISSUE TITLE
Jumpstart Spaces from the community flag

### ISSUE THREAD

**Issue by yozuysal** [neevaco/neeva-ios#3321]
This is a flag that we are gonna build more things on later, but for this issue, we just need to make sure it works as intended. It suffered a bit of a bit rot while we are making other changes.

- Enable Spaces from the community flag
- This should create a new section inside the zero query titled "Spaces from the community". All the content here is read from SpaceStore.suggested. suggestedID.
- Currently when enabled, it says "Daily digest" which is a bug. we should not be adding the daily digest store to SpaceStore.suggested at all and addDailyDigest... should early return if suggestedID is non-nil

**Comment by yozuysal** [comment]
Looks like if you click through more than one Space in this screen back to back, the second click gets stuck with a progress bar. I think there has been a few issues around this lately. I think this is a similar issue as #3311 We are essentially waiting for a refresh() to happen and it somehow doesn't ever happen. (Maybe a race that prevents allDetails update?)

The codepath here is SpaceStore.openSpace(id:) 

Technically, if we fix #3320, none of this would happen, because we wouldnt have to wait for this final refresh and we can just show the Space we fetched. (So no progress bar would be needed here)

**Comment by buracules** [comment]
Is this still happening?
