### ISSUE TITLE
Bottom bar does not hide completely when scrolling on web page

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3331]
there's just a lil bit left :/ we see this on every webpage

https://user-images.githubusercontent.com/44557675/162372048-afd4e733-d7f9-454a-9aa4-a5a164e113fe.MP4

**Comment by darinwf** [comment]
Note, there might be some complications resolving this on pages that have fixed content bottom bars (e.g., twitter.com or linkedin.com). We should verify that those sites continue to work properly. Chrome seems to add back the safe area on those pages. I wonder how they are doing that...

**Comment by darinwf** [comment]
Looks like WKWebView takes care of the issue I was worried about... testing @evancrow's fix.
