### ISSUE TITLE
NeevaScope Drag Slow and Laggy

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3344]
When I try and drag up or down on the `NeevaScope` sheet, it's really slow and laggy:

https://user-images.githubusercontent.com/37356984/162669861-70b3334e-2a6c-4adc-8271-56f98fc73997.MOV

FYI @EdwardJTL

**Comment by EdwardJTL** [comment]
do you notice this with just this website or across multiple websites in the same session?
what device are you using?

**Comment by evancrow** [comment]
iPhone 13 pro, multiple fresh/old sessions. I think it only occurs when the News or Related items horizontal scroll field is visible.

**Comment by EdwardJTL** [comment]
okay horizontal scroll is a good place to start looking!

**Comment by darinwf** [comment]
I recall a recent PR that added code that would run when the NeevaScope content is scrolled. This:

<img width="913" alt="Screen Shot 2022-04-15 at 8 27 57 AM" src="https://user-images.githubusercontent.com/79867437/163589618-2ffcfb74-7190-41da-9087-2248b6223e0e.png">

In CheatsheetMenuView.swift. I'd be suspicious of such code leading to scrolling performance issues.

**Comment by EdwardJTL** [comment]
> I recall a recent PR that added code that would run when the NeevaScope content is scrolled. This:
> 
> <img alt="Screen Shot 2022-04-15 at 8 27 57 AM" width="913" src="https://user-images.githubusercontent.com/79867437/163589618-2ffcfb74-7190-41da-9087-2248b6223e0e.png">
> 
> In CheatsheetMenuView.swift. I'd be suspicious of such code leading to scrolling performance issues.

I don't think this is causing it. I checked that this closure only gets called when the support button is pressed, which toggles the variable observed by `onChange(of:)`.

**Comment by darinwf** [comment]
Got it. I've just seen in the past that a GeometryReader like this could create problems. Maybe it is still worth commenting it out to see if it has any impact on scrolling performance.
