### ISSUE TITLE
I can not connect to OpenSea

### ISSUE THREAD

**Issue by raspberry-hu** [neevaco/neeva-ios#3345]
I encountered a problem：

WC: incomming text deserialization to JSONRPC 2.0 requests error: The data couldn’t be read because it isn’t in the correct format.
WC: <== ping
WC: ==> pong client.respondToPingWithPong: true

**Comment by yozuysal** [comment]
Thanks for passing this along! Was this while trying to sign in? or connect? And was it consistently reproducible on opensea.io?

Any details about when you got the error would be appreciated.

**Comment by raspberry-hu** [comment]
Thank you for your reply, The problem happens when I log in.
