### ISSUE TITLE
Memory Leak From ContentBlocker When Opening App

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3353]
Occurs on debug/release upon opening the app (not a fresh install). Sometimes more leaks occur throughout using the app, but only 1-2.

Some screenshots from profiler
<img width="1502" alt="Screen Shot 2022-04-11 at 3 31 29 PM" src="https://user-images.githubusercontent.com/37356984/162844794-1eb5b227-c4fa-433d-b2d2-37c4cdda4509.png">
<img width="1502" alt="Screen Shot 2022-04-11 at 3 23 20 PM" src="https://user-images.githubusercontent.com/37356984/162844796-db6d6079-aabe-4f1e-92dd-e3d01f6dd051.png">

fyi @chung-lai

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w33mrv
