### ISSUE TITLE
Cookie is not set after user login

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3367]
With the change not to navigate to Neeva home (#3309) after login, the cookie does not get set properly. Our current logic is to set login cookie only after user navigates to a Neeva page for certain authentication flow (login with Google)

Reprod:

1. Reinstall app
2. Navigate to an url (e.g., yahoo.com)
3. Go to settings and login with Google
4. Go back to settings

Note the login is not set

cc @evancrow @darinwf

**Comment by chung-lai** [comment]
Given release is happening soon, planning to go back to previous UX and navigate to neeva.com upon login. And we can revisit this for next release.

**Comment by darinwf** [comment]
Should we close this bug and open a new bug about making it so that sign-in does not create a neeva home navigation? Or should we just re-purpose this bug?

**Comment by chung-lai** [comment]
We can file a new one to skip neeva home navigation by looking into how to set token for okta flow.

**Comment by chung-lai** [comment]
Filed #3614. Closing this now
