### ISSUE TITLE
FirstRunTests.testOpenNeevaSettings is flaky

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3372]
Related: https://app.circleci.com/pipelines/github/neevaco/neeva-ios/1938/workflows/e0a53e64-68bb-4d5c-9bfa-8bd6fd2f4184/jobs/9459

**Comment by jonathangarelick** [comment]
@yozuysal I think this and #3370 can be closed... it seems like I just had a one-off problem with CI.

**Comment by yozuysal** [comment]
sgtm. thank @jonathangarelick !
