### ISSUE TITLE
ios-log: scheme URLs should be ignored

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3388]
Reported by @EdwardJTL 

<img src="https://user-images.githubusercontent.com/41495718/163726791-cab266f3-2a13-45be-b705-fa13318a559d.png" height="500">

To reproduce:
-Go to movieguide.org
-Click around on some internal links, and this eventually should trigger

This functionality is used by Movie Guide's iOS app to record JavaScript console logs, but I don't think this is relevant to the user.
Related StackOverflow explanation: https://stackoverflow.com/a/6508343

**Comment by darinwf** [comment]
I see. So is the idea that we should maintain a list of URL schemes that we should just silently drop on the floor?

**Comment by evancrow** [comment]
So now it appears that we have the opposite issue as before (needing to maintain a list of URLs to not allow instead of allow). Curious if there's some sort of middle ground, such as a rule list that the scheme must follow.

**Comment by jonathangarelick** [comment]
@darinwf Yes.
@evancrow You're right, but this seems like an improvement. I think it is reasonable to assume most custom scheme queries are okay, there are just going to be some weird situations that need to be handled, like this.

**Comment by darinwf** [comment]
I imagine the set of URL schemes we'd want to block would be relatively low compared to the number we'd want to allow, and it makes sense to by default allow all. So I think our strategy of selectively blocking those that are problematic makes sense.

By the way, how do other browsers handle this case? (Always good to consider what users experience in other browsers when deciding on a policy for ours.)

**Comment by jonathangarelick** [comment]
Safari and Chrome iOS ignore it. Firefox iOS has the same problem that we do.

**Comment by darinwf** [comment]
Interesting... I don't see any hits for "ios-log" in the Chromium codebase: https://source.chromium.org/search?q=ios-log&sq=&ss=chromium

I wonder how / why it ignores this.

**Comment by jonathangarelick** [comment]
Did some digging and it looks like here is where Chrome handles external urls. Strangely, `IsAppSpecificURL` seems to always return false, so I must be missing something

https://source.chromium.org/chromium/chromium/src/+/main:ios/chrome/browser/app_launcher/app_launcher_tab_helper.mm;l=100?q=RequestToLaunchApp&ss=chromium%2Fchromium%2Fsrc:ios%2F

**Comment by darinwf** [comment]
I think `IsAppSpecificURL` can be overridden based on the embedder. The "web" layer of the iOS code is used by both Chrome and the iOS Google app, which is probably why there is this bit of indirection happening.

See: https://source.chromium.org/chromium/chromium/src/+/main:ios/chrome/browser/web/chrome_web_client.mm;l=220?q=IsAppSpecificURL&ss=chromium&start=11

**Comment by jonathangarelick** [comment]
Woot! Looks like I found it:
```
ExternalURLRequestStatus request_status =
      ExternalURLRequestStatus::kMainFrameRequestAllowed;
  // TODO([crbug.com/852489](https://crbug.com/852489)): Check if the source frame should also be
  // considered.
  if (!request_info.target_frame_is_main) {
    request_status = ExternalURLRequestStatus::kSubFrameRequestAllowed;
    // Don't allow navigations from iframe to apps if there is no user gesture
    // or the URL scheme is for Chrome app.
    if (!request_info.has_user_gesture || HasChromeAppScheme(request_url)) {
      request_status = ExternalURLRequestStatus::kSubFrameRequestBlocked;
    }
  }
```
https://source.chromium.org/chromium/chromium/src/+/main:ios/chrome/browser/app_launcher/app_launcher_tab_helper.mm;l=196?q=RequestToLaunchApp&ss=chromium%2Fchromium%2Fsrc:ios%2F

In the issue we are dealing with, the URL is loaded using an iframe
<img width="644" alt="Screen Shot 2022-04-17 at 10 48 38 AM" src="https://user-images.githubusercontent.com/41495718/164113871-97dd8dad-b704-4913-abfd-c21116781acf.png">
In Chrome's case, it blocks these requests per the policy above :)

**Comment by jonathangarelick** [comment]
@evancrow I can confirm this solves the issue, I'll let you/Darin decide how to proceed :-)
```
        if !(url.scheme?.contains("neeva") ?? true) {

            // Disallow custom app scheme requests via iframes
            if !(navigationAction.targetFrame?.isMainFrame ?? false) {
                decisionHandler(.cancel)
                return
            }
            
            showOverlay(forExternalUrl: url)
        }
```

**Comment by evancrow** [comment]
Thanks you @jonathangarelick! I'll modify my PR to check the frame instead.

**Comment by darinwf** [comment]
Awesome digging @jonathangarelick!

IIRC, Chrome restricts these to main frame so that ads and other embedded content cannot generate these kinds of links out to other apps. Since there can be dangers with users clicking on these links, it is better if we require them to come from the page the user is visiting. That way it helps cut down on certain forms of abuse. So this approach LGTM.

**Comment by jonathangarelick** [comment]
@evancrow Looks like your PR was merged. Is this good to close?
