### ISSUE TITLE
Regression: Tab restore does not work; just results in a blank tab

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3401]
@evancrow FYI

There seems to be no way to get the tab to reopen properly without force quitting and restarting the app. Also notice that you cannot even close one of these tabs, and when trying to edit the URL / query, it won't actually leave the suggest experience when hitting enter.

https://user-images.githubusercontent.com/79867437/164042986-1f2a97ff-a809-49e2-8708-ccf3a009b885.mp4

**Comment by darinwf** [comment]
The above video is from `main`, but I also see this bug with 1.37.3 (208)

**Comment by evancrow** [comment]
Must be Toast specific since using the history or open-new-tab recently closed menu works fine.

**Comment by darinwf** [comment]
> Must be Toast specific since using the history or open-new-tab recently closed menu works fine.

Hmm, no... I saw this bug when using History > Recently Closed Tabs. Then for this video I used the toast method. I think it is not dependent on which method is used to restore the tab.

**Comment by evancrow** [comment]
Okay, this must be related to #3240

**Comment by darinwf** [comment]
https://user-images.githubusercontent.com/79867437/164044413-bb3b5e4a-60cf-420b-b6b1-f171c73c1c51.mp4

**Comment by evancrow** [comment]
Also finding that I sometimes cannot interact with the Tab in the CardGrid, thinking this may not be a problem with only restoring the WebView.

**Comment by darinwf** [comment]
> Also finding that I sometimes cannot interact with the Tab in the CardGrid, thinking this may not be a problem with only restoring the WebView.

That sounds like it could be related to 468cd2b58dd84f59330d17f73a1a7020232371bc, which included my WIP prototype changes to the card transition logic.

**Comment by evancrow** [comment]
There's something wrong with the WebView, but we haven't made any changes to the restore code... could this be a WebKit bug somehow? I went back pretty far on main and I've been able to repro.

**Comment by darinwf** [comment]
Here's the callstack for the close button:
<img width="1066" alt="Screen Shot 2022-04-19 at 10 28 37 AM" src="https://user-images.githubusercontent.com/79867437/164061451-2ab431b0-1081-44dc-90b5-9d490ca69dbd.png">

I'm seeing that there is an early return from the `guard` statement on line 12 of `TabManager+CloseTabs.swift`. For some reason, the given `Tab` is not part of `TabManager.tabs`.

**Comment by darinwf** [comment]
More:
<img width="676" alt="Screen Shot 2022-04-19 at 10 32 09 AM" src="https://user-images.githubusercontent.com/79867437/164061933-15707b2f-6834-4aa1-b46a-81c5b5f68d4e.png">

Notice that the given `Tab` is a different object instance, but it has the same `url`. This may be a regression from when we made `TabCardDetails` hold an actual reference to `Tab` instead of only storing `Tab.tabUUID` values.

**Comment by evancrow** [comment]
Probably need to change the equatable function on Tab then to look at the UUID then right?

**Comment by darinwf** [comment]
> Probably need to change the equatable function on Tab then to look at the UUID then right?

We could go there, but I think instead we should figure out why there is a reference to an old `Tab` / `TabCardDetails`. That should not happen.

**Comment by darinwf** [comment]
Yeah, hmm.... in `Card`, I see that the referenced `details` does not exist as part of `allDetails` in `TabCardModel`:

<img width="628" alt="Screen Shot 2022-04-19 at 10 43 47 AM" src="https://user-images.githubusercontent.com/79867437/164063993-769479e2-9776-4110-ae12-eee5dae50049.png">

**Comment by darinwf** [comment]
Hmm... the plot thickens. I see new instances of `Card` getting created with the new `TabCardDetails` value. Maybe the problem has to do with how `TabCardDetails` implements `Equatable`.

**Comment by darinwf** [comment]
Yes! That's the issue here. Easy fix.

**Comment by chassu** [comment]
I found out that I couldn't repro this bug on a non-main branch, and so I checked out to this commit 27dbe3a6de044b247a07c5e64bfb12f1210c4229, which my branch is based off of. I found this crash after I restore a tab.

<img width="1002" alt="Screen Shot 2022-04-20 at 12 20 41 AM" src="https://user-images.githubusercontent.com/87332917/164173755-b41376fa-e972-4084-9980-6995e1e7bf31.png">

https://user-images.githubusercontent.com/87332917/164173773-73b84f71-e195-4970-a0bd-04d57db52646.mp4

If the issue is that we didn't override equatable implementation, they why aren't we seeing this issue before? and also...how does this resolve the issue?

**Comment by chassu** [comment]
yes, the fix resolves the crash. One more question: doesn't a cardDetail gets destroyed and removed from memory once we close it? I would imagine that that's not the case because of this issue.

**Comment by darinwf** [comment]
> yes, the fix resolves the crash. One more question: doesn't a cardDetail gets destroyed and removed from memory once we close it? I would imagine that that's not the case because of this issue.

SwiftUI was just holding onto an old Card instance, which was referencing the old TabCardDetails. I imagine once SwiftUI decides to really let go of an old Card that it will also finally destroy the old TabCardDetails.
