### ISSUE TITLE
Popover accessibility seems to be broken

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3405]
Found this while writing some tests. `forceTapElement` is required because popover buttons are not considered "hittable". Interestingly, overlay accessibility seems to work just fine.

**Comment by jedireza** [comment]
Closing this due to age and partially for clarity. If this is something we should track let's get some more details. "Seems to be broken" sounds like investigation is needed. Let's also try to point to some specific code if possible.
