### ISSUE TITLE
Cannot dismiss keyboard after clicking in the email field during sign-in

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3424]
This makes clicking on the other sign-in with Microsoft/Google buttons hard to get back to.

Side note: I also just noticed when I brought the keyboard up in a spaces comment box that I couldn't dismiss the keyboard there either. Maybe a broader issue all around to track.

<img src="https://user-images.githubusercontent.com/979929/164767967-88e3c9c6-1542-49fe-8331-a5053747a547.PNG" width="300" />

**Comment by evancrow** [comment]
@darinwf We can apply a global keyboard method that would dismiss when the user taps return. Does that sound reasonable?

**Comment by jedireza** [comment]
I remember seeing a keyboard dismiss key in other apps, but the only screenshots I can find for it are on the iPad.

The more intuitive solution (to me) would be taps outside of the input field, blur it, and the keyboard gets hidden. Right now tapping outside of the input field does nothing.

**Comment by jedireza** [comment]
These screens are gone.
