### ISSUE TITLE
Save to space context menu bug when a tab doesn't have a webview

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3429]
When a tab doesn't have a web view and you tap "Save to Spaces" from the context menu, nothing happens.

In the screen capture you can see that "Share" is disabled. That button is guarding against this, but also seems a little strange. We probably should be able to share too.

https://github.com/neevaco/neeva-ios/blob/4b50f20a1ae811508c3c5710d662b1c62071a939/Client/Frontend/Browser/Card/CardDetails.swift#L306-L316

![Kapture 2022-04-22 at 16 44 13](https://user-images.githubusercontent.com/979929/164817973-12b0db52-2cf1-43a6-8381-b3e4c578da49.gif)

**Comment by darinwf** [comment]
Yeah, this is probably another side-effect of `Tab.url` being nil for zombie tabs and can also be "fixed" by using `sessionData.currentUrl` or fixing `Tab.url` to be non-nil :)

There are perhaps a few more issues to consider as when adding a page to Spaces we have code that tries to extract metadata from the page, which wouldn't work in this case.
