### ISSUE TITLE
Selecting an image breaks Neeva

### ISSUE THREAD

**Issue by MatejaSrejic** [neevaco/neeva-ios#3431]
Upon selecting an attachment (in my case from the Photo Library) on any website the Neeva client turns all black. 

https://user-images.githubusercontent.com/75619038/164965446-89f8e7d0-d271-4635-beb1-7f4dbeaee046.MOV

**Comment by darinwf** [comment]
Thanks for the bug report. @evancrow - any thoughts on this one?

**Comment by evancrow** [comment]
Not right away... this is something WebKit handles and not something we implemented. Did a quick look in the logs though, and whenever the photo picker pops up, the `GeomFrame` is set to 10x10. Likely that controller is messing with something in SwiftUI.
