### ISSUE TITLE
Triple dot button in spaces does nothing

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3432]
Tapping this button doesn't do anything for me.

<img src="https://user-images.githubusercontent.com/979929/164991100-53da4728-db10-47de-b53d-b42a455bf563.jpeg" width="300" />

**Comment by darinwf** [comment]
Hmm... in this case, it should show a menu giving you the option to delete the space. That works for me w/ 1.37.5. What version are you testing? @yozuysal @buracules FYI

**Comment by jedireza** [comment]
`1.37.5 (208.2)`

**Comment by buracules** [comment]
Can you delete Saved For Later?

**Comment by jedireza** [comment]
> Can you delete Saved For Later?

Good call out. Probably not. If that's the case, I think we should disable or completely hide that button.
