### ISSUE TITLE
Restored tabs have a blank screenshot

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3437]
When writing out the tabs state, we do a pass to prune out any screenshots from the image cache that are no longer needed. We do that by looking only at TabManager.tabs. We should include the set of SavedTab objects that make up the undo tab close stack.

@evancrow FYI

**Comment by evancrow** [comment]
@darinwf Where does this filter occur in the code?

**Comment by darinwf** [comment]
In `TabManagerStore.prepareSavedTabs`
