### ISSUE TITLE
CardGrid Should Scroll After Closing Bottom Tab

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3439]
https://user-images.githubusercontent.com/37356984/165156754-3461036d-da64-47fb-80cc-64bc5018aaca.mp4

After closing the tab in the bottom row, the rest of the `CardGrid` should move down and the empty space should disappear.

FYI @chassu

**Comment by chassu** [comment]
hmmm, didn't see this on the app store build on my device, but saw it on my simulator on main... wondering if it's a regression

**Comment by chassu** [comment]
I'm not able to repro on my testing device. Do you see this on a real device?

**Comment by evancrow** [comment]
Both. I've found it easy to recreate when using a mix of tabs and tab groups and then having a single tab on the bottom.

**Comment by darinwf** [comment]
I saw this bug this morning too w/ latest TestFlight.

**Comment by chassu** [comment]
I've tried 
1. setting the maxWidth and maxHeight of the scroll view to the container size
2. add useEffect(deps: tabModel.allDetails){scrollToSelectedTab()} to CardScrollContainer. I think that broke some stuff and the scrollToSelectedTab didn't solve the issue.

Any ideas?

**Comment by evancrow** [comment]
My guess is the `scrollToSelectedTab` didn't work because the next tab to select is already partially visible, right? Maybe we need a method to scroll to the tab above the selected tab?

**Comment by evancrow** [comment]
@chassu I think this may be related to the `ArchivedTabsView` somehow. Works fine when that's enabled and the bug did not exist before that PR merged.

**Comment by chassu** [comment]
just want to point out that this bug already exists before the `ArchivedTabsView` PR was merged 😢

**Comment by chassu** [comment]
I think I've found a way to consistently repro it - make the bottom tab a zombie tab (can go to debug settings and turn tabs into zombie tabs), select the tab, go back to switcher, and then close the tab. I'm suspecting that the scrollView bug happens when webView of the bottom closed tab is still loading.

**Comment by evancrow** [comment]
Fixed by: #3514
