### ISSUE TITLE
No progress indicator when opening native spaces and the server is being slow to return the list of spaces

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3442]
Observed using 1.38.1. During this time, you just see a blank screen where the space grid should be, and there is no visible indication that it is working to load spaces. It can take multiples seconds sometimes for the server to respond (not ideal and is another issue), but when this happens it can feel like the product is broken. Users won't know that they should stay tuned and just wait for their spaces to appear.

**Comment by darinwf** [comment]
FYI @yozuysal @buracules

**Comment by yozuysal** [comment]
We can show a placeholder progress indicator. But I feel like we need a proper design for this empty state.

**Comment by evancrow** [comment]
^ I added a topic to design open hours about this

**Comment by evancrow** [comment]
We also have the loading space indicator we can show for now.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w34tkj
