### ISSUE TITLE
Tab cards appearing on top of spaces grid

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3463]
Observed using 1.38.3

Steps to repro:

1) Visit web page
2) Add to spaces
3) Open spaces from "add to spaces" flow
4) Hit the back button on the spaces detail view

FYI @yozuysal @buracules - any ideas on this one? This is on today's release branch

**Comment by darinwf** [comment]
<img src="https://user-images.githubusercontent.com/79867437/165606656-2397ecf9-9339-448a-a734-afb07ed9ee0e.jpg" width="300">

**Comment by darinwf** [comment]
Hmm, these phantom cards appear stuck on top of the view. Switching between normal tabs and spaces doesn't get rid of them. Unclear if the repro steps above are really what leads to the issue.

Oh, these are collapsed (single row) tab groups that are spilling over into the spaces part of the grid.

@evancrow FYI -- could this be due to the card grid hotfix somehow?  513122872e0f79a146467f194bb80b1779e2edc2

**Comment by darinwf** [comment]
If i scroll my tab groups so the right most card is visible and then switch to spaces, I no longer see the phantom tabs.

**Comment by evancrow** [comment]
I doub it has to do with my change since that affected the width of the `CardScrollContainer` instead of specific tabs and tab groups. Maybe @chassu's recent changes are related?

**Comment by chassu** [comment]
I don't think I have recent changes that touched on this. Question for @darinwf - when you scroll to the right most tab in your tab group and then switch to incognito mode, does it spill over?

**Comment by darinwf** [comment]
I can no longer repro :-(

**Comment by evancrow** [comment]
@darinwf Going to remove the release blocker label for now since since you can't repro

**Comment by evancrow** [comment]
@darinwf I'm seeing this on iPad now... taking a look
