### ISSUE TITLE
After enabling default browser, I still get a default browser promo card in the zero-query

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3470]
This is with 1.38.4. What I noticed is that the promo card was initially for account creation, and so I signed in. Then the promo card started showing for default browser even though I had clicked "Open Neeva Settings" on the first-run interstitial.

@chung-lai FYI

**Comment by darinwf** [comment]
<img src="https://user-images.githubusercontent.com/79867437/165812107-1c90ff50-0798-4c2a-9d1c-08db3da66315.jpg" width="300">

**Comment by chung-lai** [comment]
This was triggered by the frequency logic we added for default browser promo card which is to show every 3rd zero query impression. As a user who just dismissed the default browser interstitial, it may be too aggressive to show default browser promo too quick. We should start showing the default browser promo card two days after user dismissing the interstitial screen
