### ISSUE TITLE
Add automated test(s) for welcome screen

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3474]
@chung-lai suggested we add automated tests to prevent regressions and ensure we're showing the expected sign in/up screens.
 
Related to https://github.com/neevaco/neeva-ios/issues/3472, https://github.com/neevaco/neeva-ios/pull/3473

**Comment by chung-lai** [comment]
Thanks for filing this! Reserving this for Yasmin

**Comment by chung-lai** [comment]
Sample test: https://github.com/neevaco/neeva-ios/blob/main/XCUITests/FirstRunTests.swift
