### ISSUE TITLE
Disabling cookie cutter from the shield menu should be a per-site action

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3521]
What I notice on latest TestFlight is that disabling on one site from the shield appears to disable cookie cutter on other sites. But I also notice that it does not appear disabled in Settings, so I'm not quite sure what is broken.

This is with the "Cookie Cutter" feature flag enabled.

@evancrow FYI

**Comment by evancrow** [comment]
I don't think there is a disabled state in settings. @hwiatneeva should there be a toggle in settings to disable Cookie Cutter? There's one for tracking protection so maybe that should just be replaced by Cookie Cutter (since the tracking protection state controls the Cookie Cutter state)?
