### ISSUE TITLE
XYZClient Wallet Intro doesnt fit on iPad

### ISSUE THREAD

**Issue by buracules** [neevaco/neeva-ios#3527]
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-05-06 at 16 55 56](https://user-images.githubusercontent.com/15333612/167147549-a4992d44-ea50-486e-95ba-a5f3492a8e48.png) 

@yozuysal

**Comment by evancrow** [comment]
Stale now that XYZ is removed
