### ISSUE TITLE
Tracking Protection: Makes Images Shrink when toggled sometimes

### ISSUE THREAD

**Issue by Kokobe** [neevaco/neeva-ios#3535]
Toggling tracking protection seems to mess with the CSS or desktop view of the `Neeva Images` site. 

https://user-images.githubusercontent.com/20916043/167220820-1c903315-9ffb-41bf-9cfc-93d7fbeb5ca0.MP4

Steps to Reproduce:

1. Have 2 tabs open
2. Open 1 tab in Neeva Images
3. Turn Tracking Protection off via the Cookie Cutter UI
4. Switch to a different tab
5. Turn Tracking Protection on via the Cookie Cutter UI
6. Switch back to the Neeva Images tab
7. See the bug

**Comment by jedireza** [comment]
I tried this with the latest version of the app and didn't get stuck in the bugged state. The images SRP did refresh and I saw the content shrink and grow, but it finished in the expected layout. Closing for now.
