### ISSUE TITLE
Regression: Extra 9th suggested site

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3568]
Observed using 1.40.4 (219)

<img src="https://user-images.githubusercontent.com/79867437/167776089-a12b1427-2071-4a1a-bd49-75bd70ea4ad4.jpg" width="300">

There should be a max of 8 suggested sites (including Neeva Home).

@jedireza FYI guessing that recent changes to zero-query somehow caused this bug.

**Comment by yozuysal** [comment]
:(. I think this was actually me. ZeroQueryModel line 276.... This update must have slipped as a part of another change while I was testing something else.

**Comment by darinwf** [comment]
The PR indicates it was cherry picked into the release, but I still see this bug in the latest TestFlight 1.40.6 (219.2) from last night. @chassu FYI

**Comment by darinwf** [comment]
Yeah, I see it cherry picked here: https://github.com/neevaco/neeva-ios/commits/Build-219-release-branch

And the 219.2 tag includes it as well: https://github.com/neevaco/neeva-ios/commits/Build-219.2

Hmm... yet, I still see the bug
