### ISSUE TITLE
When adding to the length of suggested sites there is a delayed transition of suggested sites upon showing zero-query

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3569]
Notice what happens when showing the zero query after navigating to a new site:

https://user-images.githubusercontent.com/79867437/167776641-3561e9bc-c5d3-4892-9538-60b8c0ff08b0.mp4

Observed using 1.40.4 (219). This is a polish issue resulting from not pre-populating the suggested sites for new users.

@jedireza FYI

**Comment by yozuysal** [comment]
fwiw, I think this and some other animation issues we are seeing is caused by the fact that zero query still relies on an updateState called that is explicit. If we were to move the models here to be proper ObservableObjects, we would have things updating ahead of time and not see issues like this.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w355y1
