### ISSUE TITLE
Cookie Cutter Remind Me Later

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3584]
Need to set up the copy and time interval for the Cookie Cutter remind me later notification. Also need to handle the case of the user tapping multiple remind me later flows.

Moved from #3282

**Comment by jedireza** [comment]
Cookie Cutter is now Neeva Shield in the app. IIUC we don't have outstanding features to implement for it. Going to close this. If we still need to track this let me know.
