### ISSUE TITLE
Recommended spaces didn't load in zero query at first

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3587]
There may be a race condition. I saw this once or twice randomly in the simulator and thought it was a fluke. But with the latest test flight app, it kept happened after closing the app and opening again.

Once I tap in the url bar, they appeared. This makes me thing the data was fetched, but the view didn't get notified that there was a change.

## Screenshots or recordings

https://user-images.githubusercontent.com/979929/168161948-2e6cbc5c-69ce-41f6-a731-5535d703a6ed.mov

## Hardware and software

- Your device: iPhone 13 Pro Max
- OS version: 15.4.1
- App version: Neeva Browser 1.40.7 (219.3)

**Comment by yozuysal** [comment]
since we fetch the space that contains the recommended spaces, it will be gated by how fast that single graphQL call returns. We can always start with caching that one Space, but it might get a bit involved since we dont have a caching layer for Spaces on iOS

**Comment by jedireza** [comment]
Interestingly enough I just left the screen open and didn't touch it and after a while they did load. 🤔
