### ISSUE TITLE
Weird ZeroQuery Effect When Opening OverflowMenu iPad

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3592]
On first load with the new `ZeroQuery` UI, tapping the `OverflowMenu` causes a weird flicker, and after the first time, space favicons start to flicker.

## Screenshots or recordings

https://user-images.githubusercontent.com/37356984/168189281-4b982c39-aed4-47c8-946c-e2d333ea1253.mp4

FYI @jedireza

**Comment by jedireza** [comment]
Thanks for filing. We def have some work to get those transitions in check.

**Comment by jedireza** [comment]
Since this issue was created we've removed spaces from Zero Query and IIRC did some updates for those transitions.
