### ISSUE TITLE
Preview mode spaces screen is empty after dismissing overlay

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3611]
It may be a good idea to move the content of this overlay into the main view for preview mode users. Then we could replace the "continue" button with a "sign up" to use spaces CTA.

## Screenshots or recordings

| Overlay | Overlay dismissed |
| --- | --- |
| <img width="451" alt="image" src="https://user-images.githubusercontent.com/979929/168877587-5832c041-b13f-4ce3-bb1c-4c950e96f269.png"> | <img width="564" alt="image" src="https://user-images.githubusercontent.com/979929/168877605-98bf5326-8f0b-4bf5-9a79-69744e44e52d.png"> |

**Comment by hwiatneeva** [comment]
@hwiatneeva to design

**Comment by hwiatneeva** [comment]
cc: @yozuysal for attention
