### ISSUE TITLE
Reports of slowness

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3613]
From @michellew7:
> hey y’all, im on the most recent build 1.41.1 and have been experiencing slowness with the app :disappointed: just wanted to report in case it’s anything new to investigate. app was almost unusable yesterday as I had to force quit it while I was browsing on a site. I have 50ish tabs open

From @seth737:
> I've also been noticing a lot of slowness, particularly around delays between tapping a suggestion from search suggest and the view changing to the tab to load the page

**Comment by darinwf** [comment]
I think the issue @seth737 reports is a different issue. He had 248 tabs open, and opening a new tab would need to call `updateRows` which is currently pretty expensive and scales poorly with the number of tabs already opened. @chassu FYI

**Comment by chassu** [comment]
I constantly test the performance when adding/removing a tab when there are ~500 tabs. For some reason, it doesn't feel that slow on my device. (go to debug settings and there's a button that lets you create 500 tabs)

**Comment by evancrow** [comment]
Think it's safe to call this resolved!
