### ISSUE TITLE
Account Settings Sign-in Loop

### ISSUE THREAD

**Issue by yasminyin96** [neevaco/neeva-ios#3615]
## Expected behavior

Try to get QR Code in Account Settings, but got stuck in the sign-in page. Same as the website.

## Actual behavior

Show QR Code instead of sign-in page.

## Steps to reproduce the problem

1. Go to Settings -> Account Settings (already signed in in the IOS app)
2. (QR Code Sign-in) Start
3. Verify Password

## Screenshots or recordings

https://user-images.githubusercontent.com/104786010/168913951-2c79e2a0-54d1-4593-92ff-0cbbb008bf33.MP4

## Hardware and software

- Your device: iPhone 12 Pro
- OS version: 15.4.1
- App version: Neeva Browser 1.50.3

**Comment by yasminyin96** [comment]
@hwiatneeva 
Thank you~

**Comment by chung-lai** [comment]
Looks like this sign in loop issue is still happening. @seth737, do you know who can help looking into this on web?

**Comment by jedireza** [comment]
I'm not able to reproduce.
