### ISSUE TITLE
Share to menu; Open in Neeva collides with XYZ

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3618]
If you have both Neeva and XYZ installed, and use the share to menu and choose "Open in Neeva", xyz can take over.

## Screenshots or recordings

https://user-images.githubusercontent.com/979929/168947746-e9c6a68a-6547-44cd-b8f6-16e09351373b.mp4

**Comment by evancrow** [comment]
Stale now that XYZ is removed
