### ISSUE TITLE
Opening tab with expired "Sign In via QR Code" link invalidates current account

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3623]
To sign in via QR code, we open a specific link. This tab stays open after successful log in. However, this link will expire.

## Expected behavior

Opening this link should not sign out the current user.

## Actual behavior

It signs out the current user and redirects to the welcome webpage.

## Steps to reproduce the problem

1. Open a qr code sign in link
2. Switch to a different tab
3. wait for it to expire
4. re-open the app and go to that tab

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3599v
