### ISSUE TITLE
Long press menu on back / forward buttons does not show up in Incognito mode

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3631]
## Expected behavior

Long press on back / forward button in an incognito tab and expect to see a menu of all of the navigations within that tab.

## Actual behavior

This menu does not appear.

## Steps to reproduce the problem

1. Open incognito tab
2. Navigate to some page
3. Click a link
4. Long press on back button
5. No menu is shown

## Hardware and software

- Your device: iPhone 12
- OS version: 15.4.1
- App version: Neeva Browser 1.41.4

**Comment by evancrow** [comment]
It appears that the list isn't showing in normal mode either...

**Comment by evancrow** [comment]
Appears to be a problem with SQL inside `BackForwardListModel`, which hasn't been touched. As well as the fact that we were passing an empty array of URLs to the SQL since we never set `listItems` 🤦‍♂️.
