### ISSUE TITLE
Neeva Scope header seems incorrect on nytimes.com pages

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3633]
## Expected behavior

Expecting to see the entire nytimes logo or nothing at all.

## Actual behavior

The header with the right aligned "Yo" logo doesn't look right.

## Steps to reproduce the problem

1. Go to a news article on nytimes.com
2. Open Neeva Scope

## Screenshots or recordings

<img src="https://user-images.githubusercontent.com/79867437/169217782-f6aeaad5-655e-4759-8a9c-6ae8443f2ffa.jpg" width="300">

## Hardware and software

- Your device: iPhone 12
- OS version: 15.4.1
- App version: Neeva Browser 1.41.1

FYI @EdwardJTL

**Comment by EdwardJTL** [comment]
For reference, the entity card on SRP

![image](https://user-images.githubusercontent.com/44557675/170561534-5cfe7ace-a441-4476-88b1-cabc11d123bc.png)

**Comment by EdwardJTL** [comment]
will discuss at next design meeting

**Comment by EdwardJTL** [comment]
i'd like that asset more probably, but i think that change has to come from backend. 
i can look into not showing the the image if the aspect ratio is beyond a certain limit if we want to do that as a temporary solution?

**Comment by Ria-yu** [comment]
> 

sgtm
