### ISSUE TITLE
Design a more reasonable error for when `suggestd` isn't feeling well

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3645]
Currently if `suggestd` is borked, we take over the screen. We could probably come up with a more graceful experience. Even just showing one suggest line as an error might be better than taking over the whole screen.

## Screenshots or recordings

<img width="350" src="https://user-images.githubusercontent.com/979929/169617313-3e1badb8-82d1-4e77-bfc4-4c7351d2810a.gif" />

<img width="350" src="https://user-images.githubusercontent.com/979929/169617118-d2bc6d50-068f-45c4-a433-1d9d5c503ae1.png" />

**Comment by EdwardJTL** [comment]
might still be good to send a log when that happens. Right now this goes to user-feedback which is very visible

**Comment by chung-lai** [comment]
We should have some server-side monitoring for this so we can get alert quicker instead of waiting for user feebback.

fyi, @kelvinso, @yifanj0

**Comment by yozuysal** [comment]
when suggestd fails, we should just show history suggestions and silently log? That way the user may still keep going with their task?

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w359g4
