### ISSUE TITLE
Turn off cookie cutter popup does not work for existing tabs

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3671]
See attached screen capture.

https://user-images.githubusercontent.com/87332578/169922718-d9ca3c7b-7767-468c-aa9a-858b423be9d2.mov

## Steps to reproduce the problem

1. Download app
2. Go to settings and turn off cookie cutter
3. Open cnn.com

We should not see the cookie popup declined after turning off cookie cutter. Thought it could be existing tab was injected with the cookie cutter javascript but opening a new page should inject the script based on the cookie cutter setting? cc @evancrow

**Comment by evancrow** [comment]
The script is always injected, but we pass a preference if the engine should run

**Comment by evancrow** [comment]
@chung-lai I can't recreate this, it works as expected for me :(

**Comment by evancrow** [comment]
Do you possibly need to rebuild the script since I last updated it (`yarn install && yarn build`)?
