### ISSUE TITLE
testTriggerSignInModalAndClose failure

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3696]
Test `testTriggerSignInModalAndClose` seem to fail. There are few things going on:

* For our experiment control arm, we show "Set as Default Browser" promo card. We may want to set that to be the experiment arm or disable the default browser promo by setting `Defaults`'s `didDismissDefaultBrowserCard`
* We may consider moving the test into a new suite and set the `Defaults` properly so we can make sure we are testing the promo card logic properly

fyi @jonathangarelick

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w359mz
