### ISSUE TITLE
Purple color when sending app to background from incognito grid

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3719]
When sending the app to the background on the incognito grid, there is a purple color that feels out of place. I think we're covering up the app to be discrete in this case. But we could use a better color and/or treatment.

## Screenshots or recordings

https://user-images.githubusercontent.com/979929/170807177-5699e1fe-f93c-44cc-aa36-936f57011006.MP4

**Comment by evancrow** [comment]
Be a good topic for design sync

**Comment by jedireza** [comment]
I'm not sure we need to go that far as as a first step. The purple feels out of place. A dark grey or black would do the trick and we could move on and spend less human cycles on a little thing.

**Comment by Ria-yu** [comment]
In general it'd be great if we could try to always use colors from neeva color library, in this case the brand color "Charcoal" - Hex #191919, RGB (25, 25, 25) - could work.
