### ISSUE TITLE
New image context menu long press delay + visuals

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3721]
I noticed on the latest test flight build the long press feels very long, I almost gave up on it thinking it wasn't going to work. Also the visuals I experienced were different than the screenshots. The URL row is expanded for me and the menu looks very small and hard to tap.

https://user-images.githubusercontent.com/979929/170832225-926a3f20-a4a7-4d92-a885-3522315f3bc6.MP4

Related to: https://github.com/neevaco/neeva-ios/pull/3709

**Comment by buracules** [comment]
I think i messed up with my last commit can you also send me this websites adress?

**Comment by jedireza** [comment]
https://www.pcmag.com/picks/best-iphone-apps

**Comment by buracules** [comment]
Yes i am messed up while refactoring constraints. I will revert those changes for now.

**Comment by buracules** [comment]
I should've tested with landscape images also after changes i just tested with portrait images

**Comment by buracules** [comment]
Also about ` long press feels very long` i get the callback when you stop long pressing maybe that's the issua?
