### ISSUE TITLE
Performance; slowness with 300+ tabs

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3730]
User report via Slack:

> I've ended up having a very very very large number of tabs. Now it takes 6 seconds to even close a tab.
> Finally gave up and closed all tabs. 301!
> 301 tabs

## Hardware and software

- Your device: unknown
- OS version: 15.5
- App version: Neeva Browser  1.43.1 (227)

**Comment by darinwf** [comment]
I'm also seeing this. I think it means we need to do some combination of 1) optimize buildRows, 2) minimize calls to buildRows, 3) explore a way to support removing a tab without calling buildRows, 4) enable tab archiving and take advantage of it to greatly speed up buildRows.

@chassu FYI

**Comment by darinwf** [comment]
I used the option to add 500 tabs, and then removed a single tab. What I observe:

1- buildRows is called two times
2- under the simulator, seeing it cost about 12-17 milliseconds each call
3- on an iphone 12, seeing it cost about 26-33 milliseconds each call
4- there seems to be a significant delay before buildRows gets called

Point 4 makes me think there is more going on here than just buildRows being slow. And 26-33 msec x 2 does not explain the sluggishness we are seeing.

**Comment by darinwf** [comment]
Yeah... looking at TabManager.removeTabs, with 500 tabs on an iPhone 12:

I see that removeTabs is taking about 500 msec. buildRows is just a fraction of that...

**Comment by evancrow** [comment]
The whole app is slow, not just when closing tabs. So the issue probably isn't with any of the close functions but something that affects everything.

**Comment by darinwf** [comment]
> The whole app is slow, not just when closing tabs. So the issue probably isn't with any of the close functions but something that affects everything.

I agree there may be multiple issues, but closing a single tab when you have 100s of tabs is one issue that really stands out and should be easy to debug.

I'm seeing that TabCardModel.onDataUpdated is what's slow, and like I said, it isn't all explained by buildRows. That's interesting since the part that isn't buildRows is simpler.

**Comment by evancrow** [comment]
I ran the profiler and it looks like a SwiftUI updater that calls `FaviconView` is using a lot of CPU (and almost a second of run time).

**Comment by evancrow** [comment]
Think that might be a good place to start. I will try removing `FaviconView` to see if that fixes the issue to confirm if that is the problem.

:)

<img width="497" alt="Screen Shot 2022-05-31 at 10 59 17 AM" src="https://user-images.githubusercontent.com/37356984/171253945-f0416fd9-b1a5-477f-8a78-a929f6b965e2.png">

**Comment by darinwf** [comment]
I'm seeing good speedup from removing `allDetailsWithExclusionList` and `representativeTabs` calculations. Will post a PR for that. Think these are mutually exclusive optimizations, so lets see where we net out with these efforts!

**Comment by chung-lai** [comment]
@darinwf, i assume this is different from https://github.com/neevaco/neeva-ios/issues/3745?

**Comment by darinwf** [comment]
@chung-lai - Yes, I think so since the users reporting this probably didn't have the timeline view enabled.

**Comment by evancrow** [comment]
@darinwf Can we close this? Think we resolved this.

**Comment by darinwf** [comment]
Yes, plus the time-line switcher landed which should help a lot.
