### ISSUE TITLE
Weird jump after tab animation 

### ISSUE THREAD

**Issue by yasminyin96** [neevaco/neeva-ios#3734]
## Expected behavior

No weird jump.

## Actual behavior

Weird jump after tab animation 

## Steps to reproduce the problem

1. Open tab
2. Click Show Tabs button

## Screenshots or recordings
Incognito Mode

https://user-images.githubusercontent.com/104786010/171262594-784e4285-fb85-4a77-b84b-52991d04b7ff.mov

Normal Tabs

https://user-images.githubusercontent.com/37356984/171258746-fafe2b27-fc1e-4919-935e-6279122285f1.mp4

https://user-images.githubusercontent.com/104786010/171262661-790c11e6-52d8-4298-8499-e8b59dc40e30.mov

**Comment by darinwf** [comment]
Looks like this bug can be closed now?

Thanks for fixing this issue! I saw it too and was about to file a bug for it :-)
