### ISSUE TITLE
Add frame and instruction to QR Code Scanner

### ISSUE THREAD

**Issue by yasminyin96** [neevaco/neeva-ios#3749]
## Expected behavior

When user open the QR Code Scanner, it should show the square frame and instruction to help user scan the code, for example, move closer etc.

### Before:

  1. Camera permission request 
       - Allow: go to scanner
       - Not allow: dismiss sign in page and show toast "please allow to use camera and try again"
     
  2. Add square frame
       <img width=100, src="https://user-images.githubusercontent.com/104786010/171504079-31a6080c-9599-4427-9b9b-a9436abcf9be.jpeg">

### During:
  1. Code not detected
       - Invalid QR code (qr code is not from neeva): dismiss sign in page and show toast "invalid qr code"
       - Code not detected: "try again" instruction label at the bottom of scanner
  
  2. Partial detected
       - "move closer" or " move further" instruction label at the bottom of scanner
   
  3. Correctly detected
       -  go to home page and show toast "sign in successfully"
    

### After:
   1. Sign in success: vibrate, go to home page and show toast "sign in successfully"
  
   2. Sign in failure: "refresh qr code and try again" instruction label at the bottom of scanner

**Comment by hwiatneeva** [comment]
We need an enumeration of possible paths + instructions + visual indications before / during / after... please identify those and document/add visuals what to do with each: 
- Before:  going from the qr code button in the UI to the scanner ui
- During:  1) code not detected, 2) partial detected (get closer or further), 3) correctly detected
- After:  1) sign in success, 2) sign in failure with instruction to get unstuck

Thanks!

**Comment by yasminyin96** [comment]
> We need an enumeration of possible paths + instructions + visual indications before / during / after... please identify those and document/add visuals what to do with each:
> 
> * Before:  going from the qr code button in the UI to the scanner ui
> * During:  1) code not detected, 2) partial detected (get closer or further), 3) correctly detected
> * After:  1) sign in success, 2) sign in failure with instruction to get unstuck
> 
> Thanks!

Got it

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w35a1g
