### ISSUE TITLE
Webview keeps reloading on a website

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#3756]
On main, I saw the webview keeps reloading on this site: https://www.cnbc.com/2022/05/23/ebay-enters-nft-business-with-assist-from-hockey-icon-wayne-gretzky-.html and the app gets slower as it keeps reloading.

I don't think this is archived tabs related.

https://user-images.githubusercontent.com/87332917/171519733-bd8679f2-63ef-43f3-bee0-6f547c5e1c7b.mp4

**Comment by chung-lai** [comment]
This could be cookie cutter related. It happens when I enable the feature in `1.41.4`. cc @evancrow . It stops reloading when I turn off cookie cutter.

**Comment by evancrow** [comment]
@jlynch630 Any thoughts?

**Comment by evancrow** [comment]
Think I remember something about `flagSite`?
