### ISSUE TITLE
disappearing/fallback favicon bug

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#3773]
Two favicon bugs that seem to be regressions, one of which no longer exists as a benefit of #3593 

1. disappearing favicon

<img src="https://user-images.githubusercontent.com/87332917/171964640-40843544-0272-4fb0-b070-d8a5eceb8003.png" width="400"/>

Ways to repro: create (more than 2) tabs -> kill and relaunch the app. The favicons of non selected tabs used to be missing.

#3593 now make sure the values of `savedTab.title` and `savedTab.url` is copied over to `tab.title` and `tab.url` in `SavedTab+ConfigureExtension.swift`. Not grabbing the values were why the favicon was missing. (However, some old version of the app didn't have this problem, if someone knows what PR caused this regression, it would be great if you can link it here).

2. lots of favicons are using fallback values

<img src="https://user-images.githubusercontent.com/87332917/171964931-5763b34f-d9bb-48fb-b32c-09aa36bc6ae4.png" width="400"/>

I see a lots of favicon using the fallback icon now... probably also a regression some time ago. This issue still exists on main. Might need an investigation on what PR caused the regression.

**Comment by chassu** [comment]
@evancrow @darinwf

**Comment by jedireza** [comment]
I'm not seeing this. Might've been fixed since this issue was created.
