### ISSUE TITLE
Drag-n-drop does not work when time based tab switcher is enabled / archived tabs view is enabled

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3785]
TestFlight 1.44.1 w/ "Enable time based tab switcher" and "Enable archivedTabsView in switcher" options enabled.

Unable to drag-n-drop reorder tabs:
https://user-images.githubusercontent.com/79867437/172213464-1762d88f-d473-4639-968f-2dcd88e1bd24.MP4

FYI @chassu

**Comment by evancrow** [comment]
@chassu Can this be closed?
