### ISSUE TITLE
Regression: Video (sound) keeps playing after tab is closed

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3788]
## Expected behavior

When a tab with video playback is closed, the audio should immediately stop.

## Actual behavior

The audio continues playing even after the tab has been closed. You have to force quit the app to stop the sound.

## Steps to reproduce the problem

1. Open up youtube (or perhaps some other video site?) and select a video
2. Close the tab 

## Hardware and software

- Your device: iPhone 12
- OS version: 15.5 
- App version: Neeva Browser 1.44.1

@EdwardJTL - maybe this is related to the memory leak issue you were referring to on slack?

**Comment by evancrow** [comment]
I can't seem to recreate this, do you have any flags enabled?

**Comment by darinwf** [comment]
I cannot repro either :-(

I'm pretty sure I experienced it once though. Ugh.
