### ISSUE TITLE
Regression: Space filter requires double tap

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3805]
A bit hard to repro, but I experienced this on both `main` and the app store release.

https://user-images.githubusercontent.com/41495718/172495438-78689cd1-cbd9-4478-aac2-b3291b9dc763.mp4

cc @evancrow

**Comment by evancrow** [comment]
What happened to my fix with the `DispatchQueue`? Or are you trying to replace the `GroupedButton`s with an actual `Button`?
