### ISSUE TITLE
Visual balance of some history suggestions is off

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3807]
I first noticed this in an incognito tab, then found it in the history section of a regular tab. Feels like something is missing.

## Screenshots or recordings

![history-balance](https://user-images.githubusercontent.com/979929/172519608-2ef1183f-a321-4eb3-98e3-de5827fb0817.png)

**Comment by jedireza** [comment]
When I tap this result I'm taken to the Neeva SRP for `react hooks` so this much be some kind of history entry for that search. Maybe the `<title>` tags of those pages aren't being picked up?

**Comment by yozuysal** [comment]
I think this is more an error on our DB side. We store the title of the page as empty, or somehow the titles get lost as we are pulling the Site from the DB. I have noticed this on and off inside autocomplete as well.

**Comment by darinwf** [comment]
Are you sure this is a server generated redirect? I thought neeva.com used client-side redirects (possibly via history.replaceState or equivalent in this case). Would be good to understand precisely what is going on before we try to build a solution.

**Comment by darinwf** [comment]
Actually, I don't... I wish I knew of such a tool. When I was doing a lot of engine development, I would just use my own lighttpd instance, but mobile adds another challenge.

One idea might be to just try constructing some XCUITest scenarios using the GCDWebServer instance that we have in the app. Many of our tests use it for loading test resources. It may be flexible enough to cover this case.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w35aph
