### ISSUE TITLE
card transition animation glitches on long taps

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#3813]
https://user-images.githubusercontent.com/87332917/172719421-c8159703-3a69-4de9-ac04-115c9df73c8d.mp4

I was trying to fix this yesterday. My theory is that there's a small window when the gesture is considered as a tap but also long enough to trigger the context menu. If the user releases the finger before the context menu is fully displayed, then there will be an overlay card on top of the transition card.

I realized it's actually pretty easy to repro.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w35bd7
