### ISSUE TITLE
Repeated search with neeva shortcut launches result in erroneous state

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3817]
## Expected behavior

When search term not provided: open new lazy tab with empty field
When search term is provided: open a new tab and perform search

## Actual behavior

The second launch just doesnt work in all kinds of ways. Need triaging.

## Steps to reproduce the problem

1. Define a shortcut with `Search Neeva for ___` shortcut
2. launch it directly or via siri
3. do it again

## Hardware and software

- Your device: 
- OS version: 
- App version: Neeva Browser 1.44.6(233.3) testflight

**Comment by jedireza** [comment]
I wasn't able to reproduce the shortcut bug. I did try using Siri and saying "search neeva for _______" will open the Neeva app, but doesn't have any input, doesn't open a tab.

I filed a ClickUp for the Siri part 🔒 https://app.clickup.com/t/3w3atyf

https://user-images.githubusercontent.com/979929/203426095-094ffb03-935b-4d82-b65d-50b10c376f61.MP4
