### ISSUE TITLE
Scrolling is Sticky

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3833]
I've noticed on a lot of sites that scrolling is sticky and it often pauses or gets stuck for half a second. Makes scrolling very annoying.

**Comment by darinwf** [comment]
I wonder if this could be related to the ad blocker. What happens if you
disable it?

-Darin

**Comment by evancrow** [comment]
Still happens with ad-blocker and Cookie Cutter disabled. While I can recreate it on most websites, its most prevent on ones where data has to load while scrolling: Instagram, Reddit, etc. Does not occur with Safari though so it is something we're doing.
