### ISSUE TITLE
Selecting old tabs sometimes doesn't scroll to entire card in time-based switcher

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#3837]
https://user-images.githubusercontent.com/87332917/173411926-02323950-733b-4c9e-852d-6f0707f3dd40.MP4

**Comment by chassu** [comment]
to clarify: the scrollTo should only happen until the grid is shown, not when it's hidden (when the tab card is animating to full screen).

**Comment by evancrow** [comment]
Fixed by the new design, and improved `scrollTo` logic
