### ISSUE TITLE
Performance: Add to Space sheet loads very slowly (~3min)

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3853]
Report from our community manager. Has appx. <100 Spaces. 

Has 50 tabs open.

https://user-images.githubusercontent.com/41495718/173675068-1e84607a-9ed2-4a8c-a016-0ebc91d00b17.mov

cc @martha-neeva

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3azbx
