### ISSUE TITLE
Old tabs before new tab switcher is enabled will be archived without URL and favicon

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#3854]
Due to the fact that we didn't properly store and read `tab.url` and `tab.title` until #3593. For tabs that the user hasn't interacted with since before the PR is merged, those tabs will be archived without URL and favicon. I feel like there will be plenty of tabs like this, until all the tabs in the tab switcher are created after that PR. Should we fix the UI for those tabs? and what would be a good way?

Without interacting with the tabs:

![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-06-13 at 15 44 00](https://user-images.githubusercontent.com/87332917/173671595-6e7ab319-138b-47b9-970c-7d49b593f787.png)

After bringing (some of) them back from archives and getting archived again:

![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-06-13 at 15 45 47](https://user-images.githubusercontent.com/87332917/173671613-28a5b44e-c9aa-4079-b516-f7591c6ba892.png)

**Comment by chassu** [comment]
@darinwf curious what you think about this

**Comment by darinwf** [comment]
It would be nice to fix this, but it sounds from your description that there is no way without loading the tabs again right? I don't think we want to load them again.

**Comment by chassu** [comment]
yeah, I believe those tabs have to be reloaded to persist the favicon and url :/ and it's hard to come up with a fallback option if it DNE
