### ISSUE TITLE
Failed to navigate to cookie cutter setting

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3858]
On latest testflight, tapping on cookie cutter setting in the shield menu does not land on the cookie cutter setting. It opens up the general settings, once you try to scroll then it navigates to the cookie cutter setting.

Starts happening in 1.45.2

**Comment by evancrow** [comment]
I fixed this issue once before, added `ScrollTo` code in SettingsView but it sounds like that must be broken.

**Comment by chung-lai** [comment]
Right, i think scrolling to the section header is not sufficient. We should scroll to a specific setting. Going to post a PR.
