### ISSUE TITLE
Error on opening neeva community space on preview zero query

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3864]
On latest Testflight, tapping on a neeva community space gives an error.

![IMG_7467](https://user-images.githubusercontent.com/87332578/173747155-33326f71-bbe0-4533-9830-a2aa6d454786.jpeg)

**Comment by chung-lai** [comment]
Could it be related to this [PR](https://github.com/neevaco/neeva-ios/pull/3832)?

**Comment by chung-lai** [comment]
fyi @buracules @yozuysal

**Comment by buracules** [comment]
> Could it be related to this [PR](https://github.com/neevaco/neeva-ios/pull/3832)?

Probably yes. I will check it just to be sure.
