### ISSUE TITLE
Regression: browser becomes super slow after navigating a dozen or so links on a page

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3866]
## Expected behavior

Browser performance shouldn't get slower due to past browsing.

## Actual behavior

Browser becomes super slow after navigating a dozen or so links on a page

## Steps to reproduce the problem

1. Go to https://news.ycombinator.com/
2. Click on the first link, let the page load, then click back.
3. Click on the second link, let the page load, then click back.
4. Repeat about a dozen times.
5. Notice that scrolling hacker news is now getting sluggish.

## Hardware and software

- Your device: iPhone 12
- OS version: iOS 15.5
- App version: Neeva Browser 1.45.3 (236.1)

**Comment by darinwf** [comment]
When the browser gets slow like this, and I then kill it and restart. Upon restart, I notice that it looks like the history DB may have lost some data about links that I previously clicked on. Links on hacker news that I clicked on are marked unvisited. I wonder if that could be related somehow. Maybe the issue is related to the history system getting bogged down somehow.

**Comment by chung-lai** [comment]
I downgraded to 1.44.6 and felt the sluggish was there.

**Comment by darinwf** [comment]
@chassu said he downgraded to a much earlier build and still saw this problem. So it is not a release blocker.

**Comment by chung-lai** [comment]
But also wonder if the side effect of app being slow has anything to do with your larger history DB. Was it from a new install or it's your personal device?

**Comment by darinwf** [comment]
Personal device where I have yeah, been accumulating a large history DB :)

**Comment by chassu** [comment]
After some investigation, I believe we've always had this issue, and it's caused by memory leak in `subscribe` that the `BrowserViewController` implements:

```
let estimatedProgressPub = webView.publisher(for: \.estimatedProgress, options: .new)
        let isLoadingPub = webView.publisher(for: \.isLoading, options: .new)
        estimatedProgressPub.combineLatest(isLoadingPub)
            .forEach(updateGestureHandler)
            .filter { _ in tab === tabManager.selectedTab }
            .sink { [weak self] (estimatedProgress, isLoading) in
                // When done loading, we want to set progress to 1 so that we allow the progress
                // complete animation to happen. But we want to avoid showing incomplete progress
                // when no longer loading (as may happen when a page load is interrupted).
                if let url = webView.url, !InternalURL.isValid(url: url) {
                    if isLoading {
                        self?.chromeModel.estimatedProgress = estimatedProgress
                    } else if estimatedProgress == 1 && self?.chromeModel.estimatedProgress != 1 {
                        self?.chromeModel.estimatedProgress = 1

                        DispatchQueue.main.asyncAfter(deadline: .now() + 0.4) { [self] in
                            if self?.chromeModel.estimatedProgress == 1 {
                                self?.chromeModel.estimatedProgress = nil
                            }
                        }
                    } else {
                        self?.chromeModel.estimatedProgress = nil
                    }
                } else {
                    self?.chromeModel.estimatedProgress = nil
                }
            }
            .store(in: &tab.webViewSubscriptions)

        webView.publisher(for: \.url, options: .new)
            .forEach(updateGestureHandler)
            // Special case for "about:blank" popups, if the webView.url is nil, keep the tab url as "about:blank"
            .filter { tab.url != .aboutBlank || $0 != nil }
            // To prevent spoofing, only change the URL immediately if the new URL is on
            // the same origin as the current URL. Otherwise, do nothing and wait for
            // didCommitNavigation to confirm the page load.
            .filter { tab.url?.origin == $0?.origin }
            .sink { [weak self] url in
                tab.setURL(url)

                if tab === tabManager.selectedTab && !tab.restoring {
                    self?.updateUIForReaderHomeStateForTab(tab)
                }

                // Catch history pushState navigation, but ONLY for same origin navigation,
                // for reasons above about URL spoofing risk.
                self?.navigateInTab(tab: tab, webViewStatus: .url)
            }
            .store(in: &tab.webViewSubscriptions)

        webView.publisher(for: \.title, options: .new)
            .forEach(updateGestureHandler)
            .compactMap { $0 }
            // Ensure that the tab title *actually* changed to prevent repeated calls
            // to navigateInTab(tab:).
            .filter { !$0.isEmpty && $0 != tab.lastTitle }
            .sink { [weak self] title in
                tab.lastTitle = title
                self?.navigateInTab(tab: tab, webViewStatus: .title)
            }
            .store(in: &tab.webViewSubscriptions)
         
        webView.publisher(for: \.canGoBack, options: .new)
            .forEach(updateGestureHandler)
            .filter { _ in tab === tabManager.selectedTab }
            .assign(to: \.canGoBack, on: chromeModel)
            .store(in: &tab.webViewSubscriptions)

        webView.publisher(for: \.canGoForward, options: .new)
            .forEach(updateGestureHandler)
            .filter { _ in tab === tabManager.selectedTab }
            .assign(to: \.canGoForward, on: chromeModel)
            .store(in: &tab.webViewSubscriptions)

        webView.scrollView
            .publisher(for: \.contentSize, options: .new)
            .sink { [weak self] _ in
                self?.browserModel.scrollingControlModel.contentSizeDidChange()
            }
            .store(in: &tab.webViewSubscriptions)
```

These subscriptions are accumulated as the user navigates around links for a while. When I take those subscriptions away, the scrollView inside WKWebView works smooth. When there are memory leaks, the scroll view becomes sluggish.

**Comment by chassu** [comment]
I take back what I said about memory leak.. `webVIewSubscriptions.count` a tab owns doesn't increase as I click around links. But I'm still certain this part of the code is related to the issue. Need more investigation.

**Comment by chassu** [comment]
If I close the webView that gets slow and restore it, the problem goes away. Still feels to me something is accumulating in `Tab` when navigating around links.

**Comment by darinwf** [comment]
I narrowed this down to the `ContextMenuHelper.replaceGestureHandlerIfNeeded` calls made via `updateGestureHandler`. If I remove those then the performance problem is resolved.

**Comment by darinwf** [comment]
Probably before adding a gesture recognizer, we should remove the existing one so we avoid growing the number of gesture recognizers?

**Comment by evancrow** [comment]
Just looked, we actually do check if the gesture recognizer is already added, but we added the gesture under the wrong name so the check always returned false.
