### ISSUE TITLE
Not navigate to the app when open the link with Neeva

### ISSUE THREAD

**Issue by yasminyin96** [neevaco/neeva-ios#3867]
## Expected behavior

Open link in email -> Navigate to Neeva -> Open Uber Eats

## Actual behavior

Open link in email -> Navigate to Neeva 

Apps with this issue: Uber Eats, Walgreens, Sephora, Panera Bread

## Steps to reproduce the problem

1. Open the link in the email 

## Screenshots or recordings

with Safari

https://user-images.githubusercontent.com/104786010/173879189-4930dcf2-766a-4e03-b654-dce8574eb53e.MP4

with Neeva

https://user-images.githubusercontent.com/104786010/173879231-5a0415bf-4041-43b8-84c1-ea8d3a3b5940.MP4

## Hardware and software

- Your device: iPhone 12 Pro & iPhone 13
- OS version: 15.5
- App version: Neeva Browser 1.45.2 (236)

**Comment by evancrow** [comment]
@jedireza Wonder if this is related to the `about:blank` change.

**Comment by jedireza** [comment]
Hmm. That would be interesting if it was related to that. @yasminyin96 could you test these conditions with a commit prior to b61ae29 (https://github.com/neevaco/neeva-ios/pull/3793)>

**Comment by yasminyin96** [comment]
> Hmm. That would be interesting if it was related to that. @yasminyin96 could you test these conditions with a commit prior to [b61ae29](https://github.com/neevaco/neeva-ios/commit/b61ae29c9909c62ff112088b03989f226514221e) (#3793)

Sure!

**Comment by yasminyin96** [comment]
Still not navigate to the Uber Eats with a commit prior to that one. 
I tried to comment out `bvc.tabManager.removeBlankTabs()` this line, it does not work as well.

**Comment by yasminyin96** [comment]
FYI, I tried Duckduckgo, Neeva and Safari. Only Safari will navigate to the Uber Eats app.

**Comment by evancrow** [comment]
Ah okay, might be a special Safari thing. Everything still works right, just from the web? Does the Open in External App popup show?

**Comment by jedireza** [comment]
Looks like this is working now.
