### ISSUE TITLE
Sometimes the "show tabs" button does nothing (regression?)

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3908]
## Expected behavior

Tapping the "show tabs" button should show the tab switcher.

## Actual behavior

Sometimes the button press does nothing. See video.

## Screenshots or recordings

https://user-images.githubusercontent.com/79867437/175359831-7565b3ce-d44e-4853-8159-9fe53453fb6e.MP4

## Hardware and software

- Your device: iPhone 12
- OS version: iOS 15.5
- App version: Neeva Browser 1.46.0 (237)

**Comment by evancrow** [comment]
`CardTransitionState` strikes again

**Comment by darinwf** [comment]
Yeah... must somehow be possible to get into a state where we don't realize what state we are in.

**Comment by evancrow** [comment]
Do you have a repro for this?

**Comment by EdwardJTL** [comment]
i found that this can happen when the date rolls over while you are using the app. or you can reproduce this reliably if you open some tabs, go to settings, set the date to some far time in the future, and come back to the app

**Comment by evancrow** [comment]
Related to #3889 I think
