### ISSUE TITLE
Scrolling a text field results in the top bar hiding and showing

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3909]
## Expected behavior

Scrolling a text field in the page should not impact the top bar offset.

## Actual behavior

Scrolling a text field results in the top bar hiding and showing

## Steps to reproduce the problem

1. Go to a web page with a text field like hacker news
2. Enter text long enough to make the text field scrollable
3. Try scrolling the text field

## Screenshots or recordings

https://user-images.githubusercontent.com/79867437/175360632-49a39c4b-f8e3-410c-a04f-19208ebe2e9e.MP4

## Hardware and software

- Your device: iPhone 12
- OS version: iOS 15.5
- App version: Neeva Browser 1.46.0 (237)

**Comment by evancrow** [comment]
This is because the `ScrollingControlModel` puts a `PanGestureRecognizer` on the `WebView`, but there's no way to know if it's scrolling the top-level view or a TextField. Will see if there is a better way to detect scroll changes.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3b15b
