### ISSUE TITLE
Space Reordering Reverted After New Item is Added

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3918]
See video:

https://user-images.githubusercontent.com/37356984/175576472-537e7d67-4a8e-4891-871a-340dddad3a4a.MOV

I also notice two other minor issues:
- There are extra lines in the header
- The comments section BG gets more compact when headers are added

cc @buracules @yozuysal

**Comment by yozuysal** [comment]
This is another case where the local state and remote state being detached is shooting ourselves in the foot. @buracules I think making the local update changes also apply to refreshSpace cases would get around this.
