### ISSUE TITLE
Reconsider use of badge as a pin indicator

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3919]
## Problem
Current design:

<img src="https://user-images.githubusercontent.com/41495718/175608296-990bbd55-5982-46a9-8033-ca7154813e8b.png" height="600">

I think this design presents a couple of problems:
1. When a tab is pinned, it is harder for a user to close the tab -- they must use the 3D touch menu.
2. Tapping the close button results in an action (the tab is closed). On the other hand, the pin button does not result in an action, which might confuse the user. Of course, we can implement the functionality to have the button unpin the tab, but this feels strange, because once that button is clicked, it disappears (there is no toggle functionality).
3. (reported by @buracules ) In our existing code, the top-right badge disappears on 3D touch
<img src="https://user-images.githubusercontent.com/41495718/175609217-44b45337-93a9-488e-b047-113fca613d9b.jpg" height="400">

This makes sense that the close (X) badge is no longer visible, because there is a big red "Close tab" option. However, it's a bit odd that there is no pin indicator, although a user can infer whether the tab/Space is pinned or not based on whether the Pin/Unpin text exists in the context menu.

## What do we do?
One option is that we add a pin symbol next to the title of the tab/Space. However, this might add clutter to the title. Open to other ideas.

**Comment by jedireza** [comment]
Very similar to 🔒 https://app.clickup.com/t/3w3ayyp -- I link to this issue in that ClickUp ticket.
