### ISSUE TITLE
We need to set tabs as accesibiity hidden while spaces is shown

### ISSUE THREAD

**Issue by buracules** [neevaco/neeva-ios#3932]
## Expected behavior
Voice over should focus spaces list after spaces button

## Actual behavior
Voice over focuses tabs

## Screenshots or recordings

https://user-images.githubusercontent.com/15333612/175975172-0a2e3d9a-2e96-44a8-befc-42b156f74519.MP4

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3b23x
