### ISSUE TITLE
Cookie Cutter On/Off Toggle Out of Sync

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3936]
## Expected behavior

The state in the URL bar popup should match the in the app settings.

## Actual behavior

They don't match

## Steps to reproduce the problem

1. Turn it off from the popup
2. Go to settings from the popup

## Screenshots or recordings

https://user-images.githubusercontent.com/44557675/176010801-f3f8cb18-8b70-4d4a-a4f2-936489d8016d.MOV

## Hardware and software

- Your device: iPhone 13
- OS version: 16.0 (20A5303i)
- App version: built from main @ ee13051bf0bbe2928f28acff9e80869128823057

**Comment by evancrow** [comment]
@EdwardJTL The toggle in settings is the global toggle for **all** sites. The one in the URL bar only is site-specific. @hwiatneeva Maybe we need to make that clearer?
