### ISSUE TITLE
Explore WKWebView for prose-based content

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#394]
See https://github.com/neevaco/neeva-ios-phoenix/pull/374#discussion_r635778976, where I was unable to exactly match the mock because it is difficult to stitch together links/buttons with regular text.

**Comment by darinwf** [comment]
As of iOS 15, we can now initialize a SwiftUI Text object with an `AttributedString` including support for links: https://developer.apple.com/documentation/swiftui/text/init(_:)-1a4oh

I think we can therefore close this bug.
