### ISSUE TITLE
Comments are fairly broken

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3942]
You can't see it, but I am clicking "Add" repeatedly. The only way to submit comments, it seems, is to press Return on the software keyboard. Also, the comments are gone when I revisit the Space (I can see some of them on WebUI, though which is good).

https://user-images.githubusercontent.com/41495718/176045933-c8877f80-0601-418a-8199-27521245285c.MP4

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3b4vk
