### ISSUE TITLE
Unable to rename "kept" item from generator

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3943]
Repro:
- Create a Space tracking news topics, wait for it to populate
- Choose one entity, swipe left and click Keep
- Swipe left again and click edit
- Rename and save
- The name does not change

Sometimes it works, sometimes it doesn't. Sometimes the title in the Space detail list view doesn't change, but when I reopen the form, there is the correct title!

**Comment by jedireza** [comment]
> Create a Space tracking news topics, wait for it to populate

I don't know how to do this. Does it require a feature flag or something?

Besides that, the updating and stale UI visuals doesn't seem to be limited to renaming. I mentioned this issue in ClickUp 🔒 https://app.clickup.com/t/3w33hcy
