### ISSUE TITLE
When adding a new item to a Space, the URL should not be optional

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3945]
This will make us consistent with WebUI.

iOS
<img src="https://user-images.githubusercontent.com/41495718/176256874-76365b91-e171-4086-8d6a-4501c04391e9.png" height="500">

WebUI
<img width="387" alt="Screen Shot 2022-06-28 at 11 29 32 AM" src="https://user-images.githubusercontent.com/41495718/176256327-c6bcc8c1-37ab-491e-989a-19c649b4c870.png">

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3b9p9
