### ISSUE TITLE
Sign-in prompt needs dark-mode skin

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3951]
This is on the current App Store build 1.45.5.

<img src="https://user-images.githubusercontent.com/41495718/176489372-aea55c8c-6951-4ae4-9068-69c3bfc05784.PNG" height="600">

**Comment by darinwf** [comment]
@jedireza FYI

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3ba83
