### ISSUE TITLE
App review dialog got triggered too soon

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#3959]
@michellew7 reported:

```
ran 5 unmoderated tests and 4 out of 5 testers who created accounts (sign in with apple)  were prompted to review the app within 5 min of being in the app. the 5th person who did not see the rate the app prompt used sign-up with Neeva
```

Couple potential reasons:

* Default browser flow navigate to settings add to the # of app foregrounds more than usual
* Potential foreground activity got triggered for various sign in flow

**Comment by darinwf** [comment]
Perhaps we should require at least one day to have passed before we prompt?

**Comment by chung-lai** [comment]
> Perhaps we should require at least one day to have passed before we prompt?

That makes sense! Will also only start counting # of app foreground after user has dismissed the default browser interstitial

**Comment by chung-lai** [comment]
ah, looks like the user switches back and forth between apps to look at the testing instructions. And that's what increase # of app foreground and trigger the app review. cc @michellew7 

Having said that, still make sense to show app review only after 1 day and start counting app foreground after default browser interstitial.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3bapy
