### ISSUE TITLE
Updating profile name on share sheet does not work smoothly

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3961]
https://user-images.githubusercontent.com/41495718/176749745-b3b24c39-4eaa-4582-96b6-d8a28d57cdef.MP4

I did get it to update once, but it took a while, and subsequent attempts failed. The update also does not work reliably on WebUI.

**Comment by jedireza** [comment]
More stale updates. Added a mention to this issue in ClickUp 🔒 https://github.com/neevaco/neeva-ios/issues/3961
