### ISSUE TITLE
Close any Neeva home tabs when user signs out

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3965]
We should close any tabs on Neeva home (maybe also settings or any non-public route)  when the user signs out. It's strange that I can have a tab with Neeva home open, then sign-out and be left with the existing logged in tab.

**Comment by darinwf** [comment]
An alternative option might be to simply blank out these tabs (i.e., clear their saved screenshot). That way tabs and history within the tabs are not lost.
