### ISSUE TITLE
Rogue UI element when clicking sign-in from neeva.com

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#3972]
I noticed some extra UI, looks native, when clicking the sign-in link from neeva.com. This might be related to how we detect the sign-in URL and overlay the native sign-in UI.

https://user-images.githubusercontent.com/979929/177394350-c8f6223f-c2f8-4535-88db-242e6e6b9d56.mp4

**Comment by darinwf** [comment]
This is just on the simulator right?

**Comment by jedireza** [comment]
When I try this on my physical device, we're not showing the overlay.
