### ISSUE TITLE
Set as Default browser Prompt on Search Page

### ISSUE THREAD

**Issue by barisertgrul** [neevaco/neeva-ios#3993]
## Expected behavior

User should not see Set as Default Browser prompt in search page after, setting neeva as default browser
## Actual behavior

This went wrong.

## Steps to reproduce the problem

1. user downloads the app for the first time and click to open
2. see default browser warning as first page
3.  go to setting and set default4. 
4. go back to the app and click on " continue to neeva" button
5. on the next page user selects on of the from never community links and redirect to the page
6.  click on url to open menu and see sign in or join neeva prompt
7.  go with the login flow and login to neeva
8. click on any url in main page and on the page click on url
9. user see set as default browser prompt

## Screenshots or recordings

https://user-images.githubusercontent.com/17303291/177815459-f0dfeb44-8723-4ee8-be2e-e8f4e46d75d8.MP4

## Hardware and software

- Your device: iPhone 13 / iPhone 13 Pro Max / iPad Air
- OS version: 15.5
- App version: Neeva Browser 1.48.3 (243.2)
    - Found in app `Settings > About`

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3bbkq
