### ISSUE TITLE
iPad Landscape Margin Errors

### ISSUE THREAD

**Issue by barisertgrul** [neevaco/neeva-ios#3994]
NOTE: If this is a security or privacy related issue, please email
incidents@neeva.co instead of submitting an issue on GitHub.

Thank you for submitting an issue. Provide as much information as you can.

## Expected behavior

On related pages, page designs should aligned middle in ladnscape mode

## Actual behavior

related pages displayed margin left in landscape mode

## Steps to reproduce the problem

1.  user opens neeva home page in landscape mode
2. neeva home page opens in margin left in ladscape
3. user opens neeva home page in incognito
4. incognito page theme displayed in margin left

## Screenshots or recordings

![Neeva](https://user-images.githubusercontent.com/17303291/177831130-a22b5b0b-a411-441c-99f4-bf837724ef32.png)
![You are incognito](https://user-images.githubusercontent.com/17303291/177831145-36705bf8-8938-494c-8e81-0b64eb81347d.png)

## Hardware and software

- Your device: iPad Air
- OS version: 15.5
- App version: Neeva Browser 1.48.3 (243.2)
    - Found in app `Settings > About`

**Comment by evancrow** [comment]
@jedireza these look like some WebUI issues

**Comment by jedireza** [comment]
Yeah there is some affordance for the right column in the `webui` layout and when its empty it can feel unbalanced. We may want to consider closing this issue in the iOS repo and open a new issue for `webui` in the mono repo.

🔒 Related https://github.com/neevaco/neeva/pull/68231
