### ISSUE TITLE
Update feedback toast message

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#3997]
Per discussion on `#design-mobile`, we decided to change the feedback toast message from "Feedback Submitted!" to "Sent. Thanks for your feedback!"

This is for parity between iOS and Android.

**Comment by FloatingDorito** [comment]
Hello, I would like to fix the issue, may I know which file to modify?

**Comment by darinwf** [comment]
@FloatingDorito - awesome, thanks! here's the spot in the code:

```
./Frontend/Toast/ToastDefaults.swift:        let normalContent = ToastStateContent(text: "Feedback Submitted!")
```

**Comment by darinwf** [comment]
@FloatingDorito - btw, if you are interested in joining us on Slack, you can join using [this link](https://join.slack.com/t/neeva-makers/shared_invite/zt-1aplsqnrp-MQcAsJ7iqVHVHjN5py5XIg). You can find us in the `#browser-dev` channel.

**Comment by FloatingDorito** [comment]
Hi I've made the Pull request, please review and provide feedback, thank you.
