### ISSUE TITLE
Disable "Clear All Archived Tabs" when there is nothing to clear

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#3998]
Right now, when a user visits the Archived Tabs interface, the "Clear All Archived Tabs" button is enabled, even when there are no Archived Tabs. We would like to disable this button when a user has no Archived Tabs to reduce confusion.

<img src="https://user-images.githubusercontent.com/41495718/177870008-0caeef0b-6527-4492-80cf-d91d73b055ad.png" height="600">

Here is the relevant area of the code base: [Link](https://github.com/neevaco/neeva-ios/blob/15801d48d4479789cd634e9bad8429565d903d72/Client/Frontend/Browser/Card/ArchivedTabsPanelView.swift#L43)

**Comment by AlexBurneikis** [comment]
I have implemented a simple "if" statement, that checks if the numOfArchivedTabs != 0 but am unable to test as I am unsure how to archive a tab.

**Comment by AlexBurneikis** [comment]
Update: I have tested my code by changing the date and it works! Pull request incoming!
