### ISSUE TITLE
Make it possible to pull down on the Cheatsheet content to close the Cheatsheet

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4015]
Make it possible to pull down on the Cheatsheet content to close the Cheatsheet

We have this capability with the Add-to-Spaces sheet. When opening the Add-to-Spaces sheet, a user can easily drag down on the content area to close the sheet. We don't have this hooked up for the Cheatsheet, and so to close the Cheatsheet you have to carefully drag from the drag handle at the top.

@evancrow - Do you think this would be easy to resolve given how you solved it for Add-to-Spaces? @EdwardJTL FYI

**Comment by evancrow** [comment]
This is very possible, just need to change some `OverlayStyle` preferences. I think we made a purposeful decision to disable this functionality though when we were setting up the cheatsheet.
