### ISSUE TITLE
Navigate back from new tab doesn't work

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4016]
Steps:
1) open a link that creates a new tab
2) press back (nothing happens, button grays out)
3) go to tab switcher and back
4) back button works

Url:

https://www.thespruce.com/best-bookcases-4154873

App version
1.49.1(245) TestFlight 

Screen cap:
https://user-images.githubusercontent.com/44557675/178173653-661d6954-da71-47e1-a9a4-b601d734638e.MOV

Might be related to #4014

**Comment by evancrow** [comment]
Fixed by:  #4017
