### ISSUE TITLE
Regression: top and bottom bars no longer hide on scroll

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4022]
## Expected behavior

When scrolling a page, the top and bottom bars should hide.

## Actual behavior

Top and bottom bars no longer hide.

## Screenshots or recordings

https://user-images.githubusercontent.com/79867437/178342075-432d7cd7-abec-4218-905f-d3b94340ed10.MP4

## Hardware and software

- Your device: iPhone 12 
- OS version: iOS 15.5
- App version: Neeva Browser 1.49.1 (245)

I believe it was fine in 1.48.3, so this is a recent regression on `main`

**Comment by evancrow** [comment]
Going to the CardGrid and back seems to fix this.

**Comment by darinwf** [comment]
> Going to the CardGrid and back seems to fix this.

Interesting! Looks like just creating a new tab through tapping on the URL bar will also resolve the issue.

**Comment by evancrow** [comment]
The issue is caused by the `WebView` being created after the `selectedTabPublisher` is sent, so the `webView.scrollView` is `nil` when `setupDelegates` is set.
