### ISSUE TITLE
Regression: Signed out error page shown randomly while trying to add to a space

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4026]
## Expected behavior

Just see the add-to-spaces dialog

## Actual behavior

Signed out error page shown randomly while trying to add to a space

## Steps to reproduce the problem

1. Open a tab
2. Hit the add-to-spaces button
3. Open and close the add-to-spaces sheet a few times
4. Notice that it shows a "this page is a little shy" error page

This is not super easy to repro, but I have seen it twice now.

I'm not signed out, but I'm seeing this:

<img src="https://user-images.githubusercontent.com/79867437/178370748-26111863-aae2-451f-8a42-46e74878afde.PNG" width="300">

## Hardware and software

- Your device: iPhone 12
- OS version: iOS 15.5
- App version: Neeva Browser x.x.x (x)
    - Found in app `Settings > About`

**Comment by yozuysal** [comment]
nothing that comes to mind around spaces changes, though this would happen at the top level check for signed in or not so probably more related with UserInfo updating than anything spaces.

**Comment by darinwf** [comment]
> nothing that comes to mind around spaces changes, though this would happen at the top level check for signed in or not so probably more related with UserInfo updating than anything spaces.

OK. I saw this error a couple times today while playing around with the add-to-spaces UI. No idea how to reliably repro though :(

**Comment by buracules** [comment]
Only one change comes to my mind. When i add new state to space store states (mutatingLocally) i have to add that one in here too. And it returns EmptyView() for body right now. But i am not sure thats the case. Because other changes mostly changed mutation functions and they shouldnt effect the list.

**Comment by buracules** [comment]
Actually it looks like only errors from backend can trigger this screen.

```
var gqlErrors: [String]? {
        (error as? GraphQLAPI.Error)?.errors.compactMap(\.message)
    }

    var isLoginError: Bool {
        guard let first = gqlErrors?.first, gqlErrors?.count == 1 else { return false }
        return first == "login required to access this field" || first == "unauthorized access"
    }
```
 

 For this screen to show isLoginError has to return true

**Comment by darinwf** [comment]
I see... so there must be a backend bug here. Hmm...
