### ISSUE TITLE
Unable to drag down on the content of the add-to-spaces dialog to close the dialog

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4028]
## Expected behavior

Should be able to drag down on the content of the add-to-spaces sheet to dismiss the sheet

## Actual behavior

Unable to drag down on the content of the add-to-spaces dialog to close the dialog

## Steps to reproduce the problem

1. Open a tab 
2. Click on add-to-spaces
3. Swipe up to open the sheet
4. Now try to swipe down to close it
5. Only works if you swipe from the top handle bar - it should work when swiping down from the content

Notice how it kind of stutters down a bit as it seems like the gesture down is recognized but then interrupted.

## Screenshots or recordings

https://user-images.githubusercontent.com/79867437/178376025-86f32ceb-345c-495e-a440-fef4c282ba60.MP4

## Hardware and software

- Your device: iPhone 12
- OS version: iOS 15.5
- App version: Neeva Browser 1.49.1 (245)

**Comment by darinwf** [comment]
@evancrow @buracules @yozuysal - Any idea what might have regressed this recently?

**Comment by evancrow** [comment]
Did this ever work? When you expand the sheet, the content becomes scrollable so any dragging there is moving the content, not the sheet.

**Comment by darinwf** [comment]
> Did this ever work? When you expand the sheet, the content becomes scrollable so any dragging there is moving the content, not the sheet.

Oh guess not. I thought I remembered it working, but if you don't remember it, then I must be misremembering since I assumed you were the one who implemented it :-)

**Comment by buracules** [comment]
I was hoping apple can support iOS15+ with new detens api but its going to be iOS16+. Maybe we can fix it i did something like this in UIKit and i still have the codes but i have no idea how to do it with SwiftUI maybe we can look into it together @evancrow ?

Also i am experincing this in neeva scope as well


https://user-images.githubusercontent.com/15333612/178573496-ce66209b-70a8-41b7-be93-b4a420cc3dec.mp4

**Comment by EdwardJTL** [comment]
<img width="776" alt="Screen Shot 2022-07-13 at 9 48 39 AM" src="https://user-images.githubusercontent.com/44557675/178787894-6d493053-4651-4990-a7ae-f30d0e19bd95.png">
i have done some investigation on using a wrapped UIKit scrollview for neevascope before. I'd prefer we don't go that way unless you could address the problems it causes with the SwiftUI rendering cycle.
