### ISSUE TITLE
In the last several days the responsiveness (typing, rendering a result, responsiveness of browser after render, etc) has become increasingly bad and annoying

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4033]
Reported by a member of our Makers community.

"Currently 106 tabs open and 1034 archived. Set to archive every 7 days."

**Comment by EdwardJTL** [comment]
> Definitely could be that high number of archived tabs. We should invest in better infrastructure for archived tabs so that we avoid having to scan archived tabs for most operations. I.e., success looks like `TabManager.tabs` no longer including archived tabs.

I also see that all archived tabs are loaded and tabs objects are created for them on startup.

**Comment by evancrow** [comment]
I think it would be reasonable to have an `ArchivedTab` type, similar to `SavedTab` instead of creating a new, heavy `Tab` object.

**Comment by darinwf** [comment]
> I think it would be reasonable to have an `ArchivedTab` type, similar to `SavedTab` instead of creating a new, heavy `Tab` object.

Yeah. Reserving this task for @jonathangarelick ^^^
