### ISSUE TITLE
"Sign Up" graphic in spaces view is odd on iPad and landscape

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4039]
on main

not sure if this is the intended design. the graphics is on the left side of the text and button

![Simulator Screen Shot - iPad Air (5th generation) - 2022-07-12 at 16 32 20](https://user-images.githubusercontent.com/44557675/178617004-2ef92fce-55fb-42cf-bdd3-78c4f6f8e113.png)
![Simulator Screen Shot - iPhone 13 - 2022-07-12 at 16 48 27](https://user-images.githubusercontent.com/44557675/178617014-e7918ea2-4b5d-468a-b188-944620cce169.png)

**Comment by evancrow** [comment]
Should we just hide the graphic in this case?

cc @hwiatneeva

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3bct3
