### ISSUE TITLE
"I want reddit.com links to open a 3rd-party Reddit app"

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4055]
@yashneeva 
> A complaint we heard during a user interview was:
> 1. They like browsing reddit on apollo, an ios app
> 2. Apollo is integrated with safari, such that when they're on safari and click a reddit link they will be taken to apollo
> 3. For some reason, apollo isn't supported by the neeva browser (issue 1)
> 4. When they click a reddit link on the neeva browser, the only options are to open in safari or open in the reddit app (no apollo)
> 5. If they click safari, then it opens in regular safari, it isn't automatically redirected to apollo (issue 2)

I think issue 2 is out of our control, but we might be able to solve issue 1 if we figure out Apollo's custom app URL scheme.

**Comment by jedireza** [comment]
Apollo wrote a Safari extension to make this happen.

https://user-images.githubusercontent.com/979929/203441395-574b82b0-ef55-4b2f-8108-218e26ff758d.MP4
