### ISSUE TITLE
Clean up unused variables

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#4065]
As part of this work (https://github.com/neevaco/neeva-ios/pull/4064), we ran the `unused` ruby script in the code and found there are quite a few unused variables. (https://github.com/PaulTaykalo/swift-scripts). We may want to do a pass on those unused variables and do some clean up

**Comment by chung-lai** [comment]
May also be interesting to use this tool for identifying even more unused code: https://github.com/peripheryapp/periphery

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3bewu
