### ISSUE TITLE
Ad blocking rules exceed safari content blocker rule limit on iOS 14

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#4081]
When we run the app on iOS 14, the compiler asserts on exceeding safari content blocker rule limit as we load all the content blocking rules up front when the app starts even though we only use a subset of it.

There are couple options:
* we can disable ad blocker on iOS 14
* only load ad blocker rules on demand (which may need to restructure the code a bit)

**Comment by evancrow** [comment]
See comment:

https://github.com/neevaco/neeva-ios/issues/4082#issuecomment-1195002283

**Comment by chung-lai** [comment]
nvm, don't think we can load ad blocker rules on demand since we still want to have tracking protection list and it will exceed the same limit when the user enable ad blocking rules.

i think the best option here is to disable ad blocker for iOS 14.
