### ISSUE TITLE
Bottom bar pushed up and cannot be restored.

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4084]
## Expected behavior

Bottom bar stay on the bottom

## Actual behavior

<img width="206" alt="Screen Shot 2022-07-25 at 6 45 50 PM" src="https://user-images.githubusercontent.com/44557675/180904679-a39bf9f3-ad34-4979-a17e-21a3f2c0474f.png">
Screenshot from external folk.

## Steps to reproduce the problem

have not found a reliable way to reproduce it

## Hardware and software
seems to only be a problem when running on iOS 16. I assume the external folk installed the app through app store/testflight instead of building and compiling themselves.

**Comment by evancrow** [comment]
I see the bug here, the BottomBar is appearing while the keyboard is shown when returning to the foreground from the background.
