### ISSUE TITLE
Tab selection animation dropping frames

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4085]
## Expected behavior

Smooth animation?

## Actual behavior

See recording

## Steps to reproduce the problem

This does not happen with the current app store build (which is a few weeks behind). The screen recording is from building from main on debug.

## Screenshots or recordings

https://user-images.githubusercontent.com/44557675/180906066-3b052351-7d0b-42d0-a1a1-feef947642c5.MP4

**Comment by evancrow** [comment]
Something must have happened to the lazy WebView. Are we sure this is iOS 16 specific?
