### ISSUE TITLE
Back swiping a page shows a black screen instead of the previous tab

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4093]
TestFlight v1.51.0

Can't see prev page when back swiping, it is all black. The animation also seems slower.

https://user-images.githubusercontent.com/41495718/181153551-76dad6cc-49d9-4474-8d68-0f75c937bea5.MP4

**Comment by evancrow** [comment]
@jonathangarelick Safe to close?

**Comment by evancrow** [comment]
Ah I misread your earlier comment. Thought you meant that the latest version was working fine. This issue has not been fixed then.
