### ISSUE TITLE
Error after deleting a space

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4100]
on main:
received these errors in console when deleting a space

<img width="899" alt="Screen Shot 2022-07-28 at 11 29 47 AM" src="https://user-images.githubusercontent.com/44557675/181612121-e9617962-22db-46c8-bda5-a3e6cf2bc53f.png">

the space does appear to be deleted. maybe the client is just trying to fetch the deleted space?

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3bhe9
