### ISSUE TITLE
User report of UI becoming very sluggish

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4128]
"noticeable latency on most actions like opening a tab, clicking on a link, closing a tab"

Version 1.51.1

The user reports having a reasonable number of active tabs. However, they might have a ton of archived tabs, and we know that there are still UI scenarios that involve scanning all tabs and not just the active tabs. It could be that we need to do a better job of isolating the cost of archived tabs (as we have known we've wanted to do).

**Comment by yasminyin96** [comment]
Same problem, but only have 14 active tabs and 35 archived tabs(26 for last month and 9 for older).

https://user-images.githubusercontent.com/104786010/182295001-792e5629-47c9-43bc-b593-4ea96ef10344.mov

**Comment by darinwf** [comment]
Hey @yasminyin96 - I think that is you tapping on the tabs to select them, right? If so, I think that issue should be resolved in the latest TestFlight build (1.52.2) thanks to a recent fix from @evancrow. Would be great if you could confirm. Thanks!

**Comment by yasminyin96** [comment]
> Hey @yasminyin96 - I think that is you tapping on the tabs to select them, right? If so, I think that issue should be resolved in the latest TestFlight build (1.52.2) thanks to a recent fix from @evancrow. Would be great if you could confirm. Thanks!

I switched to TestFlight version and this issue is resolved. Thank you.

**Comment by evancrow** [comment]
@darinwf I think all of those actions are affected by `selectTab`, which probably means this issue is fixed.
