### ISSUE TITLE
privacy policy and terms links are truncated/wrapped

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#4150]
In other language where "terms and services" and "privacy policy" have longer text. They result in truncation/wrapping:

<img width="561" alt="Screen Shot 2022-08-04 at 8 01 16 AM" src="https://user-images.githubusercontent.com/87332578/182883463-3521cdcb-b00b-46e3-bec0-c3d4f9b15498.png">

For testing, can simply change those terms into longer text and see how it behave.

cc @evancrow

**Comment by chung-lai** [comment]
One option is to try converting that into markdown but not sure if we can override the url open logic to open the link in SafariViewController.

**Comment by jedireza** [comment]
These old intro view screens are gone now. The new welcome/sign-in-up screens scroll vertically to prevent clipping like this.

<img width="534" alt="image" src="https://user-images.githubusercontent.com/979929/203444162-09282286-5a1c-4cc0-9a6b-863d54407847.png">
