### ISSUE TITLE
Bottom bar not updated properly when exiting switcher from spaces

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4151]
Bottom bar is not updated properly when leaving the switcher from having visited spaces

<img src="https://user-images.githubusercontent.com/79867437/182909159-a9185d7d-fe0a-4be2-a970-dba34a3530de.jpg" width="300">

See video below for exact (possibly extraneous) repro steps:

https://user-images.githubusercontent.com/79867437/182909079-fde8a24a-e89d-4d4f-a1ce-1b909c9ec7d0.MP4

- App version: Neeva Browser 1.52.4

**Comment by darinwf** [comment]
Something about the flow from removing the page from a space, hitting the "open space" link and then hitting back followed by "done" leaves the app in this broken state.

**Comment by evancrow** [comment]
This hasn't been reported in a while, and with many toolbar improvements, I think this can be closed.
