### ISSUE TITLE
Tab Grid icon animated separately during transition

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4159]
If you look at it frame by frame, the text and the screenshot are animated at the same time, but the icon is not. Towards the end of the animation, there is a noticeable bounce animation on the icon where the bottom part of it gets occluded.

## Screenshots or recordings

https://user-images.githubusercontent.com/44557675/182942343-40e79192-4a4a-4a78-b958-769c75db7509.MP4

## Hardware and software

- Your device: iPhone 13
- OS version: 16 beta 3
- App version: Neeva Browser 1.51.1 (249.1)

**Comment by darinwf** [comment]
On iOS 15, I also observe the favicon appearing to not be animating in perfectly alongside the text label. Perhaps that is a clue as to how to resolve this.

**Comment by evancrow** [comment]
Resolved by #4250
