### ISSUE TITLE
Changing a Space entity's title does not always update immediately

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4160]
this was missed in #4136

cc @buracules 

https://user-images.githubusercontent.com/41495718/182947980-02bf2231-ba9f-40b9-92c5-65b60c113c0d.mp4

note that the entity with the URL immediately updates, but the entity without the URL does not immediately update.

**Comment by buracules** [comment]
Also thumbnail update doesn't work.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w33hcy
