### ISSUE TITLE
Done button in Tab Switcher can be in wrong state after closing all tabs

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#4166]
The done button is still activated after closing all tabs, this was caught by a flaky `testDoneButtonState`. The trick to reproduce this is to quit the app on an empty tab switcher. After that, you should see the tab switcher when you launch the app again. So it seems to have something to do with the screen restore flow. cc @evancrow 

Reprod video:

https://user-images.githubusercontent.com/87332578/183016297-1d9f062d-60c3-4b16-92a2-4d499ae38e30.mov

**Comment by evancrow** [comment]
Hm can't seem to repro that @jonathangarelick
