### ISSUE TITLE
iPadOS 16 IntroView cut off

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4174]
## Actual behavior

Bottom part of intro view is cut off. Sign in option is not visible or available. No scrolling available.

In centre stage, app can be almost arbitrarily sized.

## Steps to reproduce the problem

1. Enable centre stage
2. Trigger sign in at various app sizes

## Screenshots or recordings
![IMG_0005](https://user-images.githubusercontent.com/44557675/183520486-0e4c9693-efc1-4685-8d2a-d9d84b6c600a.png)

## Hardware and software

- Your device: iPad Air 5
- OS version: 16.0
- App version: Neeva Browser 1.51.1

**Comment by evancrow** [comment]
Fixed by the new welcome view
