### ISSUE TITLE
Add to Spaces Infinite Loading & Flashing

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4176]
## Actual behavior

Add to spaces keeps flashing. This behaviour is intermittent. Not quite sure how to reliably reproduce it. I’m also not certain if this one is iOS 16 specific.

# Steps to reproduce the problem

1. Enter centre stage
2. Do a bit of resizing
3. Open add to spaces 

## Screenshots or recordings

https://user-images.githubusercontent.com/44557675/183521351-8da9364f-4b46-476e-8ba7-247fa3c46a81.mov

## Hardware and software

- Your device: iPad Air 5
- OS version: iPadOS 16.0
- App version: Neeva Browser 1.51.1

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3bk2k
