### ISSUE TITLE
[Build Script] Check NEEVA_HOME env

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4178]
This env variable should be checked before it is first used in the build script, which is at line 11 currently.

**Comment by chung-lai** [comment]
Guess we should move NEEVA_HOME check to the beginning of the build-release script. It's right now being checked after bootstrap and it's only checking if slack script exist :)

```
if ! test -f "$NEEVA_REPO/client/browser/scripts/send-slack-message.sh"; then
  if [ -z ${NEEVA_REPO} ]; then
    echo 'Set $NEEVA_REPO to point to your neeva main repository'
  else
    echo "No slack script detected, make sure you have the latest changes from main Neeva repo"
  fi
  exit 1
fi
```

**Comment by chung-lai** [comment]
We can probably close this with the new build system in place, no more neeva repo dependency.
