### ISSUE TITLE
[Build Script] Check GitHub CLI access

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4179]
Check for GitHub CLI access before continuing. Currently if CLI access is not valid, the script just aborts when trying to create the PR to increment version strings on main.

**Comment by chung-lai** [comment]
I think that's intentional. If there is no cli access, it bumps the version and push the branch. Then you have to create the PR manually

**Comment by darinwf** [comment]
But probably we want folks who run this script to let the script generate the PRs for them? Maybe we should at least give you a heads-up to install the script and let you know that not having it will mean you have to generate the PR manually?

**Comment by chung-lai** [comment]
We can probably close this with the new build system in place, no more pr creation needed on our local machine
