### ISSUE TITLE
One tracker blocked on neeva.com after signing in via QR code

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4184]
There shouldn't be any content on neeva.com that gets classified as a tracker, but seems like something is tripping over our filters. This only happens when signing in via QR code.

Observed by @hwiatneeva using build 255 from TestFlight.

@chung-lai FYI

**Comment by hwiatneeva** [comment]
![image (10)](https://user-images.githubusercontent.com/91506909/183761984-bde8c044-f79c-4d8e-b971-eb24c2263fb1.png)

neeva.com/qr-login-landing

**Comment by chung-lai** [comment]
interesting, may also be possible that it's an issue with the client side stats. Will identify which rule it triggers

**Comment by jedireza** [comment]
Just signed in with a QR code and I'm not seeing this.

![IMG_9058B7650160-1](https://user-images.githubusercontent.com/979929/203446832-4cd9cf81-3197-4cac-98cc-e45f32d1c8b1.jpeg)
