### ISSUE TITLE
Old tabs that should be archived currently aren't if they are part of a tab group that has a non-archived tab

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4190]
Old tabs that should be archived currently aren't if they are part of a tab group that has a non-archived tab

We should exclude all tabs that are too old first, and then only show tabs in the main card grid that are within the archive window. That means that tab groups may be partial, only showing the non-archived portion in the main card grid. The archived portion would live in the archived tabs section.

**Comment by evancrow** [comment]
@darinwf Don't know why we thought that this wasn't working, but this already works on main. But after messing around with it, the `ArchivedTabsPanel` is totally flakey. I'm going to refactor it heavily.

**Comment by darinwf** [comment]
@evancrow - Thanks for investigating
