### ISSUE TITLE
Account Settings Read mode Error

### ISSUE THREAD

**Issue by barisertgrul** [neevaco/neeva-ios#4191]
NOTE: If this is a security or privacy related issue, please email
incidents@neeva.co instead of submitting an issue on GitHub.

Thank you for submitting an issue. Provide as much information as you can.

## Expected behavior

This is what I expected to happen.On Account settings page there should be no read mode

## Actual behavior

On the Account settings page when user opens reader mode user only see neeva icons

## Steps to reproduce the problem

1. Go to settings page
2. login to neeva 
3. go to account settings 
4. Open reading mode
5. user see neeva icons

## Screenshots or recordings

This is a big help if possible and relevant.

## Hardware and software

- Your device: iPhone 13
- OS version: 15.5
- App version: Neeva Browser 1.53.4 (255.2)
    - Found in app `Settings > About`
![IMG_99469CAEF3F4-1](https://user-images.githubusercontent.com/17303291/184119176-fe3fb698-e429-4b70-94bc-1d67510e80bc.jpeg)

**Comment by jedireza** [comment]
I think we're inheriting "reader mode" state from webkit. I found https://stackoverflow.com/q/2999600 and it doesn't seem like it's something we have a lot of control over on the markup side. I'm not seeing much we can do here.
