### ISSUE TITLE
Privacy & Security Section is not Shown in Account Settings

### ISSUE THREAD

**Issue by barisertgrul** [neevaco/neeva-ios#4192]
NOTE: If this is a security or privacy related issue, please email
incidents@neeva.co instead of submitting an issue on GitHub.

Thank you for submitting an issue. Provide as much information as you can.

## Expected behavior

User should be able to see privacy and security section in account settings

## Actual behavior

User can not see privacy and security section unless kill the app and reopen after install

## Steps to reproduce the problem

1. Login to neeva
2. Go to settings
3. Go to Account settings
4. There is no privacy and security section
5. Kill the app and reopen
6. User can see privacy and security section 
## Screenshots or recordings

This is a big help if possible and relevant.

## Hardware and software

- Your device: iPhone 13
- OS version: 15.5
- App version: Neeva Browser 1.53.4 (255.2)
    - Found in app `Settings > About`

https://user-images.githubusercontent.com/17303291/184122441-281bb612-dcd2-4af7-bc26-095e87e5dc16.MP4

**Comment by jedireza** [comment]
I was unable to reproduce.
