### ISSUE TITLE
Sign in apple needs better error message when email is already in use

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4197]
if you have an account via okta
and you try to sign in with google, it gives error "there is already an account for this email address. please sign in with your email address instead"

but, if you try to sign in with apple and don't forward your email, it can either
1) succeed in the popup, but then fails to sign in and redirect you to web app sign in with generic error message
2) hangs in the popup and eventually fails with "no connection" error

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3bqy1
