### ISSUE TITLE
View benefits link is broken

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4206]
https://user-images.githubusercontent.com/44557675/184433536-94869c1a-e193-43e7-ada9-e59cc61e46f0.MOV

**Comment by evancrow** [comment]
@jedireza Would this have anything to do with hiding text related to premium to pass Apple Review? The entire membership section appears to be hiding on mobile native since the URL is correct and everything appears on desktop.

**Comment by jedireza** [comment]
Yes IIRC we hide that section from the iOS app since it was a way to pay for premium outside of the native app. Possible solutions:
* just remove this link from the settings screen
* instead of hiding the membership section in webui, replace it with a message that makes sense for iOS

**Comment by evancrow** [comment]
It should probably have a message on the WebUI. In addition to this case, it also makes sense to have one if the user makes it to that page from another source without context.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3br41
