### ISSUE TITLE
Show desktop site is broken on Neeva settings

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4207]
This should work on our own websites at least lol
https://user-images.githubusercontent.com/44557675/184433608-bb8ba13e-0e9f-4e63-a602-081825562a34.MOV

**Comment by darinwf** [comment]
I think this might be WAI given how the site is built. Try shrinking down your desktop window.

**Comment by jedireza** [comment]
Yes this is WAI (response css).
