### ISSUE TITLE
[iPadOS 16] Bottom Tool Bar not showing

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4222]
I did not notice this to be an issue when I filed #4175. 

on iPadOS in center stage, when you resize the screen, it looks like the top bar is able to switch to the iPhone-analogous view, but the bottom bar is not showing. 

[Video to come]

While in split screen on iPadOS 15, the bottom bar shows up correctly.

https://user-images.githubusercontent.com/44557675/184683210-e3cedbb0-9a77-4659-9bce-89879d8b262d.mov

**Comment by EdwardJTL** [comment]
@evancrow fyi

**Comment by EdwardJTL** [comment]
https://user-images.githubusercontent.com/44557675/184686990-9d9aad84-aaf7-4ecc-a917-23515736df23.MOV

it does not let me upload into the original PR description :(

**Comment by evancrow** [comment]
This is fixed for me in today's beta (B6)

**Comment by EdwardJTL** [comment]
> This is fixed for me in today's beta (B6)

Yup just updated and it went away... nice lol
