### ISSUE TITLE
Support Pointer Editing Menus on Text Selection

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4232]
nice to have for iPadOS 16 for more pointer friendly interface

**Comment by EdwardJTL** [comment]
[What’s new in iPad app design - WWDC22 - Videos - Apple Developer](https://developer.apple.com/wwdc22/10009)

see 6:30

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3brg4
