### ISSUE TITLE
Selection in Tab Manager

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4233]
Video of how selection works in Notes. We could borrow some features, such as pinning, deleting, and moving(grouping). I’d personally really appreciate these features.

Filing this now so we may discuss it in a future design discussion.

https://user-images.githubusercontent.com/44557675/184734433-b31b2421-1ba2-4b1d-86c2-0989c96994e9.mp4

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3brhp
