### ISSUE TITLE
Hide tab card strip when there’s only one tab

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4249]
Just a suggestion
![IMG_0025](https://user-images.githubusercontent.com/44557675/185048670-53283650-73a7-431e-b01d-08c6e2570a41.png)

**Comment by EdwardJTL** [comment]
@evancrow fyi

**Comment by evancrow** [comment]
Fixed by: #4230

You prob have a pinned tab open that isn't visible (also fixed by #4230), but the strip model includes that in the open tab count.
