### ISSUE TITLE
Regression: Regular tabs can be seen on the incognito tabs container momentarily

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4270]
Regression: Regular tabs can be seen on the incognito tabs container momentarily

This happens when a regular tab in a tab group is scrolled horizontally to the left of the regular tabs container. This looks like a recent regression.

Video:

https://user-images.githubusercontent.com/79867437/185988067-7e1328db-5ea3-4c3b-9fe3-794fef9c5b99.MP4

## Hardware and software

- Your device: iPhone 12
- OS version: 15.6.1
- App version: Neeva Browser 1.55.1 (260)

**Comment by darinwf** [comment]
I'm not sure how to repro this. After restarting the browser on my device, I can no longer repro either :(

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3brmx
