### ISSUE TITLE
Pinned tab card transition animation is broken; tab doesn't show until card grid is manually scrolled

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4272]
Pinned tab card transition animation is broken; tab doesn't show until card grid is manually scrolled

https://user-images.githubusercontent.com/79867437/185991279-4d94fd7e-2534-4f32-adb9-e8dd58fd89e4.mp4

## Hardware and software

- Your device: iPhone 12 and iPhone 13 sim
- OS version: 15.6.1
- App version: Neeva Browser 1.55.1 (260)

**Comment by darinwf** [comment]
Somehow this is only happening with pinned tabs. I think there must be something about the pinned tab section that is different than the today section. @evancrow FYI

**Comment by darinwf** [comment]
> Hmm, this works fine for me. Tested it with 100+ tabs, some pinned, with different sections.

Hmm... I'm able to fairly easily repro. That video was from a simulator.

**Comment by evancrow** [comment]
I'm on a simulator as well, main branch
