### ISSUE TITLE
Adding to space from home screen + srp is non-native UI

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#4275]
Also when clicking the "open space" button takes the user to the non-native space page.

**Comment by yozuysal** [comment]
hmm, sounds like a regression. We should be hijacking all neeva.com/spaces urls and routing them as native deeplink requests. I think this logic used to be in BVC somewhere.

**Comment by buracules** [comment]
https://user-images.githubusercontent.com/15333612/186405780-0d993cb0-11db-4c0b-958c-5cb4f6758a92.mp4

@jedireza  Are you talking about this or another "open space" action?

**Comment by jedireza** [comment]
No Neeva home page (after login) and also any SRP result.

**Comment by EdwardJTL** [comment]
https://user-images.githubusercontent.com/44557675/193701598-a7ed026c-ca4d-44cb-90bf-57643d8af92c.MP4

i think its these ones?

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3brz5
