### ISSUE TITLE
Spaces screen is not cleared out after signing out

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#4276]
After signing out, spaces were still showing the state from being signed in.

https://user-images.githubusercontent.com/979929/186027487-4cb37adc-22a0-4b39-b1db-c9e996258c17.mp4

**Comment by yozuysal** [comment]
Looks like the publisher listening to sign in/out is failing? (We should be clearing the allSpaces cache on signed out.

@buracules we might need a Spaces polish day :) I think there was another pretty visible bug that was filed last week.

**Comment by buracules** [comment]
I can't reproduce this. Right now it's observing isUserLoggedIn state and changing the manager. I can also remove the allSpaces cache but if this doesnt work user will not see "From the neeva community" space and "Kill the Clutter" view.

**Comment by buracules** [comment]
@jedireza can you reproduce this?

**Comment by jedireza** [comment]
Yes I just reproduced with the latest test flight build `261.2 (v1.55.4)`.

With a fresh app install:
* I signed in with my AppleID
* Ran a search, clicked a result
* Hit the add to space button in the bottom bar
* Added to save for later
* Signed out
* Went back to spaces
* Only saw "From the Neeva community"
* Then I signed in with my Google account and did everything above over again
* This time spaces stayed populated (bug reproduced)

**Comment by jedireza** [comment]
Here is a screen recording reproducing from a fresh install off of `main`.

https://user-images.githubusercontent.com/979929/186574510-764fa631-133c-4ed7-8c51-1bdbe03d9418.mp4

**Comment by buracules** [comment]
https://user-images.githubusercontent.com/15333612/186911282-2ca74d4a-c898-41af-8778-16fefb5fd95e.mp4

I still can't reproduce it. All of this changes depends on `isUserLoggedIn`. Maybe status doesn't update itself correctly?

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3btba
