### ISSUE TITLE
QR sign-in Text Margin Error

### ISSUE THREAD

**Issue by barisertgrul** [neevaco/neeva-ios#4285]
NOTE: If this is a security or privacy related issue, please email
incidents@neeva.co instead of submitting an issue on GitHub.

Thank you for submitting an issue. Provide as much information as you can.

## Expected behavior

QR sign in popup texts fit to the screen

## Actual behavior

QR sign in popup information texts are not fit to the screen

## Steps to reproduce the problem

1. Login to neeva
2. go to settings
3. go to account settings
4. click on QR code sign in start button
5. see QR code window opened and information texts are not  fit to the screen 
## Screenshots or recordings

This is a big help if possible and relevant.

## Hardware and software

- Your device: iPhone 13
- OS version: 15.6.1
- App version: Neeva Browser 1.55.3 (261.1)
![IMG_8259](https://user-images.githubusercontent.com/17303291/186365038-d5fe638e-4bae-4ed8-9d49-e82be23468cd.PNG)
![IMG_BB0751F79FCB-1](https://user-images.githubusercontent.com/17303291/186365047-c1fc2793-61dc-47e7-895c-03493cde0534.jpeg)

    - Found in app `Settings > About`

**Comment by evancrow** [comment]
This appears to be a WebUI issue, not an iOS issue.

cc @seth737 @jedireza

**Comment by jedireza** [comment]
Correct. This needs to be fixed on the webui side.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/36034046/TRI-239
