### ISSUE TITLE
[Suggestion] Manage Go Back in Graph

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4302]
Overall Idea:
- Use an acyclic graph to represent navigation stack
- Each connected component of the graph will be a tree.
- Inside each tree, a node will take on one of the three types
  - ZeroQuery
  - SpaceItem
  - weak ref to Tab with navigation stack (backforward list)
- A "pointer" will indicate a tab's current state in the graph
  - navigating backward/forward on the tab will move the pointer
  - when moving the pointer:
    - the stack on the tab is prioritized
    - if the advancing the pointer will move past the stack bounds, then 
      - a graph traversal is performed, which may destroy the current tab object
- at appropriate times (TBD), we can fall back to the current logic of selecting "adjacent"/most recently used tab

Motivation:
- Tab go back logic has distributed ownership between `Tab`, `WebView`, and `SimulatedSwipeController`
- Some tab operations are currently expensive:
  - removing a tab requires traversing through every tab to remove their parent properties, which also triggers canGoBack update
  - many operations call `backNavigationSuggestionQuery` to update different types of back visibility

Challenges:
- Fast indexing into the graph
- the "pointer" for the navigation stack on a tab would need to be proxied; we still use `WKWebView`'s native go back method
- Setting states for forward navigation would be challenging
- Garbage collection to remove invalid items

Additional benefits:
- the navigation graph should be testable without UI tests.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3btxu
