### ISSUE TITLE
Search Page Default Browser Prompt Error 

### ISSUE THREAD

**Issue by barisertgrul** [neevaco/neeva-ios#4321]
NOTE: If this is a security or privacy related issue, please email
incidents@neeva.co instead of submitting an issue on GitHub.

Thank you for submitting an issue. Provide as much information as you can.

## Expected behavior

After selecting Neeva as default browser, user should not see default browser prompt on search page

## Actual behavior

user see default browser prompt on search page even after selecting Neeva as default browser

## Steps to reproduce the problem

1. run first run flow
2. select Neeva as default browser when it asks
3. login to Neeva
4. go to search page and see default browser prompt 

## Screenshots or recordings

This is a big help if possible and relevant.

## Hardware and software

- Your device: iPhone 13
- OS version: 15.6.1
- App version: Neeva Browser 1.56.3 (264.1)
    - Found in app `Settings > About`

https://user-images.githubusercontent.com/17303291/187703888-3989e462-6960-4bf1-8077-9e88e8a308be.MP4

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3bbkq
