### ISSUE TITLE
SDWebImageSwiftUI SwiftUI Runtime Warning

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4325]
There are three lines in the SDWebImageSwiftUI package that raise the runtime warning "Publishing changes from within view updates is not allowed, this will cause undefined behavior."

Carthage/Checkouts/SDWebImageSwiftUI/SDWebImageSwiftUI/Classes/SwiftUICompatibility.swift:49; `PlatformAppearView.willMove`
Carthage/Checkouts/SDWebImageSwiftUI/SDWebImageSwiftUI/Classes/WebImage.swift:60; `WebImageView.body`
Carthage/Checkouts/SDWebImage/SDWebImage/Core/SDWebImageManager.m:623: `callCompletionBlockForOperation`

**Comment by chung-lai** [comment]
Looks like a fix may be coming, On their github (PR 225)
