### ISSUE TITLE
Hangrisk in GCDWebServer

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4326]
Carthage/Checkouts/GCDWebServer/GCDWebServer/Core/GCDWebServer.m:678: warning run: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions

in `GCDWebServer._stop`, `dispatch_group_wait(_sourceGroup, DISPATCH_TIME_FOREVER); `

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3c1jc
