### ISSUE TITLE
Preferred providers does not realize I'm not logged in

### ISSUE THREAD

**Issue by jedireza** [neevaco/neeva-ios#4328]
There should be a message/warning about this feature requiring the user be logged in.

https://user-images.githubusercontent.com/979929/188026290-1e72c1b9-7320-48ad-8e40-2c94b1655980.mp4

**Comment by darinwf** [comment]
I think I recall hearing that there was an intention to make this work for preview users. @seth737 - do you know if this is WAI?

**Comment by seth737** [comment]
Yes, we implemented preferred provides for preview sessions as part of the
CAT work. When a user has set preferred providers in a preview session and
then creates an account, those preferences get transferred and save as part
of their user account.
