### ISSUE TITLE
Conflict in keyboard command when restore tab toast is showing

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4332]
I am not sure if this problem is limited to iPadOS 16.

Steps:
- On iPad with physical keyboard, close two tabs from the tab strip. Then, wait for the toast to show. Press cmd+shift+T. 

Expect:
- As shown in the toast label, restore 2 tabs.

Actual behaviour:
- Restore only the last closed tab. I think the always active BVC keyboard commands are prioritized?

**Comment by evancrow** [comment]
I had fixed this before, must have been broken again. Will take a look.
