### ISSUE TITLE
Privacy Policy Page Sign In Error

### ISSUE THREAD

**Issue by barisertgrul** [neevaco/neeva-ios#4338]
NOTE: If this is a security or privacy related issue, please email
incidents@neeva.co instead of submitting an issue on GitHub.

Thank you for submitting an issue. Provide as much information as you can.

## Expected behavior

After Login to Neeva, user opens privacy policy from settings page and don't see sign up button

## Actual behavior

After Login to Neeva, user opens privacy policy from settings page and see sign up button, when clicked user goes through sign up flow again
## Steps to reproduce the problem

1.  user login to Neeva
2. user go to settings page
3. go to privacy policy page
4. click on sign up button on privacy page  

## Screenshots or recordings

https://user-images.githubusercontent.com/17303291/188840005-58f1cc29-2ba1-4c44-9bc1-e505f8b53446.MP4

This is a big help if possible and relevant.

## Hardware and software

- Your device: iPhone 13
- OS version: 15.6.1
- App version: Neeva Browser 1.57.2 (267)
    - Found in app `Settings > About`

**Comment by jedireza** [comment]
This is a webui bug. Filed ticket here: 🔒 https://app.clickup.com/t/36034046/TRI-230
