### ISSUE TITLE
[iOS 16] Thumbnail does not resize properly when transitioning to card grid

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4359]
Observed using build 1.57.1 (266):

Here's a snapshot of the animation part way thru:
<img width="350" alt="Screen Shot 2022-09-13 at 10 18 27 AM" src="https://user-images.githubusercontent.com/79867437/189975169-e2b17460-25ee-413f-9efa-333639b22456.png">

The thumbnail should be the same size as the card boundary. This appears to be an iOS 16 specific regression.

This issue may also be related to the "Publishing changes from within view updates is not allowed, this will cause undefined behavior." issues we are seeing associated with SDWebImageSwiftUI on iOS 16.

I cannot reproduce this bug using a simulator. It only shows up on a real device, in this case on an iPhone 12.

**Comment by darinwf** [comment]
I'm not able to repro using a debug build on device, so this might be a release build specific issue.

**Comment by evancrow** [comment]
If you build for profiling, it installs the production version. Will try that and see if I can reproduce.

**Comment by evancrow** [comment]
Border looks fine, but the text does not animate with the card:


https://user-images.githubusercontent.com/37356984/190699637-a872fc94-a389-4d80-beb0-9a8b7d1a4332.mp4

**Comment by darinwf** [comment]
Yes, i can no longer repro the original bug report with the latest TestFlight
