### ISSUE TITLE
Transition between incognito and normal tabs could use some polish

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4381]
Observed using 1.59.2 (274):

https://user-images.githubusercontent.com/79867437/190814301-5deccf09-ad61-4c3d-a763-6db89af0557a.mp4

The incognito mode description text overlaying the normal tabs is not great. The fact that it instantly hides the normal tabs instead of showing them slide off to the right seems undesirable as well.

**Comment by evancrow** [comment]
Has been fixed by #4374
