### ISSUE TITLE
Regression: show tabs button does not work after doing a search (which results in a new tab)

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4386]
Observed using TestFlight 1.59.4 (276):

If you do a search, which results in a new tab, then the "show tabs" will animate when tapped but not result in showing you the card grid.

Most likely this means we are missing a call to `updateAllTabDataAndSendNotifications` -- i.e., the newly created tab does not have a corresponding `TabCardDetails`.

**Comment by darinwf** [comment]
https://user-images.githubusercontent.com/79867437/190916638-8a0af734-3f2f-4e4e-b9fe-bfe78c52972f.MP4

**Comment by darinwf** [comment]
Frustratingly, I cannot repro on `main` with a debug build.

**Comment by darinwf** [comment]
OK, to repro the current tab has to be a pinned tab.

**Comment by darinwf** [comment]
> OK, to repro the current tab has to be a pinned tab.

Actually, that's not right either. I think the real issue has to do with there being some scenarios in which scrolling to the selected card is not happening.

**Comment by darinwf** [comment]
OK, figured it out. `Row.index` always starts at 0 within a section. This means there are multiple `Row` objects with `index` of 1. As a result, the code in `TabGridContainer.selectedRowId` incorrectly returns the ID of the `rows[0]` when selecting any tab that is the first in a section.

So for example if you are on a pinned tab (and have a bunch of pinned tabs) and then open a new tab (via searching from the location bar) and if this is the first new tab you are creating today, then the newly created tab will be the first in the today section. Trying to scroll to it, will however, only scroll to the pinned header. That won't result in the newly created tab being visible in the card grid, and therefore the transition animation will fail.

**Comment by darinwf** [comment]
Commenting out these lines fixes the bug:

<img width="519" alt="Screen Shot 2022-09-18 at 1 49 17 PM" src="https://user-images.githubusercontent.com/79867437/190927593-c46c4354-59be-4ae0-ad56-0f0588f02aac.png">

Another fix might be to ensure that `Row` objects do not have duplicate `index` values. That's probably the right answer.

Another fix would be to select the section header row corresponding to the selected row instead of assuming `index == 1` means the first row in the pinned section.

**Comment by evancrow** [comment]
Selecting the section header seems good to me. Just need to bypass that for cases where there is no header, so allRows/incognito.

**Comment by evancrow** [comment]
If you wanted to go the round of fixing the indexes, `buildRows` would need to know the count of all the prior rows. For example, `lastWeek`'s start index would need to be `0 + todayRowCount + yesterdayRowCount`. 

Would probably require at least one additional loop, which we already have a lot of.

**Comment by darinwf** [comment]
The other issue I think is that `Row.id` needs to be applied to the individual `HStack` elements so we can actually target them. PR coming up...
