### ISSUE TITLE
[UI] Odd double bar under tab switcher

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4403]
See immediately above the Yesterday label

<img src="https://user-images.githubusercontent.com/41495718/191849222-c72379f3-60a2-4814-a322-63b028305247.jpg" height="400">

iOS 16.0, TestFlight 1.60.1 (279)

**Comment by evancrow** [comment]
Think this is caused by the toolbar padding adjustment... will fix.
