### ISSUE TITLE
"Clear incognito tabs when leaving incognito" only activates when a normal tab is selected.

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4405]
Noticed in #4278. Is this working as intended, or should we update the behavior to clear incognito tabs when the grid slider is activated, the app is backgrounded, etc.

**Comment by darinwf** [comment]
We shouldn't do this when the app is backgrounded as that can result in users losing tabs unexpectedly. We can't know for sure that the user is the one who deliberately put the app in the background.

I think it could make sense to close incognito tabs when the grid slider is activated.
