### ISSUE TITLE
Regression: Space pin doesn't update when I call SpaceStore.refresh()

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4414]
To replicate:
1. Pin a Space on WebUI
2. Verify that Space is shown as pinned on iOS
3. Unpin the Space on WebUI
4. Do an action that triggers iOS SpaceStore.refresh (e.g., select a tab, then go back to the card grid)
5. Go to Spaces and wait a few seconds. The pin will still be there (expected behavior: pin has disappeared)

Edit: It will update after force quitting the app and relaunching.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3c278
