### ISSUE TITLE
iOS 16 paste url and go Error

### ISSUE THREAD

**Issue by barisertgrul** [neevaco/neeva-ios#4435]
NOTE: If this is a security or privacy related issue, please email
incidents@neeva.co instead of submitting an issue on GitHub.

Thank you for submitting an issue. Provide as much information as you can.

## Expected behavior

when user paste and go to the url, tab bar needs to stay at the bottom

## Actual behavior

after paste and go to the url, tab bar moves up to the middle of the screen

This issue can not be reproduce on ios 15 

## Steps to reproduce the problem

1. copy a url
1. open neeva app and click on search bar
1. click on paste and go

## Screenshots or recordings

https://user-images.githubusercontent.com/17303291/192891328-005a80e1-8ec6-43b6-b0b6-1f21c826d075.MP4

This is a big help if possible and relevant.

## Hardware and software

- Your device: iPhone 13 Pro max
- OS version: 16.0
- App version: Neeva Browser 1.60.5 (282.1)
    - Found in app `Settings > About`

**Comment by evancrow** [comment]
Duplicate of #4379
