### ISSUE TITLE
Re-implement card transition animation using matchedGeometryEffect

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4438]
The current animation is a bit janky, complex and fragile. Based on some early investigations, it looks like we should be able to great simplify by using `matchedGeometryEffect`.

Slack thread:
https://neevaco.slack.com/archives/C03CTK4DA3B/p1664304615259989

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3c2hw
