### ISSUE TITLE
Selecting text from webpage is unreliable

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#4441]
it appears that selecting and copying text from websites via tap and hold can fail sometimes.

https://github.com/neevaco/neeva/issues/76433

**Comment by jedireza** [comment]
This seems like something that's a core mechanic of iOS/webview. Going to close for now since I'm not seeing any issues selecting text and copying it. If we could get some screen captures that would be awesome. I'd like to see what it looks like.
