### ISSUE TITLE
FastTap Images Don't Update With Typing+New Results

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#4458]
Repro:
- Start typing a query and wait for the wiki suggestion 
- Continue writing the query until a different wiki suggestion appears
- The image doesn't update for the new wiki result, uses the original one 

Screen recording:

https://user-images.githubusercontent.com/37356984/193935517-186dc42c-28af-4a25-ac8c-e3ef65b5829d.MOV

fyi @chung-lai

**Comment by chung-lai** [comment]
taking a look, looks like it could be related to SDWebImage upgrade

**Comment by chung-lai** [comment]
@EdwardJTL pointed out we can add an id to the image view so it resets the UI state
