### ISSUE TITLE
Double toast on iPad when using History

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4460]
Repro:
- Open url in normal mode
- Go to incognito
- Open history
- Long press a history item and click Open in new tab

https://user-images.githubusercontent.com/41495718/193945171-c4a6dd6e-8bce-436a-b30a-4aadc92c6035.mp4

**Comment by evancrow** [comment]
Fixed by #4396 :)

**Comment by evancrow** [comment]
I saw this too, but it's fixed by the new History UI using the OverlayManager system.
