### ISSUE TITLE
Dummy tab appears on incognito after cold start

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4463]
Preference close incognito tabs when leaving incognito ON

Video for repro:

https://user-images.githubusercontent.com/41495718/193977638-0f14e0f9-db4e-40e8-962c-431766a363c9.mp4

**Comment by evancrow** [comment]
Is this from `main` or #4452? `main` works fine for me.

**Comment by evancrow** [comment]
K, will take a look at this as a part of that PR.

**Comment by evancrow** [comment]
This was set up before we had EmptyCardGrid. It seems reasonable to just remove lines:

```
if Defaults[.lastSessionPrivate], !tabToSelect.isIncognito {
    tabToSelect = addTab(isIncognito: true, notify: false)
}
```

so the incognito grid just appears empty as it should.
