### ISSUE TITLE
Cookie Popups # does not reset after navigating to new page

### ISSUE THREAD

**Issue by chung-lai** [neevaco/neeva-ios#4482]
1. Perform a neeva search (cookie pop up # stays 0)
2. Install new app
3. Navigate to a site with cookie popup
4. Perform a neeva search (cookie pop up # now reports 1)
5. Open Neeva shield

https://user-images.githubusercontent.com/87332578/194924991-8387eb54-6d75-4f5a-8a0e-2d26b2a8deb8.mov

Expected: cookie pop up # reset to 0

Actual: cookie pop up # still report 1

cc @evancrow

**Comment by evancrow** [comment]
This is probably because we show 1 in the menu if there was a cookie blocked on the domain before. So we probably blocked a popup on the marketing page, and now for every Neeva domain, we show 1 in the menu. 

Should restrict that domain filter more.
