### ISSUE TITLE
Explore using the new (as of iOS 15) interactionState attribute on WKWebView

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#4489]
It looks like interactionState was added to WKWebView to help solve the problem of saving and restoring session state for a webview. If so, this could potentially eliminate a lot of crufty code in our session restore mechanism.

We should explore seeing how this works and how much it can help simplify our code.

Link:
https://developer.apple.com/documentation/webkit/wkwebview/3752236-interactionstate

**Comment by darinwf** [comment]
Here's the webkit patch that added it:
https://bugs.webkit.org/show_bug.cgi?id=220958

This is very promising!

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3c2wy
