### ISSUE TITLE
Toast appears too high on fullscreen modal

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4550]
<img src="https://user-images.githubusercontent.com/41495718/199074823-7a4bd3c9-0ff4-4f82-9386-22992da3eac6.png" height="500">

Repro:
- Close a tab from the card grid
- Quickly open Settings from the overflow menu

This is likely happening because the toast displays above the bottom bar. However, when the full screen modal is shown, it doesn't look quite right.

**Comment by evancrow** [comment]
Could be! We were also discussing switching to archiving tabs instead of closing them, which would remove the need for this toast.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3c4hk
