### ISSUE TITLE
Unclear text displayed when history/archived tabs search has no results

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4551]
<img src="https://user-images.githubusercontent.com/41495718/199083442-6b3631e3-4151-4ee8-8d1e-798771fce208.jpeg" height="600">

It would probably make sense to change this text to indicate that no search results were found.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3c4nz
