### ISSUE TITLE
`AddToSpaceRequest` sometimes has unnecessary state tracking

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4555]
For an example, see here: https://github.com/neevaco/neeva-ios/pull/4541/files#diff-95e35da376b1799f269e6b69b8e7a99d033f1519112537bc8ef96fae4ee58cf8R1706 . If we don't care about the state, we should not track it. This will improve the app's performance.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3c4v8
