### ISSUE TITLE
Changing the "Block pop-up windows" preference does nothing

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4559]
Demo site:
https://www.quackit.com/javascript/popup_windows.cfm

When the preference is set to allow pop-ups...

Expected behavior:
Clicking the button opens a new tab

Actual behavior:
Clicking the button opens the page in the same tab

It does work when I force quit the app, but this should not be necessary.

**Comment by jedireza** [comment]
Is this being tracked somewhere? Sounds like a user report. Also I think this WAI.
