### ISSUE TITLE
Member report: ics files might not be handled correctly

### ISSUE THREAD

**Issue by jonathangarelick** [neevaco/neeva-ios#4562]
🔒 https://app.clickup.com/t/2w46bzj

**Comment by evancrow** [comment]
ICS files should be opened in a SafariViewController. That functionality must have broken recently.

**Comment by evancrow** [comment]
Specified under `BrowserViewController+WebViewDelegates.isSpecialAppleURL`, maybe the path extension isn't correctly identified?

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/2w46bzj
