### ISSUE TITLE
Enable automated testing of signed-in features (e.g., spaces)

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#541]
@darinwf:

> I think even better would be to use dependency injection here for the spaces backend so it can be substituted with a dummy / preview backend. (OK for that to be a different PR.)

(https://github.com/neevaco/neeva-ios-phoenix/pull/539#discussion_r646879506)

**Comment by evancrow** [comment]
Spaces, signed in testing infra has been built
