### ISSUE TITLE
Consider removing __firefox

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#57]
I haven't evaluated its purpose but we should try to remove it if we can. For one thing, it is one way that our browser will look different than other browsers on iOS. Yes, we will be grouped with Firefox, but together with Firefox, we are adding another bit of entropy that could be helpful in fingerprinting users. Also, we should be worried about how well hardened __firefox (and in particular any methods exposed on it) may be to attack. If any of those are IPCs back to trusted code, we'd need to worry about that being a privilege escalation vector.

**Comment by jedireza** [comment]
Moved to ClickUp: 🔒 https://app.clickup.com/t/3vxf3cg
