### ISSUE TITLE
No option to send as PDF from iPad Air 2

### ISSUE THREAD

**Issue by michellew7** [neevaco/neeva-ios#648]
## Steps to reproduce
1. visit https://sos.oregon.gov/business/Documents/business-guides/start-business-guide.pdf
2. tap on share icon
3. see share icon

### Expected behavior
have option to send as PDF

### Actual behavior
no option to send as PDF

### Device & build information
* Device: iPad Air 2
* Build version:  iOS 14.6
### Notes
Attachments: 

Neeva app:
![IMG_DFB12ABF861C-1](https://user-images.githubusercontent.com/62567819/122312175-8da34280-cec8-11eb-8baf-3c7708faea13.jpeg)

Safari app:

![image](https://user-images.githubusercontent.com/62567819/122312222-9d228b80-cec8-11eb-9d81-32b03bb19670.png)

![image](https://user-images.githubusercontent.com/62567819/122312238-a7448a00-cec8-11eb-8177-8df027bc327d.png)

@yozuysal @jed-fox-neeva @darinwf FYI

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxf95c
