### ISSUE TITLE
Consider showing historical search queries when typing into the URL bar in incognito mode

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#674]
Consider showing historical search queries when typing into the URL bar in incognito mode

We disable talking to Neeva suggest service when in incognito mode but we do show results as you type based on local history. We exclude search results from that because in a non-incognito session those are better served live from the suggest service. We could consider showing local history based search suggestions though when in incognito mode. That is what chrome appears to do. Or we could decide that it is best as is to avoid unnerving users who may not understand the nuance here.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxf9an
