### ISSUE TITLE
Consider using push notifications to bring the user back into the app upon email confirmation

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#841]
Consider using push notifications to bring the user back into the app upon email confirmation

When the user creates a new Neeva account using our OKTA flow, we need to verify their email address. We should consider having the app notice when email verification has completed. This would probably work best via push notifications. This will help users get back into the app and continue where they left off.

@seth737 FYI

**Comment by evancrow** [comment]
We've finished the whole notification thing, and are no longer pursuing this use case
