### ISSUE TITLE
Consider enabling a dark mode override for web sites (aka firefox-style night mode)

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#887]
Consider enabling a dark mode override for web sites (aka firefox-style night mode)

Just filing this bug as a placeholder. We have gotten at least one request for this feature: https://github.com/neevaco/neeva-ios-phoenix/issues/880

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfa0w
