### ISSUE TITLE
Autocomplete should allow non-domains

### ISSUE THREAD

**Issue by yozuysal** [neevaco/neeva-ios#916]
Currently the logic for autocomplete (inside HistorySuggestionModel) only allows domains for most cases (if the match is not exact). Since Suggested Sites already remembers frequent domains, we should tweak autocomplete to also suggest matches with frequent non-domain history entries (common behaviors like checking yahoo.com/finance, mlb.com/giants will be addressed through this.) 

Things to consider:

1) Would also be good to record non-domain vs domain as log and check
2) Should we still restrict to path only? and not include query?

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfa4a
