### ISSUE TITLE
Login button does not work on https://mv5.mvelopes.com/login  when using 1Password or Safari Saved Passwords

### ISSUE THREAD

**Issue by michellew7** [neevaco/neeva-ios#971]
Details from the member (paraphrased for simplicity):

1) open https://mv5.mvelopes.com/login  on the Neeva app
2) pull up saved username and password from 1Password or Apple Keychain
3) Tap to log-in

Expected:
Credentials are accepted, log-in successful

Actual: 
Login button on the site doesn't work, eventually works but credentials not accepted. 

Manually adding the username and password works and does not have this issue.

--------------------------------------------------------

Full details:

When I open the website in the Neeva app I navigate to the username field, pull-up my saved username/password from 1Password or Safari saved passwords to fill in the values, hit enter and the Login button on the site doesn’t work.  After trying the Login button it will eventually tell me the username/password is invalid. 

I just tried a different approach. Instead of using auto-fill from 1Password, I manually entered my username and copy/pasted my password from 1Password. That worked. Must be some issue when you allow 1Password or Safari to automatically fill in the values. 

@jed-fox-neeva @darinwf not sure if this is a known issue

**Comment by jedireza** [comment]
I know this issue is super old. Sounds related to password managers and autofill. I've confirmed this is working with 1Password. Though I didn't test on that particular website.
