### ISSUE TITLE
Implement some sort of kill switch

### ISSUE THREAD

**Issue by jed-fox-neeva** [neevaco/neeva-ios#993]
See [the notes from the discussion](https://paper.dropbox.com/doc/Mobile-eng-weekly--BOnDaCL71Lw4mZRBW_Xmpp3sAg-X8OgmUWiOPhsJ28N4j8ZT#:uid=991680753082568751043070&h2=Meeting-7/15/2021).

Options:
- lock out all API requests to Neeva, but still allow usage while signed in
  - this could take the form of the server returning an error
- use a feature flag to deny access to the entire app

Considerations:
- Must be bug-free and easy to maintain
- As a default browser app, users expect to be able to tap a link and view a website; a global kill switch would remove that functionality
  - consider bumping them into a Safari View Controller?
- want to log the number of people that hit this

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3vxfavj
